### ISSUE TITLE
Review gh actions

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#1000]
I'm not sure what happened, but gh actions approved this pr: https://github.com/pajbot/pajbot/pull/990
However after running the reformat script, I found changes that needed to be made: https://github.com/pajbot/pajbot/pull/999

Should probably look into why this didn't work correctly the first time.

**Comment by RAnders00** [comment]
I cannot replicate that the master branch needs reformatting, both running `reformat.sh` locally as well as on the CI.
