### ISSUE TITLE
Add option for slotmachine to only be accessible after somebody subs

### ISSUE THREAD

**Issue by Felanbird** [pajbot/pajbot#1015]
would make the options consistent across both the slotmachine and roulette modules (normal settings | whisper option | after sub option)

prevents chat from being filled with gambling spam 24/7

![image](https://user-images.githubusercontent.com/41973452/92990598-ad29bc80-f4ab-11ea-924e-515ad2d5e80a.png)

false by default

**Comment by alazymeme** [comment]
How do you suggest it notifies users that they can use the slot machine? Won't it get spammy if someone has both modules enabled?

**Comment by Felanbird** [comment]
> How do you suggest it notifies users that they can use the slot machine? Won't it get spammy if someone has both modules enabled?

Interesting thought, if this issue was brought up after the fact, I probably would just change one of the modules to "Gambling is now allowed...." and leave the second one blank, but I don't have a better idea than that.

**Comment by RAnders00** [comment]
Due to pajbot [being moved into maintenance mode](https://github.com/pajbot/pajbot/blob/master/README.md) I'm closing this feature request.
