### ISSUE TITLE
Steal points module

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#1016]
Add a module to allows users to steal points from other people, but people MAY go to "jail" and get fined if caught and unsuccessfully stealing. Should have sub-only options like only allowing subs to steal, etc. Should be also able to adjust the odds of being caught and the messages and shit.

Partial credit to @fourtf

**Comment by RAnders00** [comment]
What happens when a user goes to jail?

**Comment by alazymeme** [comment]
> What happens when a user goes to jail?

I suppose they get timed out for x amount of time? (depending on how much they were trying to steal). Maybe they have a bail that they or someone else has to pay in order to get them out? (`!bail user`) If you are caught stealing, you can't attempt to steal for 24 hours. If you are successful, then the cooldown will be significantly shorter.
