### ISSUE TITLE
Add console logging for irc errors

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#1020]
I've been running into issues running pajbot's recently and I get the most useless error:
`Disconnected from IRC (Connection reset by peer)`

It would be cool if there was more logging used so I didn't have to do the guess work of figuring out the problem.

**Comment by RAnders00** [comment]
For anyone that wants to implement this, this is essentially logging any `NOTICE` messages on a connection before a `001` is received (successful login).

**Comment by alazymeme** [comment]
I can help you out by closing this one too
