### ISSUE TITLE
Add alternate certbot install steps for Ubuntu

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#1023]
I noticed on the certbot website that they suggest installing via snap for ubuntu. Then to enable certbot with cloudflare you have more completely different instructions: https://certbot.eff.org/lets-encrypt/ubuntufocal-nginx
Probably need to update this somehow (before this I was having issues)

**Comment by RAnders00** [comment]
the install instructions are for debian, not ubuntu :)

For debian, I think our instructions are fine: https://certbot.eff.org/lets-encrypt/debianbuster-other

**Comment by RAnders00** [comment]
It says "The following instructions should work without any changes on Debian and Ubuntu." on the install docs currently. As far as I can see the snap approach won't really work on Debian without having to install snapd first.

I think also for the sake of simplicity an apt-get install is more straight forward than diving into the whole snap ecosystem, just to run certbot.

**Comment by alazymeme** [comment]
Alright I'll pr some install docs for ubuntu 😄

**Comment by RAnders00** [comment]
You can add notes to the existing docs in places where the recommended steps for ubuntu are different.

**Comment by alazymeme** [comment]
> You could also add notes to the existing docs in places where the recommended steps for ubuntu are different.

I can, not a problem. The wiki I suggested enabled you to have multiple tabs (eg for different distros), so I'm not sure.

**Comment by alazymeme** [comment]
Don't worry, I'll close this one for you
