### ISSUE TITLE
ID for redeemed prize

### ISSUE THREAD

**Issue by vchan37** [pajbot/pajbot#1050]
what should i fill in this one ? i still dont understand 
![image](https://user-images.githubusercontent.com/71643519/95887871-8dd3c700-0daa-11eb-8b7a-412f2055ab8a.png)

**Comment by Felanbird** [comment]
@vchan37 We are not able to help you with this as this is not a pajbot module, this is a module from a forked version of pajbot.

Go to the moderators tab at the top and contact whoever's name is at the top marked with level 2000

![image](https://user-images.githubusercontent.com/41973452/95889800-e70f0c80-0d50-11eb-8841-7577f8728161.png)

**Comment by TroyDota** [comment]
@vchan37 is this M0xyy? Troy#0003 write me on discord.

**Comment by vchan37** [comment]
> @vchan37 is this M0xyy? Troy#0003 write me on discord.

its on dreamocell, i'll hit you on discord. can close the thread thx
