### ISSUE TITLE
502 bad gateway

### ISSUE THREAD

**Issue by StephanBruh** [pajbot/pajbot#1054]
I wanted to add a new bot (already have 2 pajbots running) but when trying to add the 3rd one I got a 502 bad gateaway. When i checked the logs It says something about a module? Anyone any idea what it could be?

Here are my logs.
`pajbot-web@drawing[22525]:   File "/opt/pajbot/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1473, in _handle_dbapi_exception
pajbot-web@drawing[22525]:     util.raise_from_cause(sqlalchemy_exception, exc_info)
pajbot-web@drawing[22525]:   File "/opt/pajbot/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
pajbot-web@drawing[22525]:     reraise(type(exception), exception, tb=exc_tb, cause=cause)
pajbot-web@drawing[22525]:   File "/opt/pajbot/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
pajbot-web@drawing[22525]:     raise value.with_traceback(tb)
pajbot-web@drawing[22525]:   File "/opt/pajbot/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
pajbot-web@drawing[22525]:     cursor, statement, parameters, context
pajbot-web@drawing[22525]:   File "/opt/pajbot/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
pajbot-web@drawing[22525]:     cursor.execute(statement, parameters)
pajbot-web@drawing[22525]: sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "module" does not exist
pajbot-web@drawing[22525]: LINE 2: FROM module
pajbot-web@drawing[22525]:              ^
pajbot-web@drawing[22525]: [SQL: SELECT module.id AS module_id, module.enabled AS module_enabled, module.settings AS module_settings
pajbot-web@drawing[22525]: FROM module]
pajbot-web@drawing[22525]: (Background on this error at: http://sqlalche.me/e/f405)
pajbot-web@drawing[22525]: unable to load app 0 (mountpoint='') (callable not found or import error)
pajbot-web@drawing[22525]: *** no app loaded. GAME OVER ***
pajbot-web@drawing[22525]: VACUUM: unix socket /var/run/pajbot/drawing/web.sock removed.
pajbot-web@drawing.service: Main process exited, code=exited, status=22/n/a
pajbot-web@drawing.service: Failed with result 'exit-code'.
pajbot-web@drawing.service: Service hold-off time over, scheduling restart.
pajbot-web@drawing.service: Scheduled restart job, restart counter is at 4.
Stopped pajbot-web for drawing.
Started pajbot-web for drawing.
pajbot-web@drawing[22543]: [uWSGI] getting INI configuration from uwsgi_shared.ini
pajbot-web@drawing[22543]: *** Starting uWSGI 2.0.18 (64bit) on [Fri Oct 23 20:59:59 2020] ***
pajbot-web@drawing[22543]: compiled with version: 7.5.0 on 19 August 2020 19:56:39
pajbot-web@drawing[22543]: os: Linux-4.15.0-91-generic #92-Ubuntu SMP Fri Feb 28 11:09:48 UTC 2020
pajbot-web@drawing[22543]: nodename: vmi341266.contaboserver.net
pajbot-web@drawing[22543]: machine: x86_64
pajbot-web@drawing[22543]: clock source: unix
pajbot-web@drawing[22543]: detected number of CPU cores: 6
pajbot-web@drawing[22543]: current working directory: /opt/pajbot
pajbot-web@drawing[22543]: detected binary path: /opt/pajbot/venv/bin/uwsgi
pajbot-web@drawing[22543]: !!! no internal routing support, rebuild with pcre support !!!
pajbot-web@drawing[22543]: your processes number limit is 63984
pajbot-web@drawing[22543]: your memory page size is 4096 bytes
pajbot-web@drawing[22543]: detected max file descriptor number: 1024
pajbot-web@drawing[22543]: lock engine: pthread robust mutexes
pajbot-web@drawing[22543]: thunder lock: disabled (you can enable it with --thunder-lock)
pajbot-web@drawing[22543]: uwsgi socket 0 bound to UNIX address /var/run/pajbot/drawing/web.sock fd 3
pajbot-web@drawing[22543]: Python version: 3.6.9 (default, Oct  8 2020, 12:12:24)  [GCC 8.4.0]
pajbot-web@drawing[22543]: PEP 405 virtualenv detected: venv
pajbot-web@drawing[22543]: Set PythonHome to venv
pajbot-web@drawing[22543]: Python main interpreter initialized at 0x55f79d5aa520
pajbot-web@drawing[22543]: python threads support enabled
pajbot-web@drawing[22543]: your server socket listen backlog is limited to 100 connections
pajbot-web@drawing[22543]: your mercy for graceful operations on workers is 60 seconds
pajbot-web@drawing[22543]: mapped 145840 bytes (142 KB) for 1 cores
pajbot-web@drawing[22543]: *** Operational MODE: single process ***`

my config: ( maybe helps? )
`[web]
deck_tab_images = 1
modules = linefarming duels playsounds
streamer_name = drawingb0t
domain = 0ut3.kech.be
subscriber_badge_version = 0

[main]
nickname = drawingb0t
streamer = 0ut3
admin = stephanbruh
db = postgresql+psycopg2:///pajbot?options=-c%%20search_path%%3Dpajbot1_drawing

[phrases]
;welcome = {nickname} {version} running! HeyGuys
;quit = {nickname} {version} shutting down... BibleThump

[twitchapi]
client_id = noidontthinkso
client_secret = noidontthinkso
redirect_uri = noidontthinkso

[twitter]
consumer_key = abc
consumer_secret = abc
access_token = 123-abc
access_token_secret = abc
streaming = 1

[flags]
silent = 0
dev = 0

[websocket]
enabled = 1
unix_socket = /var/run/pajbot/drawing/websocket.sock
host = wss://0ut3.kech.be/clrsocket

[maintainer]
name = KKonaTestAdmin
contact_string = You can contact me over at <a href="https://KKonaTestAdmin.se/contact">CONTACT LINK</a>

[pnsl]`

**Comment by RAnders00** [comment]
This can be caused when the web process is started before the bot (because the bot process creates the database schema). Try stopping the web process, then start the bot, then start the web process up again. Let me know if that helps.

**Comment by RAnders00** [comment]
By the way, you leaked your secret_key above, you should delete it from your config (remove the entire line including the secret_key=) then a new one will be generated automatically.

**Comment by StephanBruh** [comment]
monkaS forgot, fixed it thanks, I noticed when manually starting the bot first, that one gives a error aswell

`pajbot@drawing[6046]: psycopg2.errors.InvalidSchemaName: no schema has been selected to create in
pajbot@drawing[6046]: LINE 1: CREATE TABLE IF NOT EXISTS schema_version(revision_id INT NO...
pajbot@drawing[6046]:                                    ^
systemd[1]: pajbot@drawing.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: pajbot@drawing.service: Failed with result 'exit-code'.
systemd[1]: Stopped pajbot for drawing.
systemd[1]: Started pajbot for drawing.
pajbot@drawing[6059]: [2020-10-23 23:40:12,824] [DEBUG  ] Loaded config
pajbot@drawing[6059]: [2020-10-23 23:40:12,863] [ERROR  ] Logging an uncaught exception
pajbot@drawing[6059]: Traceback (most recent call last):
pajbot@drawing[6059]:   File "main.py", line 74, in <module>
pajbot@drawing[6059]:     run(args)
pajbot@drawing[6059]:   File "main.py", line 40, in run
pajbot@drawing[6059]:     pajbot = Bot(config, args)
pajbot@drawing[6059]:   File "/opt/pajbot/pajbot/bot.py", line 154, in __init__
pajbot@drawing[6059]:     sql_migration.run()
pajbot@drawing[6059]:   File "/opt/pajbot/pajbot/migration/migrate.py", line 23, in run
pajbot@drawing[6059]:     with self.migratable.create_resource() as resource:
pajbot@drawing[6059]:   File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
pajbot@drawing[6059]:     return next(self.gen)
pajbot@drawing[6059]:   File "/opt/pajbot/pajbot/migration/db.py", line 13, in create_resource
pajbot@drawing[6059]:     cursor.execute("CREATE TABLE IF NOT EXISTS schema_version(revision_id INT NOT NULL)")
pajbot@drawing[6059]: psycopg2.errors.InvalidSchemaName: no schema has been selected to create in
pajbot@drawing[6059]: LINE 1: CREATE TABLE IF NOT EXISTS schema_version(revision_id INT NO...
pajbot@drawing[6059]:                                    ^
systemd[1]: pajbot@drawing.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: pajbot@drawing.service: Failed with result 'exit-code'.
systemd[1]: pajbot@drawing.service: Service hold-off time over, scheduling restart.
systemd[1]: pajbot@drawing.service: Scheduled restart job, restart counter is at 2390.
systemd[1]: Stopped pajbot for drawing.
systemd[1]: Started pajbot for drawing.
pajbot@drawing[6076]: [2020-10-23 23:40:16,591] [DEBUG  ] Loaded config
pajbot@drawing[6076]: [2020-10-23 23:40:16,622] [ERROR  ] Logging an uncaught exception
pajbot@drawing[6076]: Traceback (most recent call last):
pajbot@drawing[6076]:   File "main.py", line 74, in <module>
pajbot@drawing[6076]:     run(args)
pajbot@drawing[6076]:   File "main.py", line 40, in run
pajbot@drawing[6076]:     pajbot = Bot(config, args)
pajbot@drawing[6076]:   File "/opt/pajbot/pajbot/bot.py", line 154, in __init__
pajbot@drawing[6076]:     sql_migration.run()
pajbot@drawing[6076]:   File "/opt/pajbot/pajbot/migration/migrate.py", line 23, in run
pajbot@drawing[6076]:     with self.migratable.create_resource() as resource:
pajbot@drawing[6076]:   File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
pajbot@drawing[6076]:     return next(self.gen)
pajbot@drawing[6076]:   File "/opt/pajbot/pajbot/migration/db.py", line 13, in create_resource
pajbot@drawing[6076]:     cursor.execute("CREATE TABLE IF NOT EXISTS schema_version(revision_id INT NOT NULL)")
pajbot@drawing[6076]: psycopg2.errors.InvalidSchemaName: no schema has been selected to create in
pajbot@drawing[6076]: LINE 1: CREATE TABLE IF NOT EXISTS schema_version(revision_id INT NO...
pajbot@drawing[6076]:                                    ^
systemd[1]: pajbot@drawing.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: pajbot@drawing.service: Failed with result 'exit-code'.`

**Comment by RAnders00** [comment]
Looks like you forgot to create the schema pajbot1_drawing! Check https://github.com/pajbot/pajbot/tree/master/install-docs#create-a-database-schema then try again with same steps as above (start bot before web process)

**Comment by StephanBruh** [comment]
No I did "ERROR:  schema "pajbot1_drawing" already exists"

**Comment by alazymeme** [comment]
> No I did "ERROR: schema "pajbot1_drawing" already exists"

Are you running this on a dedicated server? Or WSL or something?

**Comment by StephanBruh** [comment]
> > No I did "ERROR: schema "pajbot1_drawing" already exists"
> 
> Are you running this on a dedicated server? Or WSL or something?

Yes on a server

**Comment by RAnders00** [comment]
Could you show the output from entering `\dn` in a `sudo -u postgres psql` console?

**Comment by StephanBruh** [comment]
`  List of schemas
  Name  |  Owner
--------+----------
 public | postgres
(1 row)`

**Comment by RAnders00** [comment]
Sorry, my fault. Can you do that again, except with `sudo -u postgres psql pajbot`? I forgot the `pajbot` part which means the previous command connected to the wrong database...

**Comment by StephanBruh** [comment]
`        List of schemas
        Name         |  Owner
---------------------+----------
 pajbot1_drawing     | postgres
 pajbot1_stephanbruh | postgres
 pajbot1_tommylans   | postgres
 public              | postgres
(4 rows)`

**Comment by RAnders00** [comment]
I think the owners of the schemas are wrong. Try `sudo -u postgres psql pajbot`, then `ALTER SCHEMA pajbot1_drawing OWNER TO pajbot;` (repeat for all schemas you listed above). Then try restarting the bot and report back.

**Comment by RAnders00** [comment]
(As an addition, the owner is incorrect if you forget/omit the sudo part when creating the schemas. The sudo -u pajbot before the psql command also implicitly sets the owner of the schema that is being created. I assume that‘s what went wrong in your case here.)

**Comment by StephanBruh** [comment]
Hmm thanks I think I forgot that part then for this instance. 
Thanks for your help man its fixed.
