### ISSUE TITLE
Changelog reminder github action

### ISSUE THREAD

**Issue by RAnders00** [pajbot/pajbot#1056]
https://github.com/mskelton/changelog-reminder-action

**Comment by Yagueteiro** [comment]
Hi! I would be interested to work on this. If I understood well, you want this action to be added to a workflow, correct me if I'm wrong

**Comment by RAnders00** [comment]
I would prefer if this was created as a completely new workflow. You can keep the config simple.

**Comment by RAnders00** [comment]
If you could, I would appreciate if you could also integrate a changelog check into the same workflow, e.g. https://github.com/marketplace/actions/changelog-checker or https://github.com/marketplace/actions/changelog-enforcer

**Comment by Yagueteiro** [comment]
Ok, I'll work on it! Can you please assign me, so that people are able to see I'm working on it?
