### ISSUE TITLE
Respect auth and join rate limits when initially making a bot

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#1075]
![image](https://user-images.githubusercontent.com/12804673/99889904-6d4e3500-2ca5-11eb-9776-d51b8d25afb9.png)

I found myself running into irc errors when the bot continually tries to reconnect when I make a new bot. Can we delay the attempts to every 5 seconds or something? Deleting auth keys, etc etc didnt work at all. Had to wait to be able to re-auth the bot

**Comment by RAnders00** [comment]
the default delay is 2 seconds per reconnect. that would make 5 authentication attempts per 10 seconds. So unless you were setting up 4 bots at the same time I don't see how this could be a problem?

**Comment by alazymeme** [comment]
> the default delay is 2 seconds per reconnect. that would make 5 authentication attempts per 10 seconds. So unless you were setting up 4 bots at the same time I don't see how this could be a problem?

I mean I'm just taking a shot in the dark, but it's possible it's the reason I'm having issues. Unless you can think of something else?

If I leave the bot un-authed for too long, it just disconnects from irc and refuses to reconnect

**Comment by alazymeme** [comment]
I can't reproduce this, so I'm just closing it. Seems people not following basic instructions can't be fixed by code.
