### ISSUE TITLE
Fix Styling on website so google search doesn't complain.

### ISSUE THREAD

**Issue by TroyDota** [pajbot/pajbot#1089]
![image](https://user-images.githubusercontent.com/49777269/101079468-32ef6c80-35b0-11eb-9a38-0aff037a433f.png)
![image](https://user-images.githubusercontent.com/49777269/101079486-384cb700-35b0-11eb-9328-d2b23403985c.png)
![image](https://user-images.githubusercontent.com/49777269/101079504-3e429800-35b0-11eb-82c7-58e45b3e569a.png)

the content wider than screen and the clickable items too close together are 
![image](https://user-images.githubusercontent.com/49777269/101079649-6c27dc80-35b0-11eb-83ce-0c230f88e75d.png)

Both can be fixed with a grid layout and then adding a gridgap for the content too close together and a grid column template for things going off screen so this happens
 
![image](https://user-images.githubusercontent.com/49777269/101085070-8fa25580-35b7-11eb-9629-76a2e8763cb1.png)

![image](https://user-images.githubusercontent.com/49777269/101089166-7ac8c080-35bd-11eb-9264-1f88fd51bee5.png)

**edit nuuls changed the format of my video file to mp4 when its flv BrokeBack**
https://i.nuuls.com/hRBw8.mp4

^ Small video demonstrating what I mean. Is it worth the pr?

**Comment by TroyDota** [comment]
A better more long-term solution, is to not use python to serve the webpage and move to something like react/vue/angular and use python flask as a restful or gql api.

**Comment by alazymeme** [comment]
I don't think mobile was in mind when working on this website for a very good reason. I'd love to migrate the website to something like react + material ui, but the time it would take to redo the entire UI just because google complains about mobile not working well? I personally don't think it's worth it. But if you'd like to work on it, go ahead.

I also wouldn't consider this as being a bug, but more a feature request.

**Comment by RAnders00** [comment]
This is arguably extremely minor and as you said better solved with a general overhaul of the website which is something we won't accept given that pajbot has been moved into maintanance mode. I'm closing this for now. If you want to implement a "small" fix to these problems you are of course open to make a pull request with a fix.
