### ISSUE TITLE
502 gateaway, journal openssl errors

### ISSUE THREAD

**Issue by StephanBruh** [pajbot/pajbot#1096]
Tried reinstalling pajbot on my new server, followed every step correctly.  (postgres db user is correct)
When I tried accesing the site I got 502, checked the journal and got both errors in web and pajbot. And cant find whats wrong/how to fix.

`pajbot-web journal:`
[uWSGI] getting INI configuration from uwsgi_shared.ini
*** Starting uWSGI 2.0.18 (64bit) on [Wed Dec  9 20:38:34 2020] ***
compiled with version: 9.3.0 on 09 December 2020 18:50:49
os: Linux-5.4.0-26-generic #30-Ubuntu SMP Mon Apr 20 16:58:30 UTC 2020
machine: x86_64
clock source: unix
detected number of CPU cores: 6
current working directory: /opt/pajbot
detected binary path: /opt/pajbot/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 63830
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /var/run/pajbot/stephanbruh/web.sock fd 3
Python version: 3.8.5 (default, Jul 28 2020, 12:59:40)  [GCC 9.3.0]
PEP 405 virtualenv detected: venv
Set PythonHome to venv
Python main interpreter initialized at 0x55bd15897bb0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
Traceback (most recent call last):
  File "./app.py", line 4, in <module>
    import pajbot.web
  File "./pajbot/web/__init__.py", line 8, in <module>
    from pajbot.apiwrappers.twitch.helix import TwitchHelixAPI
  File "./pajbot/apiwrappers/twitch/helix.py", line 7, in <module>
    from requests import HTTPError
  File "/opt/pajbot/venv/lib/python3.8/site-packages/requests/__init__.py", line 95, in <module>
    from urllib3.contrib import pyopenssl
  File "/opt/pajbot/venv/lib/python3.8/site-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/opt/pajbot/venv/lib/python3.8/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/opt/pajbot/venv/lib/python3.8/site-packages/OpenSSL/SSL.py", line 664, in <module>
    _lib.Cryptography_HAS_TLSEXT_HOSTNAME, "SNI not available"
AttributeError: module 'lib' has no attribute 'Cryptography_HAS_TLSEXT_HOSTNAME'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. GAME OVER ***
VACUUM: unix socket /var/run/pajbot/stephanbruh/web.sock removed.
 Main process exited, code=exited, status=22/n/a

`bot log:`
`Traceback (most recent call last):
  File "main.py", line 7, in <module>
    from pajbot.bot import Bot
  File "/opt/pajbot/pajbot/bot.py", line 10, in <module>
    import requests
  File "/opt/pajbot/venv/lib/python3.8/site-packages/requests/__init__.py", line 95, in <module>
    from urllib3.contrib import pyopenssl
  File "/opt/pajbot/venv/lib/python3.8/site-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/opt/pajbot/venv/lib/python3.8/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/opt/pajbot/venv/lib/python3.8/site-packages/OpenSSL/SSL.py", line 664, in <module>
    _lib.Cryptography_HAS_TLSEXT_HOSTNAME, "SNI not available"
AttributeError: module 'lib' has no attribute 'Cryptography_HAS_TLSEXT_HOSTNAME'
Main process exited, code=exited, status=1/FAILURE
Failed with result 'exit-code'.`

Also tried reinstalling the dependencies what goes without errors

**Comment by RAnders00** [comment]
It's probably an external breakage: https://github.com/pyca/pyopenssl/issues/973 Will investigate whether something has to be fixed on our end.

**Comment by RAnders00** [comment]
@StephanBruh When testing this I'm not having problems starting up a web process with a fresh install (I can't reproduce your problem anymore). It's quite possible that it was a breakage in the openssl dependency that has since been fixed by the pyopenssl/cryptography maintainers and that can be solved by a reinstall of the dependencies. For this reason, could you try deleting the entire venv (`rm -r venv`) and recreating it (`./scripts/venvinstall.sh`), then give the web process a restart?

**Comment by StephanBruh** [comment]
> @StephanBruh When testing this I'm not having problems starting up a web process with a fresh install (I can't reproduce your problem anymore). It's quite possible that it was a breakage in the openssl dependency that has since been fixed by the pyopenssl/cryptography maintainers and that can be solved by a reinstall of the dependencies. For this reason, could you try deleting the entire venv (`rm -r venv`) and recreating it (`./scripts/venvinstall.sh`), then give the web process a restart?

That fixed the issue thanks!
