### ISSUE TITLE
Put pajbot into a maintenance mode

### ISSUE THREAD

**Issue by RAnders00** [pajbot/pajbot#1097]
Here's my idea:
- Update README to say that we primarily fix issues to keep the bot running, e.g. fixing bugs, updating dependencies and the code interacting with deprecated/broken external APIs, and that pajbot isn't really open to major feature requests or enhancements anymore
- After doing that, close issues with major feature requests; If a issue can't be closed altogether reduce it to bugfixes and small improvements

Please share your thoughts below @pajlada @alazymeme ![image](https://user-images.githubusercontent.com/1629196/101913284-13190380-3bc3-11eb-918e-af4fef2e8a0f.png)

**Comment by alazymeme** [comment]
What if I want to add something? ![image](https://user-images.githubusercontent.com/12804673/101960247-c250eb80-3c52-11eb-9717-30b593c7a490.png)

I'm not sure about this idea, it's not like pajbot2 is in a fully featured state as of yet.

**Comment by pajlada** [comment]
We wouldn't be fully closed to features being implemented in pajbot, but rather we would make it clear that the project is not being actively developed by the project owners. We ensure things run, we ensure bugs are squashed, but we don't push for or accept new feature **requests**.

If an issue is created with a feature request, it could stay open for a short time to see if someone wants to do it, but if no one wants to own it then we would close it.

I'll start writing on a README pr now
