### ISSUE TITLE
Mass ping timeout not factored into largest timeout checking

### ISSUE THREAD

**Issue by Felanbird** [pajbot/pajbot#1117]
![image](https://user-images.githubusercontent.com/41973452/103423969-d44dec00-4b77-11eb-87e8-7b922effd508.png)

First user is only given 1m for pb1 banphrase and 350s via pb2 height [massping does not fire because banphrase fired]

Second user is properly given 20700s for massping and 350 via pb2 height which punisher corrects to be 20698s [no banphrase so massping fires]

**Comment by RAnders00** [comment]
The issue is more that pajbot1 doesn't actually figure out what the longest timeout is, it just fires all the modules in a certain order and the first one that returns False from its message handler stops the other modules from getting the message.

**Comment by alazymeme** [comment]
> The issue is more that pajbot1 doesn't actually figure out what the longest timeout is, it just fires all the modules in a certain order and the first one that returns False from its message handler stops the other modules from getting the message.

Shouldn't pajbot be taking into account the current user's timeout time? In a similar way to "trying to paid timeout someone who has been timed out for 10m due to a banphrase".

**Comment by RAnders00** [comment]
I don‘t think there is a solution to this that doesn‘t require internal refactors.
On a more positive note here, pajbot2 was actually designed with this problem in mind, and in pajbot2 the processing does not stop on the first „matched module“ like pajbot1 does.
