### ISSUE TITLE
run_through_banphrases parser doesn't work for modules

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#1118]
Have tried adding it to both the math module and the lastfm module. The bot still sends the response as if it had never checked for the banphrase.

Relevant code:
https://github.com/alazymeme/pajbot/blob/8a0622c62da522bdbad7fca1180a4c2a29d46940/pajbot/modules/math.py#L86-L94

**Comment by RAnders00** [comment]
I don‘t think that‘s what the flag is used for. In modules you‘d use bot.safe_privmsg and bot.safe_me, e.g.: https://github.com/pajbot/pajbot/blob/c3058eb1b71468b180871042eccebbe144fc845e/pajbot/bot.py#L628

if needed you could also add a safe_say method which is like say (escapes chat commands like `/timeout` from accidentally being executed)

**Comment by RAnders00** [comment]
Example from trivia module: https://github.com/pajbot/pajbot/blob/c3058eb1b71468b180871042eccebbe144fc845e/pajbot/modules/trivia.py#L162

**Comment by alazymeme** [comment]
Cheers, looks like it works
