### ISSUE TITLE
Replace usages of PogChamp

### ISSUE THREAD

**Issue by RAnders00** [pajbot/pajbot#1121]
https://github.com/pajbot/pajbot/search?q=PogChamp

I guess we wait until twitch releases a PogChamp replacement? https://twitter.com/Twitch/status/1347003153749737479

**Comment by alazymeme** [comment]
They have a new replacement, but it's not the best. Maybe we should replace it with KomodoHype (since it's global, compared to VisLaud)

**Comment by RAnders00** [comment]
Since Twitch added a PogChamp replacement I think I'll close this for now, it would have just sucked if there was no PogChamp emote at all

**Comment by alazymeme** [comment]
2/2 PogChamp emotes have been terrible. Would be an idea to change it, but I'm not sure if it's worth it.

**Comment by RAnders00** [comment]
We might look into just making as many module output strings configurable as possible (with module settings).

**Comment by alazymeme** [comment]
> We might look into just making as many module output strings as possible configurable (with module settings).

I think we should find a "decent" way of doing it. Simply dumping string options into modules makes it look very cluttered and overwhelming. That's how I currently feel about the simple sub alert module...
