### ISSUE TITLE
Variables don't work in auth error message

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#1126]
Should be `No authentication token found for user impactdroid (636258438) in redis`
![image](https://user-images.githubusercontent.com/12804673/104585914-790c1580-56b0-11eb-8eca-ef6396006f0c.png)

**Comment by RAnders00** [comment]
Can you show the full error, I think it‘s supposed to say the interpolated string somewhere?

**Comment by alazymeme** [comment]
Oh yeah it shows on the next line

**Comment by RAnders00** [comment]
![image](https://user-images.githubusercontent.com/1629196/104809854-a7910a00-57f0-11eb-9a36-118e777c2c7d.png)

**Comment by alazymeme** [comment]
![Ranerds](https://user-images.githubusercontent.com/12804673/104810003-8efb1100-583d-11eb-8031-20f568907dc7.png)
