### ISSUE TITLE
Quest System

### ISSUE THREAD

**Issue by pajlada** [pajbot/pajbot#118]
## Overview

The quest system should be a module.
Whenever a stream is started, emit the stream_started signal.
This signal is read by the Quest module.
We randomize a daily quest out of all available quests.
This is the quest that's shown in the !quest or !currentquest command.
The quest should be its own object that has a start() and stop() method.
the start() method will register all signals that it needs to track.
The quest status of each user should be stored in redis.
## Quests
- [ ] Time out a trump/reynad/nostam/massan sub
- [ ] Create an X-width pyramid
- [x] Use X emote Y times
- [ ] Type X lines in Y time
- [x] Get timed out by someone
- [ ] Have your name written in chat by others X amount of times, or Have your name written in chat by X people
- [ ] Russian roulette someone: One of you finish the quest, the other doesn't.
- [ ] Spend X amount of points.
- [x] Win X points in a single duel
- [x] Win X points in duels in one day
- [x] Win a raffle/emote bingo.
- [ ] Be the first (or only?) user to type a certain emote within the last X minutes?
- [ ] Use an emote that hasn't been used in the last X minutes or Y lines
- [ ] Be part of an emote combo of at least X size. Should the emote be specific?
- [ ] Timeout a user who used emote X in the last minute.
- [x] Win a bet on a hearthstone game. This would require a shit ton of coding to get done, but would be really dank. Some sort of modified Hearthstone Deck Tracker could be run on Forsens PC to keep track of the matches. Check out trackobot? seems to have an open API. SeemsGood trying now
- [ ] Use X different emotes in Y time
- [ ] How about a quest where you must commit sudoku (with the sudoku command), which times you out for like 5 minutes?
- [ ] a personal emote bingo (or what u call it) , everyone has to guess their own unique emote (OG and bttv)
- [ ] don't type in chat for XX minutes
- [ ] A Russian roulette raffle where a percentage of players lose all their points while the rest get the tokens pajlada
- [ ] The Lover's Ball. Make 2 users "lovers", they have to type eachothers name in chat in a 1 minute span, and get rewarded when that's done. So when you ask the bot you get the name of your lover.
- [ ] Roulette 1000 points?
- [ ] not sure if it's in log or mentioned by something, It'd just do a quest where you have to ask friends to make the quest for you - like that they have to tune in to stream and type command for you !watchingfor nickname (like 5friends have to do that) -- 5friends would know you listen to gachi gachiGASM
- [x] win X duels in a day
- [ ] show text on screen like "type memes123", and you have to do it within 5 seconds. Kappa
- [x] only type messages with /me for X lines or X minutes?
- [ ] go all in in a roulette
- [ ] hide and seek quest: one user types !hide and after 1 minute someone has to type !found "username". if no one types it in a 1 minute timeframe the quest is fullfilled
- [ ] write alphabet, one letter at a time, in sequence
- [ ] ajlada he meant snusbot types an emote and you have to be in the top x people to type it pajaW
- [ ] somehow, have X people type your name Y times
- [ ] A quest that when a key word (color) appears like "green", you have to type green emotes ( FeelsBadMan ) , when it is "black" you type black emotes ( TryHard )
- [ ] quest to morn the loss of a chat member when they are timed out by typing something like RIP <name>
- [ ](TWITCH PLAYS, chat moves emote on screen) yah, its hard as a quest, since you have to repeat that shit and it would be too much spam on screen. How about making it like a bonus event? Where a certain amount of viewers have to enter a command to trigger it
## Collective quests
- Have 10 people type the same message in a row.
- Be part of a 200 emote combo.
- Be part of the winning team of an "emote war"/"emote counter war"
- 5 people join a team with something like !teamup <names> and then these 5 people ONLY join the boss battle. if they lose they lose points
- subs vs plebs in factions, spend points to timeout someone of the other faction. meter on stream that resets every 5 minutes that shows total points spent timing members of the other faction out.
- be part of building a pyramid
  - chaining token-commands? same playsoud/showemote
-  tug of war in the chat? KKona The harder you spam in chat the harder you pull the rope. That could be some kind of subs vs plebs quest. Those who outspam the others win the quest
## Rewards
- Show X emotes on screen?
- X points?

**Comment by KostasPelelis** [comment]
Extra quests:
1) Get global banned
2) Follow/Sub LegendaryLea for a day DansGame
3) Count to X in Y seconds
4) Predict next song (requires a module were chat would have to choose next song between 2 selections)

**Comment by pajlada** [comment]
## Current progress:
![asd](http://i.imgur.com/F9SuzQv.png)

We should save the current quest id in the redis database when it's randomized, and then when the stream stops (i.e. when the quest is stopped) we remove it from the redis database.

**Comment by pajlada** [comment]
For tomorrow:
```
Tokens are going to be saved in redis, without any redis expire time.
Each user will have have a HASH key in the redis database for their tokens for the given streamer.

Key format: {streamer}:{username}:tokens

The HASH key will be filled like this:
{stream_id} = tokens_available

Example:
pajlada:karl_kons:tokens
103 = 1
104 = 5

Karl finished his dailies two streams in a row.
Karl did not spend any of his tokens.

When the next stream begins, we go through all pajlada:*:tokens.
We remove any unused tokens that were from 2 streams ago.
If we notice that a HASH key is empty, remove the entire key.
```

**Comment by pajlada** [comment]
We need to implement commands that cost tokens.
Should these specify that they use tokens in the databasE?
OR should it be handled for each command.
I think it needs to be specified in the database, that way it can be displayed properly on the web interface.

So:
Add a new column to tb_command:
token_price
server default: 0
integer
non nullable

Add checks for tokens and stuff in Command.run

Token-based commands... Should they be specified in separate modules?
Yes.
One module per token command, assuming they're different enough.
So that would mean one module for each of these commands:
!#playsound
!#emote
!#message

**Comment by SnakeTheRipper** [comment]
Global quests. When triggered, everybody in the chat can join them. 

Example : 

* Gachi vs Weeb. Join one side or other by !gachi or !weeb. Whichever side has more users wins after x seconds. Users on the winning side gets some reward.

* Whenever the forsenSS song is played, mods start the quest with !ssquest or something like that. For x seconds the chat needs to reach x messages. If reached, everybody who played gets some reward.

* Subs vs Plebs. Whenever the fuck the plebs song is played, mods start the quest with !subsvsplebs or something like that. For x seconds, both sides have to spam the chat. When time is up, the side with more messages wins and everybody who participated on the winning side gets a reward. (Extra: if subs win, submode for x seconds ?)

**Comment by KARLKONA** [comment]
How about a quest where you need to correctly type the Brain Power lyrics? 

As in:

```
ARE YOU READY
ADRENALINE IS PUMPING
ADRENALINE IS PUMPING
GENERATOR
AUTOMATIC LOVER
ATOMIC
ATOMIC
OVERDRIVE
BLOCKBUSTER
BRAINPOWER
CALL ME LEADER
COCAINE
DON'T YOU TRY IT
DON'T YOU TRY IT
INNOVATOR
KILLER MACHINE
THERE'S NO FATE
TAKE CONTROL
BRAIN POWER
LET THE BASS KICK
O-oooooooooo AAAAE-A-A-I-A-U- JO-oooooooooooo AAE-O-A-A-U-U-A- E-eee-ee-eee AAAAE-A-E-I-E-A-

```

Maybe don't check for upper/lowercase tho. Bot could start checking for followup messages when it reads someone type "ARE YOU READY" and if it's not too taxing for the bot it could send out NotLikeThis for the person when they type wrong.

This would have the plebs engage on their first real adventure and search the interwebs for the correct lyrics and at the same time teach them how to properly sing along to this great song.

**Comment by Kruhlmann** [comment]
For the color-specific emotes maybe this is a start

It grabs an image from a web destination and compares it with predefined RGB color sets. For now it ignores all alpha pixels with a < 200.

_colortest.py_

    from PIL import Image
	import sys
	import os.path
	import io
	try:
		import urllib.request as urllib2
	except ImportError:
		import urllib2

	class Color():
		r = 0
		g = 0
		b = 0
		name = ""

		def __init__(self, r, g, b, name):
			self.r = r
			self.g = g
			self.b = b
			self.name = name

	colors = {
		Color(255,235,205, "beige"),
		Color(0, 126, 0, "green"),
		Color(0, 0, 255, "blue"),
		Color(255, 0, 0, "red"),
		Color(0, 255, 0, "lime"),
		Color(0, 255, 0, "yellow"),
		Color(0,255,255, "cyan"),
		Color(128,128,128, "gray"),
		Color(255,255,255, "white"),
		Color(0,0,0,"black"),
		Color(165,42,42, "brown")
	}

	def analyze(img):
		print("Analysis engaged...")
		# grab width and height
		width, height = img.size

		# make a list of all pixels in the image
		pixels = img.load()
		data = []
		for x in range(width):
			for y in range(height):
				cpixel = pixels[x, y]
				data.append(cpixel)

		r = 0
		g = 0
		b = 0
		counter = 0

		# loop through all pixels
		# if alpha value is greater than 200/255, add it to the average
		# (note: could also use criteria like, if not a black pixel or not a white pixel...)
		for x in range(len(data)):
			try:
				if data[x][3] > 200:
					r+=data[x][0]
					g+=data[x][1]
					b+=data[x][2]
			except:
				try:
					r+=data[x][0]
					g+=data[x][1]
					b+=data[x][2]
				except:
					print("RGB error on index " + str(x) + " : ")
					print(*data, sep='\n')

			counter+=1

		# compute average RGB values
		rAvg = r/counter
		gAvg = g/counter
		bAvg = b/counter

		print("Average rgb of image R:" + str(rAvg) + " G:" + str(gAvg) + " B:" + str(bAvg))
		return (rAvg, gAvg, bAvg)

	if __name__ == "__main__":
		print("Initializing...")
		file = urllib2.urlopen("https://static-cdn.jtvnw.net/emoticons/v1/171/1.0")
		img = Image.open(io.BytesIO(file.read()))
		r, g, b = analyze(img)
		closest_match = 255
		closest_color = "No match"
		for color in colors:
			total = 0
			total += abs(color.r - r)
			total += abs(color.g - g)
			total += abs(color.b - b)
			total = total / 3
			print("Result for color: " + color.name + " - " + str(total))
			if total < closest_match:
				closest_match = total
				closest_color = color.name
		print("Result: " + str(closest_match) + " " + closest_color)

**Comment by Nacht123** [comment]
A lot of quests here are **impossible** to finish or to made them work were well.

Lose points in duels, roulette, ... would be a funny quest.
like @KARLKONA said on [reddit](https://www.reddit.com/r/forsen/comments/4h6j9h/the_spam_quest_is_one_of_the_worst_thing_that/d2ocmeh)

**Comment by alazymeme** [comment]
@pajlada is this still active, or have you implemented everything you wanted to?
