### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by jeovanny315** [pajbot/pajbot#1185]
![image](https://user-images.githubusercontent.com/79304571/110237803-d4a99100-7ef2-11eb-8cbe-fa66ba6d5264.png)

**Comment by RAnders00** [comment]
check if the postgres server is running: `sudo -u postgres pg_lsclusters`

**Comment by RAnders00** [comment]
I assume since you haven't gotten back on this ticket this is solved? If not feel free to respond and I can reopen the ticket.
