### ISSUE TITLE
Idea for fixing multiple moderation modules overriding each others timeout

### ISSUE THREAD

**Issue by RAnders00** [pajbot/pajbot#1209]
I want to start this more as a discussion and to write down a technical idea of how we can band-aid-fix the problem that if a message is found to be bad by more than one moderation module it will apply the first module's action and not run the other modules after that. E.g. you can bypass the massping timeout by also including a banned phrase in your message.

Relevant issue: https://github.com/pajbot/pajbot/issues/1117
![image](https://user-images.githubusercontent.com/1629196/113521614-dd958d00-959a-11eb-9b93-67f7be542076.png) (braille is banned via banphrase, not ascii module in nymn's chat)

My idea was:
- Add a flag to `HandlerManager.add_handler` that is called `run_if_propagation_stopped` (or something like that). Current behaviour is to run handlers in the order they were added and to abort if one of them returns `False`. I would change it to not abort immediately, instead continue iterating handlers and only run those with `run_if_propagation_stopped=True`. Then all moderation modules would register their event handlers with this flag set to `True`.
- Add a **thread-local** state variable to `Bot` that makes `bot.timeout`, `bot.ban`, etc. behave differently if the bot is in the middle of processing a message (e.g. during [`on_pubmsg`](https://github.com/pajbot/pajbot/blob/5be9b351fcc0b3c7fdc85cf06160c43812f8525e/pajbot/bot.py#L788)).
  Instead of sending the timeout/ban command directly to the wire, the thread-local variable is updated when a module calls `bot.ban` or `bot.timeout` (for example choosing the higher of two timeouts, or a ban over a timeout). When the `on_pubmsg` handling code ends (i.e. all event handlers have been called) the action is "executed", aka sent to the wire.

We will probably need to inspect usages of `timeout` and `ban` to see whether this behaviour is not desireable for some modules, maybe we will need to add an override flag to timeout/ban methods (`immediate=True` or something like that).

Will probably affect `bot.timeout`, `bot.ban`, `bot.untimeout`, `bot.unban`.

**Comment by pajlada** [comment]
This seems like a reasonable way to solve this.
