### ISSUE TITLE
Add an option to banphrase emotes

### ISSUE THREAD

**Issue by badoge** [pajbot/pajbot#1214]
If you currently banphrase an emote, anyone that types it will get timed out, even if they don't have that emote, what would be better is to check if the irc message contains the emote.
So it would be a new banphrase operator that matches the banned phrase with the emotes parameter in the PRIVMSG

something like this: !add banphrase (forsenE|forsenC) --operator emote
it would be nice if it supported regex also so we can ban multiple emotes with a single phrase or a whole emote set by banning the prefix.

**Comment by Ieppeg** [comment]
NOIDONTTHINKSO

**Comment by ALazyMeme** [comment]
> !add banphrase (forsenE|forsenC) --operator emote

So would the operator also have to support regex? Because that seems to be crossing lines with the regex operator.

**Comment by ALazyMeme** [comment]
![image](https://user-images.githubusercontent.com/12804673/126886049-f7413705-0bad-4cf5-8be7-abd5d6740319.png)
