### ISSUE TITLE
Unhandled tweepy exceptions

### ISSUE THREAD

**Issue by ALazyMeme** [pajbot/pajbot#1216]
In this case, the twitter user is suspended: https://i.alazymeme.com/DisturbedLinearFile.txt 
In this case, the twitter user does not exist: https://i.alazymeme.com/ExuberantRightFile.txt

When you try to follow a user that does not exist, you get no whisper and errors in the logs: https://i.alazymeme.com/ExuberantRightFile.txt
Same for a suspended user: https://i.alazymeme.com/FlyingSubjectiveFile.txt

**Comment by pajlada** [comment]
These errors are outdated (i.e. these exceptions aren't used anymore), recreate if we find new exceptions (after #1589)
