### ISSUE TITLE
Add support for 7TV

### ISSUE THREAD

**Issue by TroyDota** [pajbot/pajbot#1256]
As the title suggests.
https://7tv.app
:)

Also the GQL implantation allows for querying of BTTV and FFZ emotes bundled into the response so you could remove the support for loading them by implementing the 7tv extension. 
If this is something you would consider adding i dont mind doing the PR.

**Comment by RAnders00** [comment]
We should add 7TV support, but i‘d prefer loading ffz and bttv from those sources directly, otherwise all emote providers would be „down“ when just 7TV is down, and 7TV being relatively new doesnt exactly allow us to know of the service‘s stability.

**Comment by killertofus** [comment]
In my opinion, The extension is "too niche" to spent time on implementing and maintaining it over an indefinite amount of time.

Also,adding support for one niche extension makes it harder to argue against supporting other niche extensions. Now, if the 7tv gained popularity on the levels of BTTV and FFZ, it would make sense to reconsider this at a later point in time.

**Comment by pajlada** [comment]
Closed by #1260
