### ISSUE TITLE
Remove hardcoded timeout limits from moderation modules 

### ISSUE THREAD

**Issue by badoge** [pajbot/pajbot#1332]
Some modules have hardcoded limits for the timeout length. They are not consistent also, some of them start at 3 or 30 and max out at 300 or 3600.
Point commands also have some hardcoded limits on price.

**Comment by pajlada** [comment]
Could you create new issues on a per module basis?

For example "change limits of raffle module from 3000 to 50000" or whatever - that let's people bite off each issue one at a time.

Thank you!

**Comment by badoge** [comment]
I think i'll just make pull requests for each module myself since it seems that I only need to edit 1 line.

**Comment by ALazyMeme** [comment]
This one's already done isn't it?

**Comment by badoge** [comment]
> This one's already done isn't it?

yes
