### ISSUE TITLE
Blackjack Game

### ISSUE THREAD

**Issue by kpelelis** [pajbot/pajbot#137]
!blackjack { points }  Initialize a simplified blackjack game session. The bot deals 2 cards to the player ,one hidden and one public for itself.
(Main Functionality) The user then can either !hit or !stop. The rules after that are the same except the split feature which would require a shiton of work to do.

If the user wins he gets x2 his points. And if he looses the bot gets the pot. This can be a multi user feature as well. Example:
(moderator command) !startblackjack { pot } { user_limit } Initialize a blackjack session which require { pot } points to join and up to { user_limit } players can join for the next 40 seconds. After this time interval the dealer deals one card to each player (e.g. with a private message) and keeps doing the main functionality for each player in a cyclic way.

The idea of card games for chat is generally a feasible idea in my opinion and should be fun enough

**Comment by RAnders00** [comment]
Due to pajbot [being moved into maintenance mode](https://github.com/pajbot/pajbot/blob/master/README.md) I'm closing this feature request.
