### ISSUE TITLE
!add timer command

### ISSUE THREAD

**Issue by ALazyMeme** [pajbot/pajbot#1376]
!add timer <name> <response>
Parameters:
--online (to override the online time, in minutes - 10 minutes if not specified)
--offline (to override the offline time, in minutes - 30 minutes if not specified)
--action <me/say> (to override the action - say if not specified)

**Comment by RAnders00** [comment]
Do you want to own this feature @ALazyMeme? Otherwise I want to close this due to the pajbot maintenance mode, since it's purely a feature request.
