### ISSUE TITLE
Emote Counter on stream

### ISSUE THREAD

**Issue by pajlada** [pajbot/pajbot#139]
Mods somehow start an emote counter.
two emotes only?
!emotecounter start <3 DansGame
will count how many <3 compared to DansGame's are on stream and display them in the center left position.
with a bar or something?

**Comment by DatGuy1** [comment]
No bar, but working example exists: https://pastebin.com/cQbH8Gqm
How it looks: https://i.nuuls.com/JjlX0.png

**Comment by RAnders00** [comment]
Due to pajbot [being moved into maintenance mode](https://github.com/pajbot/pajbot/blob/master/README.md) I'm closing this feature request.
