### ISSUE TITLE
!bttvemotes and the other emotes command no longer work

### ISSUE THREAD

**Issue by MagicHack** [pajbot/pajbot#1437]
Every !xxemotes command are broken (probably from commit  91b2b4d3d25763b3e244bc80fe0d7f430bb1f894 ). 
https://github.com/pajbot/pajbot/blob/master/pajbot/modules/basic/emotes.py#L182 calls print_emotes without the new event parameter.

`File ".../pajbot/pajbot/modules/basic/emotes.py", line 182, in do_print
self.print_emotes(source, manager)
TypeError: print_emotes() missing 1 required positional argument: 'manager'`

**Comment by ALazyMeme** [comment]
I'll fix it when I get home
