### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [pajbot/pajbot#1451]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by pajlada** [comment]
I'm in the process of creating the `SECURITY.md` file now in #1452

The best way to reach out to me is through my email pajbot@pajlada.com if it's a sensitive matter - please reach out!

**Comment by ALazyMeme** [comment]
Fixed by https://github.com/pajbot/pajbot/pull/1452
