### ISSUE TITLE
Unable to use any commands on xQc's channel.

### ISSUE THREAD

**Issue by Elliptah** [pajbot/pajbot#1459]
On my previous account there were no problems but with my new Twitch account  I'm unable to use the !roulette or anything.

**Comment by ALazyMeme** [comment]
Which other commands? If !roulette is the only one you can't use, that'd be fairly normal.

**Comment by Elliptah** [comment]
> Which other commands? If !roulette is the only one you can't use, that'd be fairly normal.

I can't use any of them. I should of stated that, my bad

**Comment by ALazyMeme** [comment]
> > Which other commands? If !roulette is the only one you can't use, that'd be fairly normal.
> 
> I can't use any of them. I should of stated that, my bad

According to logs, you haven't even attempted to use any commands. Which makes me think that you're trying to use them while he's live - which his chat is generally too fast to get any messages to actually send.

**Comment by Elliptah** [comment]
> > > Which other commands? If !roulette is the only one you can't use, that'd be fairly normal.
> > 
> > 
> > I can't use any of them. I should of stated that, my bad
> 
> According to logs, you haven't even attempted to use any commands. Which makes me think that you're trying to use them while he's live - which his chat is generally too fast to get any messages to actually send.

I been in his offline chat trying to gamba but nothing goes through to my logs

**Comment by ALazyMeme** [comment]
> > > > Which other commands? If !roulette is the only one you can't use, that'd be fairly normal.
> > > 
> > > 
> > > I can't use any of them. I should of stated that, my bad
> > 
> > 
> > According to logs, you haven't even attempted to use any commands. Which makes me think that you're trying to use them while he's live - which his chat is generally too fast to get any messages to actually send.
> 
> I been in his offline chat trying to gamba but nothing goes through to my logs

If nothing's going through to your logs, it's got nothing to do with pajbot. It sounds like you might've been potentially banned on another account.

Once your messages go through and you can confirm you still aren't getting a response from pajbot, please ping me and I'll reopen the issue.

**Comment by Elliptah** [comment]
> > > > > Which other commands? If !roulette is the only one you can't use, that'd be fairly normal.
> > > > 
> > > > 
> > > > I can't use any of them. I should of stated that, my bad
> > > 
> > > 
> > > According to logs, you haven't even attempted to use any commands. Which makes me think that you're trying to use them while he's live - which his chat is generally too fast to get any messages to actually send.
> > 
> > 
> > I been in his offline chat trying to gamba but nothing goes through to my logs
> 
> If nothing's going through to your logs, it's got nothing to do with pajbot. It sounds like you might've been potentially banned on another account.
> 
> Once your messages go through and you can confirm you still aren't getting a response from pajbot, please ping me and I'll reopen the issue.

I didn't know if I've been previously banned it'd effect an alt, also I tried some ! commands but noting

**Comment by ALazyMeme** [comment]
Yes, it would affect an alt. It usually shadowbans you and stops you from talking. Regardless, as per your logs, you haven't typed anything in chat:

![image](https://user-images.githubusercontent.com/12804673/133400667-d4b287eb-a643-49ee-83a3-6526b87da4ff.png)

**Comment by Elliptah** [comment]
> Yes, it would affect an alt. It usually shadowbans you and stops you from talking. Regardless, as per your logs, you haven't typed anything in chat:
> 
> ![image](https://user-images.githubusercontent.com/12804673/133400667-d4b287eb-a643-49ee-83a3-6526b87da4ff.png)

makes sense, thx for explaining it
