### ISSUE TITLE
Disable status check messages in Discord webhook

### ISSUE THREAD

**Issue by RAnders00** [pajbot/pajbot#1490]
@pajlada In your own Discord community server I would like to be able to use the #github channel. Unfortunately it‘s being flooded by CI run success/failure messages burying the useful information.

Can you as the repository/organization admin change that?

**Comment by ALazyMeme** [comment]
github-ci channel when

**Comment by pajlada** [comment]
I've gone ahead and disabled the "Deployment statutes" checkbox for the organization CI webhook - please re-open the issue if this doesn't solve the spam.

**Comment by pajlada** [comment]
*SHOULD* be fixed now - I disabled "Check runs" too

**Comment by RAnders00** [comment]
Looks like it‘s fixed - Thank you!
