### ISSUE TITLE
Add a way to disable/enable commands in chat

### ISSUE THREAD

**Issue by zneix** [pajbot/pajbot#1499]
I'd like to be able to disable a command from chat, without need to open dashboard.
The proposal is to add flags to `!edit command`, like `--disable` (and/or have `--disabled` as an alias).

side note: Ideally for feature parity, flag for enabling command (`--enable`, `--enabled`) would work as well, however due to #838 it wouldn't be very useful, but good to have it regardless of that.

**Comment by sirinoks** [comment]
I'll work on this

**Comment by zneix** [comment]
Just noticed that this was already implemented in #1502, just forgot to close this issue. Sorry for causing such confusion by leaving this issue open.
