### ISSUE TITLE
Disconnected from IRC (Connection reset by peer)

### ISSUE THREAD

**Issue by Mateyoo** [pajbot/pajbot#1509]
When I start the bot, the web works just fine, and after a couple seconds I get these messages:

  for deck in db_session.query(Deck).order_by(Deck.last_used.desc()):

 /opt/pajbot/pajbot/models/user.py:340: SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` flag is not set to True.  Set this flag to True if this type object's state is safe to use in a cache key, or False to disable this warning.

 db_session.query(User).filter_by(login=login).order_by(User.login_last_updated.desc()).one_or_none()

 [ERROR  ] Disconnected from IRC (Connection reset by peer)

Any ideas?

**Comment by pajlada** [comment]
It might be related to the VPS you're using, in case they block certain ports from being used. I know we've ran into similar issues in the Chatterino repo, but it's less common for VPS's to do that sort of port blocking.

**Comment by Mateyoo** [comment]
What ports do I need to allow, if this is the issue?

**Comment by ALazyMeme** [comment]
Where you able to solve the issue?

**Comment by Mateyoo** [comment]
I didn't try it since then, but if the error will be the same, I'll open an issue ticket again.
