### ISSUE TITLE
Module to make links in donations safer?

### ISSUE THREAD

**Issue by pajlada** [pajbot/pajbot#151]
Module that parses incoming donations
Imgur has an API that can tell you if it's animated or not. API: https://api.imgur.com/endpoints/image
If it's animated, should we download the image and explode it?
Maybe there's a third party site that can do it for us?
Or - We set up a submodule, which lets moderators see incoming donations and links, and lets them verify links.
Forsen will see links as unverified (i.e. dangerous to click) until a moderator says it's ok

**Comment by pajlada** [comment]
If a link is detected as a gif, we could simply change the link into the thumbnail link instead. This will make it static.

**Comment by idkm23** [comment]
How do you feel about checking if the end of an animation is a static image? You could do some kind of checksum to see if anything changed in the last portion of frames and if this is detected you could flag that image. I know this wouldn't work for inappropriate **animations** at the end of a gif, but as of right now a lot of these animations end with an image of something... shocking

**Comment by pajlada** [comment]
@idkm23 One issue with doing that is that few traps don't leave the static image at the end, instead they just reloop the original gif. So it would only catch like 50% of the shit we want to catch?
There are three options in the end I think, that are viable.
In order of what I think is best:
1. Manual confirmation
2. Explode GIFs
3. Filter out GIFs

**Comment by alazymeme** [comment]
@pajlada Can probably also be removed

**Comment by pajlada** [comment]
Not relevant for pajbot1 anymore as we're out of the "donation api" business
