### ISSUE TITLE
Default moderation commands are no longer listed on webui

### ISSUE THREAD

**Issue by Felanbird** [pajbot/pajbot#1521]
current master:
![image](https://user-images.githubusercontent.com/41973452/137012655-6e30ff79-d1b7-461a-8313-a06877de52c4.png)

forked bot still running on 1.54:
![image](https://user-images.githubusercontent.com/41973452/137012820-899a561b-2bab-4881-a346-7c76f3706394.png)

**Comment by pajlada** [comment]
I was wrong - turns out it had to do with internal commands, not just multiactions

**Comment by ALazyMeme** [comment]
Fixed in https://github.com/pajbot/pajbot/pull/1538
