### ISSUE TITLE
Modify modules from chat

### ISSUE THREAD

**Issue by pajlada** [pajbot/pajbot#153]
`!module enable MODULE_NAME`
`!module disable MODULE_NAME`
`!module list` - list all modules
`!module list enabled` - list all enabled modules
`!module list disabled` - list all disabled modules

**Comment by Nacht123** [comment]
maybe a bit **outdated**,
since there are to many modules now and `!module list` would spam you.

**Comment by pajlada** [comment]
Agreed. If this is to be implemented it should only have  enable and disable
