### ISSUE TITLE
My Issues

### ISSUE THREAD

**Issue by jkalter24** [pajbot/pajbot#1531]
Hi so I have heard about pajbot and I have been trying to set it up I have a few questions.

1. In the install doc should I replace the streamer_name with my streamer name or is that used for something
2. If I'm using a subdomain when it says Streamer_Name.your-domain.com should I still put my subdomain for example bot or use my stream name
3. I am trying to set up pajbot with a .tk domain. it was registered through Freenom and I am using CloudFlare as NameServers. When I try and do the nginx and the cloudflare letsencrypt it says you can't use any free domains. How can I still use my domain

**Comment by Felanbird** [comment]
1. `streamer_name` is replaced with the name of the stream you are setting the bot up for, for example `xqcow`
2. `streamer_name.your-domain.com` should look something like this, example `NymN` - [nymn.pajbot.com](https://nymn.pajbot.com/)
But that's only a suggestion, see [forsen.tv](https://forsen.tv/)
3. I can't personally help you with that.

**Comment by jkalter24** [comment]
I fixed the domain issue now when doing nginx I get this erro
![9360391c826ce1918a82d6c9fd48c4d0](https://user-images.githubusercontent.com/70232140/137572945-54bdca28-0386-46bd-a589-84cc38c5d970.png)
r

**Comment by pajlada** [comment]
@jkalter24 Could you show your nginx config around line 21? specifically the `/etc/nginx/sites-enabled/bot.josephstechworld.com.conf`

**Comment by jkalter24** [comment]
> @jkalter24 Could you show your nginx config around line 21? specifically the `/etc/nginx/sites-enabled/bot.josephstechworld.com.conf`

![image](https://user-images.githubusercontent.com/70232140/137593859-b1b3d858-48fe-47ac-b067-7ad82d685805.png)

**Comment by pajlada** [comment]
@jkalter24 Could you post the part relating to `joseph-botsite`?
Should look something like
```
upstream pajlada-web {
    server unix:///var/run/pajbot/pajlada-web.sock;
}
```

**Comment by RAnders00** [comment]
In your config file, at lines 1 and 5, you should replace `streamer_name` with `joseph`

**Comment by RAnders00** [comment]
If you have any further questions or issues feel free to comment here again, and we can re-open the issue. For now though I‘ll close this since you haven‘t gotten back for quite a while. Thank you!

**Comment by jkalter24** [comment]
Ok, I started over and I have a new domain as well. I did everything and the ngix check. I also did the Cloudflare part. Any time I try and go in the URL it's not found. It also forced www.

**Comment by RAnders00** [comment]
What is your domain name, so we can perhaps investigate a bit?

**Comment by jkalter24** [comment]
> What is your domain name, so we can perhaps investigate a bit?

thecyberzone.online
