### ISSUE TITLE
new sounds for !#playsound

### ISSUE THREAD

**Issue by pajlada** [pajbot/pajbot#155]
Got an idea for a sound?

Cut the sound to an mp3 file, upload it to clyp.it or another file upload site and post it as a comment here

**Comment by Nacht123** [comment]
nyanpass for swiftapples
http://nyanpass.com/nyanpass.mp3

if you could upload this :+1:

**Comment by pajlada** [comment]
@Nacht123 https://pajlada.se/files/clr/nyanpass.mp3

**Comment by swiftapples** [comment]
Tuturu sound
http://www.myinstants.com/media/sounds/tutturuu.mp3

Goes well with pajaHey .

**Comment by swiftapples** [comment]
Ayaya sound
https://drive.google.com/file/d/0BxHQkfkGW9Q0VjJNbFY2NWFPMFE/view?usp=sharing

It's safe. Keepo

**Comment by CommName** [comment]
Where's my auctioneer?
https://drive.google.com/file/d/0B9VTteZoIes1VWloOGJod2xjNDg/view?usp=sharing

**Comment by CommName** [comment]
do it dad ! 
https://drive.google.com/file/d/0B9VTteZoIes1M1V4R0d5NnJXZnM/view
me go face
https://drive.google.com/file/d/0B9VTteZoIes1cVRvaUwyLS10OWc/view

**Comment by swiftapples** [comment]
POI 
http://anohito.tw/poi/mp3/POI_08.mp3

OH
http://www.myinstants.com/media/sounds/oh_7.mp3

**Comment by farbrormelker97** [comment]
https://drive.google.com/folderview?id=0B4Pq8HInf39cMmRxSUdKUlN4dG8&usp=sharing 
some gachi sounds maybe one is earrape idno nymnSmug

**Comment by Huwodro** [comment]
Jesse, we have to cook: https://clyp.it/riivwlrr
Dayum dayum dayum: https://clyp.it/acgnv1ld
Shakalakalaka in you: https://clyp.it/svngl1uk

**Comment by dischordo** [comment]
https://drive.google.com/folderview?id=0B1HLjQRzRcE1SHFYMzdpX0pUUzA&usp=sharing

**Comment by pajlada** [comment]
finished up to here
-------------------------------------------------------------------------------------------------------------------------------------

**Comment by Shenkilol** [comment]
http://puu.sh/nhVVZ/23ada945c8.mp3

**Comment by gnig17** [comment]
**Surpise MotherFucker** http://www.myinstants.com/media/sounds/surprise-motherfucker.mp3
**Bitch (Jesse)** http://www.myinstants.com/media/sounds/sequence-01_1_3.mp3
**My name is Jeff** http://www.myinstants.com/media/sounds/ringtone_20.mp3
**Shieeeet** http://www.myinstants.com/media/sounds/sheeeit.mp3
**Smoke weed everyday** http://www.myinstants.com/media/sounds/snoop-dogg-smoke-weed-everyday.mp3
**Facebook MSG** http://www.myinstants.com/media/sounds/facebook-chat-sound-hd.mp3

Right click and save as to download MP3

**Comment by T-Brawl** [comment]
I can make the MP3s later if needed (at work right now Kappa) but here are some suggestions : 
- Damn son, where'd you find this?
- Oh baby a triple!
- Are you scared now, bitch?
- Mistake! (Jaraxxus, old Forsen sub notification sound)
- Uhhh
- Steam message sound

**Comment by Shenkilol** [comment]
http://puu.sh/nxER7/2df0cce75b.mp3 WutFace

**Comment by NotDefendotKappa** [comment]
Keepo
- http://www.myinstants.com/instant/hoshizora-rin-nyan-nyan-nyan/  cirNilla nyan cirCola
- http://puu.sh/nzn82/ac6832b831.mp3 uguu
- http://puu.sh/nzw4m/9e2fa62c5b.mp3 omurice desu !!!

**Comment by kotverzehrer** [comment]
https://www.youtube.com/watch?v=eu3O_FBilko word around the office

**Comment by RandomRoleplayer** [comment]
"Buddy I Think you got the wrong door, the leather club is two block down" gachiGASM
https://drive.google.com/file/d/0B6H7L0Osk9ERbFpoUjZXcVB0VHM/view?usp=sharing

**Comment by kotverzehrer** [comment]
slaves get your ass back here...could be hilarious if hes chasing people in the culling
http://soundboard.ass-we-can.com/static/music/VanD/Slaves%20get%20your%20ass%20back%20here.mp3

**Comment by LavenderWow** [comment]
Behind You 

https://drive.google.com/file/d/0B8ZsxEmEGwhiU3BGRWtnV0o5dHM/view?usp=sharing

I see You 1

https://drive.google.com/file/d/0B8ZsxEmEGwhidHJweXZuN0pzRWc/view?usp=sharing

I see You 2

https://drive.google.com/file/d/0B8ZsxEmEGwhid0xCWmpOeS1fWlU/view?usp=sharing

**Comment by lde94** [comment]
OH HO HO HO GANGING UP
https://clyp.it/osndmok5

I know dad needs this.

**Comment by pajlada** [comment]
## DOWNLOADED UP TO HERE

**Comment by LavenderWow** [comment]
Oops, sorry if this is a bit spammy, forgot this one.

**Yaranaika?**

https://drive.google.com/file/d/0B8ZsxEmEGwhiZFRrQjFBMVZSM3M/view?usp=sharing

**Comment by Sephironx** [comment]
its not a lie: https://clyp.it/bka5dgib

I'm not fucking lying: https://clyp.it/sxdwikv0

Lost in the sauce: https://clyp.it/me0yvrl2

Team time with Byrone: https://clyp.it/vak1flhz

GAMBAA: https://clyp.it/1sylngsz

**Comment by illuminarty** [comment]
Here the laugh sample as promised: https://clyp.it/yfsakcq4 AlkXD

**Comment by pajlada** [comment]
some random sample from huwarf https://clyp.it/5vgpusjk

**Comment by pajlada** [comment]
https://drive.google.com/file/d/0B33lZ0_jut46eEVVUzZVVlZVQVE/view?usp=sharing
reynad sample

**Comment by Tehurnhype** [comment]
(puke) https://clyp.it/rb2ovz4o

**Comment by NotDefendotKappa** [comment]
http://puu.sh/nEiRy/e09c6e0324.mp3   Nico Nico Nii~ 
http://puu.sh/nEiGh/507de4b2b0.mp3   Its a prank bro

**Comment by str4t0s** [comment]
https://aww.moe/xly7on.mp3 - forsens famous sound of disgust (from http://oddshot.tv/shot/forsenlol-20151024184418207)

**Comment by plziom** [comment]
https://drive.google.com/file/d/0B9fgURKNS0q1TVh1LWFXZHlycnM/view?usp=sharing best sample ever

**Comment by str4t0s** [comment]
https://aww.moe/s8wozu.mp3 ear licking asmr

**Comment by Testman123** [comment]
3/15/2016, 9:33:52 PM
rIoTGEms: https://clyp.it/jh40q3m0 do I need to sign up and link it on github?

**Comment by SevenFiveSeven** [comment]
[RAVIOLI RAVIOLI GIVE ME THE FORMUOLI](https://drive.google.com/file/d/0BzAjnpxhQU4sZ1QtX1RxUDhjX00/view?usp=sharing)

**Comment by SevenFiveSeven** [comment]
[RAVIOLI RAVIOLI GIVE ME THE FORMUOLI ](https://drive.google.com/file/d/0BzAjnpxhQU4sZ1QtX1RxUDhjX00/view)

**Comment by Nacht123** [comment]
from @Hejnusskolarbete

**You think you can beat me 123?** closes #243 
http://puu.sh/nK3pF/202367c367.mp3
<hr/>
maybe cut the last part
<br/><br/>
**AHHHHHHHHHHHHHHHHHHHHHHHH** closes #244 
http://puu.sh/nK4hQ/619e109e08.mp3
<hr/>
There is already an **!#playsound aaaah**, not sure but i think this ahhh is to long/loud

**Comment by Kappa1337** [comment]
https://www.youtube.com/watch?v=I5bfCc_8p90
Black priest

**Comment by Billywob** [comment]
Dank fucking sound:
[I wanna fuck you in the ass](https://clyp.it/pvk2c01h)

**Comment by pajlada** [comment]
@Kappa1337 can you turn the relevant sound from the YouTube clip into an mp3 file?

**Comment by Kappa1337** [comment]
@pajlada i hope dropbox is ok for you. https://www.dropbox.com/s/x1vk7l2qsminxzi/Fucking%20White%20People.mp3?dl=0

Btw i'm JeSuisElle

**Comment by dextermb** [comment]
@Kappa1337 :fire: You like to watch the world burn, don't you :fire: dropbox :fire_engine:

**Comment by NotDefendotKappa** [comment]
Guys stop writing to each other here i always get an email when someone comments Kappa

**Comment by Kappa1337** [comment]
@NotDefendotKappa im sorry. Take another mail Keepo

**Comment by Shenkilol** [comment]
http://puu.sh/nPEKp/a99258eb58.mp3 <- 4Head Not my best sound, sorry broskies I'm out of idea pajaW

**Comment by dersand** [comment]
http://www81.zippyshare.com/v/IvJzP8v7/file.html

CS:GO footsteps for left ear. More?

**Comment by Shenkilol** [comment]
http://puu.sh/o1irl/742fd68cc7.mp3 <- TriHard
http://puu.sh/o1itc/47c6b14301.mp3 <- Sensual whisper / Doki doki / Might need a volume upgrade pajaW

**Comment by thoriume** [comment]
https://clyp.it/021njnvz <- No god please no. No. NOOOOOO. From the Office when there is too much brain damage..i mean power.

**Comment by CodeBowser** [comment]
https://clyp.it/4d4ycw3c

kripp's intro

**Comment by CodeBowser** [comment]
https://clyp.it/gvtvvyou

Nozdormu's "Just in time" to troll forsen, also usable if forsen went afk and still finished his turn after the rope came.

**Comment by CodeBowser** [comment]
https://clyp.it/oo5qccoa

athene's catch phrase

**Comment by CodeBowser** [comment]
https://clyp.it/hsprrwgo

ＨＩ，  Ｉ  ＡＭ  ＥＬＥＣＴＲＩＣ  ＢＯＤＹＢＵＩＬＤＥＲ  ＦＲＯＭ  ＲＵＳＳＩＡ﻿

**Comment by Ampzyh** [comment]
http://soundboard.ass-we-can.com/static/music/Unripped/Without%20further%20interruption.mp3

**Comment by Shenkilol** [comment]
http://puu.sh/oa417/c41b4b9880.mp3 trump LUL

**Comment by otul** [comment]
I'll leave you here a few missing gachi sounds for the playsound command. You can add them if you want :)

https://mega.nz/#!58V2USqC!A5J8LUTCGQR8JSc1-yxoTkHsLJXR-prnTbxJmg4lC8w

**Comment by NotDefendotKappa** [comment]
https://www.myinstants.com/instant/oh-god-i-love-memes/ FeelsGoodMan

**Comment by NotDefendotKappa** [comment]
I couldnt leave without weeb samples Keepo
http://puu.sh/oeXSv/b48166b8ae.mp3 rena laugh
http://puu.sh/oeXRO/538dcd9ed7.mp3 weeb cry

**Comment by NotDefendotKappa** [comment]
Another one for the email list PogChamp :
Couldnt decide which one to choose so just pick one Keepo
1. http://puu.sh/ol6Mz/4ac64b783f.mp3 Do it or 2. http://puu.sh/ol6Ma/1c3a72e5e0.mp3 Just do it

**Comment by dischordo** [comment]
https://drive.google.com/folderview?id=0B-QopgNi8sA1VzNMQmJrdE9DcFk&usp=sharing 
The hefftobemad is so good nowadays

**Comment by Nacht123** [comment]
sounds with low uses should be removed.

**Comment by NotDefendotKappa** [comment]
RIP Nightnacht and sound samples FeelsBadMan

**Comment by Blainezab** [comment]
https://clyp.it/tzmlm4gb pajaGASM

**Comment by farbrormelker97** [comment]
https://clyp.it/u0chbofe pain1 
https://clyp.it/23hv2kih get on your hands and knees and ill show ya 
https://clyp.it/rpwviscm Pull up our pants 
https://clyp.it/fsdhr0tw No spammerino in the chatterino

**Comment by pajlada** [comment]
MOVE YOUR TONGUE AROUND MORE gachiBASS

https://clyp.it/m5mjwqsn#

**Comment by pajlada** [comment]
# downloaded until here

**Comment by Blainezab** [comment]
https://i.nuuls.com/JknNF.mp3 FeelsGoodMan from the FeelsDecentMan song on youtube
