### ISSUE TITLE
Auto accept duel under a certain amount

### ISSUE THREAD

**Issue by th0mk** [pajbot/pajbot#158]
Since its sometimes hard to keep track of duels, maybe it would be a good idea to add some sort of auto accept. That should include some sort of limit (so people don't abuse it on someone).
Example: 
!autoduelon 100
!autodueloff

It could maybe also be possible to whitelist or blacklist certain people for the auto accept. This might be a bit too complicated together with the limit though.

**Comment by pajlada** [comment]
this would be pretty dank, but i'm setting it as low priority, as the amount of work required to make this work well is really high.

**Comment by Nacht123** [comment]
This could be easy done with two new information about the user in mysql or redis.

- **duel_auto** - Boolean True / False
- **duel_points** - Int - Limit for autoduels

If must check if **duel_auto** is **1** and will accept the duel for the user.

But yeah this is maybe just **useless data for mysql and redis** that you don't really need.
