### ISSUE TITLE
Playsounds takes points, regardless if the sound plays or not

### ISSUE THREAD

**Issue by ALazyMeme** [pajbot/pajbot#1652]
```
22:33 🥧🤖: @ALazyMeme ALazyMeme has 816 points. For more information about points, see paj.pajlada.se/points
22:33 ALazyMeme: !#playsound idle
22:33 🥧🤖: ALazyMeme has 616 points
```
This was the playsound, which doesn't exist: https://i.nuuls.com/zf3FO.mp3
As seen above, the bot still takes my points.

**Comment by pajlada** [comment]
Bot owner error, this realistically shouldn't happen if the playsounds are configured properly. I don't think it's the bots responsibility to validate that the link is valid, that it returns a 200, or that it plays in a CLR.
