### ISSUE TITLE
iso format date and time doesn't work with the datetimefromisoformat parameter

### ISSUE THREAD

**Issue by ALazyMeme** [pajbot/pajbot#1667]
It only appears to work with dates and screws up when you input a time. It was copied from the variable page example: https://docs.python.org/3/library/datetime.html#datetime.datetime.fromisoformat

Refer below:

![image](https://user-images.githubusercontent.com/12804673/147716031-b317f341-e3ce-477e-a5b2-abf528804101.png)
![image](https://user-images.githubusercontent.com/12804673/147716054-26b2c4aa-6eba-4022-84e4-6250ac0e67e9.png)

**Comment by RAnders00** [comment]
This is probably because yet another character has to be added to the parsing regex

**Comment by pajlada** [comment]
got solution for this in local commits, have solved the urgent usecase and will push proper solution on saturday
