### ISSUE TITLE
Social Media handles (for the front page) don't save.

### ISSUE THREAD

**Issue by mmattbtw** [pajbot/pajbot#1677]
I've been getting this error for a while now, not sure why :/

![z4Ixe2PxxP](https://user-images.githubusercontent.com/30363562/148486409-2b7de61f-0854-4028-b7d1-4bec81287f76.gif)
![firefox_pvmIERChvo](https://user-images.githubusercontent.com/30363562/148486549-e76be7da-f37c-473d-8e86-0e7235304be2.gif)

**Comment by ALazyMeme** [comment]
Can reproduce

**Comment by pajlada** [comment]
Confirmed, has to do with the CSRF token
