### ISSUE TITLE
CLR Overlay not showing emote combos or showemote

### ISSUE THREAD

**Issue by sh6rpshot** [pajbot/pajbot#1724]
Whenever I enter the !#showemote command or do an emote combo in twitch chat, nothing appears on the CLR overlay (https://sh6rpshot.com/clr/overlay/12345). 

Something to note: when I try and enable the clroverlay-group module by typing "!module enable clroverlay-group" the bot responds: Unable to enable module clroverlay-group.

I know that the other modules (showemote, emotecombo, emotesonscreen) are enabled and that the commands themselves work, because whenever I do !#showemote, it takes away my points. Hopefully someone can help me out :)

**Comment by ALazyMeme** [comment]
1. clroverlay-group isn't a module, if you want to enable a specific module then you must use that specific module's ID
2. The CLR isn't working, check your configuration first:

![image](https://user-images.githubusercontent.com/12804673/151683750-34cc760d-8e4a-46ec-9fda-4d98bd705da5.png)

**Comment by sh6rpshot** [comment]
the config file seems like it's correct but it's still producing an error, can the bot be configured without having a subdomain set up?

**Comment by ALazyMeme** [comment]
> the config file seems like it's correct but it's still producing an error, can the bot be configured without having a subdomain set up?

Any domain will work, is the nginx file setup correctly?

**Comment by sh6rpshot** [comment]
From what I'm seeing yes, nginx is active and all the systems connected to it are running properly

**Comment by sh6rpshot** [comment]
Just an update, I notice that there's no websocket.sock file in /var/run/pajbot/sh6rpshot/. Is this normal? My nginx config file suggests that both of these paths should be filled.

**Comment by pajlada** [comment]
> Just an update, I notice that there's no websocket.sock file in /var/run/pajbot/sh6rpshot/. Is this normal? My nginx config file suggests that both of these paths should be filled.

Sounds to me like your pajbot instance isn't writing the websocket file to the right path.

Does the `/var/run/pajbot/sh6rpshot/` directory exist?
Is the `unix_socket` setting set under the `[websocket]` category? https://github.com/pajbot/pajbot/blob/master/configs/example.ini#L120-L126 if it is, what is it set to?
What version of pajbot are you running? If not a stable version, what commit hash?

Next step after this would be to export the logs from the pajbot instance to see if it's maybe having permissions errors making it unable to create the socket file in the directory or something like that.

**Comment by RAnders00** [comment]
Let us know if you need any more help, I‘ll close this since you haven‘t gotten back on this in quite a while.
