### ISSUE TITLE
Toggling modules and the banphrase api aren't working on a fresh venv

### ISSUE THREAD

**Issue by MagicHack** [pajbot/pajbot#1808]
While doing some testing I completely removed my venv and reinstalled it. After the  reinstall toggling stuff on the web interface stopped working as well as the banphrase api.
I tried downgrading from 1.60 to 1.59 and the problem is still present with a fresh venv.

Error in the console on toggling `POST https://twitch.magichack.xyz/api/v1/modules/toggle/top 400`
Banphrase api errror `{"message": "The browser (or proxy) sent a request that this server could not understand."}`

Nothing out of the ordinary in the bot logs.

**Comment by ALazyMeme** [comment]
Can reproduce

**Comment by MagicHack** [comment]
Another weird finding at least for the banphrase api, specifying the headers  `Content-Type': 'application/json'` and sending the test message as json works.
![image](https://user-images.githubusercontent.com/24930768/161409524-722dac95-1a2c-4892-b5a5-a924040b84b0.png)

**Comment by pajlada** [comment]
Can confirm, returns HTTP code 400 but still actually toggles the module
