### ISSUE TITLE
Graph of user's points and points record

### ISSUE THREAD

**Issue by joaopms** [pajbot/pajbot#188]
Show a happy little graph on the user's profiles that displays how many points the user had through the week/month/year. Also show the user's points record and the date of the record.

**Comment by T-Brawl** [comment]
Great idea but it does imply a lot of stuff. At least a database to store values and a dashboard to actually display those.

**Comment by joaopms** [comment]
@T-Brawl Honestly, I don't think it would be that hard. You just have to know when a user gained/lost points. To make it more simple, a solution would be to just keep track of losts/gains in raffles/roulettes.
And we don't really need a new dashboard, just put it in the user's profile.

**Comment by RAnders00** [comment]
Due to pajbot [being moved into maintenance mode](https://github.com/pajbot/pajbot/blob/master/README.md) I'm closing this feature request.
