### ISSUE TITLE
`announce` reply type doesn't actually work

### ISSUE THREAD

**Issue by Felanbird** [pajbot/pajbot#1930]
![image](https://user-images.githubusercontent.com/41973452/168384044-50c6fdfd-2a75-4e71-8228-482820c63d64.png)
![image](https://user-images.githubusercontent.com/41973452/168384080-6e6bbddf-1996-4f7b-ae46-4bb22d256dba.png)

**Comment by ALazyMeme** [comment]
I don't believe it's meant to work in that scenario. Refer [here](https://github.com/pajbot/pajbot/pull/1847#discussion_r857126488).

**Comment by Felanbird** [comment]
Discussed on stream, The reply type should work and does not, what was meant in the above comment was preventing users from invoking `/announce` when using a command that supports `$(args:1-10)` or something along those lines.
