### ISSUE TITLE
Top emotes on `/stats`

### ISSUE THREAD

**Issue by mmattbtw** [pajbot/pajbot#1959]
I think it'd be nice to have top emotes on `/stats` because StreamElements still hasn't implemented 7TV emote stats, and pajbot already tracks the amount of times an emote has been used. (Also it would be nice if we could customize the amount of emotes that show up on `/stats` instead of just having the top 5)

**Comment by pajlada** [comment]
Happy to have the functionality added, but not looking to implement this myself.
