### ISSUE TITLE
Add a feature list of the bot somewhere

### ISSUE THREAD

**Issue by pajlada** [pajbot/pajbot#196]
pajbot.com maybe?
README.md in this repo maybe?

**Comment by Nacht123** [comment]
should be on pajbot.com or here in the wiki.
since there are to much features it would be getting spammed in README.md

and maybe remove all the bots from README.md since there are already on pajbot.com

**Comment by RAnders00** [comment]
Due to pajbot [being moved into maintenance mode](https://github.com/pajbot/pajbot/blob/master/README.md) I'm closing this feature request.

**Comment by alazymeme** [comment]
This is more documentation focused, not bot focused. Can you reopen and assign me pls
