### ISSUE TITLE
Certain commands are missing from the admin commands page

### ISSUE THREAD

**Issue by Felanbird** [pajbot/pajbot#1965]
https://redshell.pajbot.com/commands vs https://redshell.pajbot.com/admin/commands 

`Note: pajbot/web/routes/admin/commands.py uses a different method to fetch the list of commands. see if we can use pajbot.web.utils.get_cached_commands() there too? or at least the underlying way to get them uncached`

**Comment by pajlada** [comment]
Wasn't actually an issue in the way we fetch commands really, but rather commands that had non-unique aliases. Redshell had 5 discord commands, 4 enabled ones and 1 disabled one somehow
