### ISSUE TITLE
When there are multiple ban reasons, the whisper response is wrong

### ISSUE THREAD

**Issue by hotbear1110** [pajbot/pajbot#1977]
When a user gets banned for multiple reasons, the whisper response shows the wrong timeout length.

Example:
Timeout:
![image](https://user-images.githubusercontent.com/77441913/173199081-2b6c8893-c45e-484a-8251-3d472a1dc521.png)

Whisper:
![image](https://user-images.githubusercontent.com/77441913/173199102-78a25315-a38c-413c-9836-7c2aa30982fb.png)

**Comment by pajlada** [comment]
For reference, the whisper notification triggers in the modules themselves, while the timeout duration is only defined there but trickles down and gets triggered only once other modules have had a chance to also trickle down their timeout duration.
To solve this issue, we'd need to either:
1) Trickle down a timeout whisper so it can be concatenated
2) Move all timeout whisper logic to the trickled down timeout
3) Delete the "whisper on timeout" functionality entirely

I'm in favour of #3 as the user can now see their timeout reason already
![image](https://user-images.githubusercontent.com/962989/175766823-eb5ce9b5-8e40-46a9-9175-b44962f3c329.png)

**Comment by RAnders00** [comment]
I agree, option 3 seems like the best option 👍🏻

**Comment by ALazyMeme** [comment]
This was fixed by #2003 right?
