### ISSUE TITLE
Mark donators in the pleblist system

### ISSUE THREAD

**Issue by pajlada** [pajbot/pajbot#198]
Somehow a tag system based on the users paypal email?

**Comment by pajlada** [comment]
Next step: In the pleblist host, do the fun frontend part.
Next to the donators name, there should be a list of tags and a "+" button.
The +-button will open up a modal in which you can type in the tag you want to add to the user.
Make sure the modal is fast.

### API Endpoints
`GET /api/v1/email/tags`
#### Arguments
email

`POST /api/v1/email/tags`
#### Arguments
email
new_tag

`GET /api/v1/email/tags`
#### Arguments
email
new_tag

**Comment by alazymeme** [comment]
@pajlada You might also be able to remove this too due to logins being removed
