### ISSUE TITLE
Trouble installing and getting stuff running

### ISSUE THREAD

**Issue by jkalter24** [pajbot/pajbot#2013]
hello, I have been trying to install pajbot. I think I got everything working. the local ip for the bot goes to Nginx but when added bot_login it wont work or error 502

![image](https://user-images.githubusercontent.com/70232140/178089277-e2bed456-f3ae-4927-9ea0-8c8b4ebeb74d.png)

Link to the nginx/site-enabled file https://gist.github.com/jkalter24/0ea42fcb20ba8da8ab9a8f813be99a30

I may just try reinstalling tommorow.

**Comment by RAnders00** [comment]
Hi, thanks for providing those details. Could you also post the output of `journalctl -efu pajbot-web@thecyberzone`, e.g. as a GitHub Gist. This would include the reason as to why the web service exited with an error code.

**Comment by jkalter24** [comment]
> 

https://gist.github.com/jkalter24/44d58b4e76ab806552267a178ad2c2b2

**Comment by pajlada** [comment]
Have you run the `./scripts/venvinstall.sh` script when you cloned the repo?

**Comment by jkalter24** [comment]
Yes im pretty sure

**Comment by jkalter24** [comment]
> Have you run the `./scripts/venvinstall.sh` script when you cloned the repo?

Yes I think I did

**Comment by pajlada** [comment]
> > Have you run the `./scripts/venvinstall.sh` script when you cloned the repo?
> 
> Yes I think I did

Can you try running it again? One of the errors
`Failed to locate executable /opt/pajbot/venv/bin/uwsgi: No such file or directory`
says it can't find the binary in your virtual environment directory. This should be installed if you've run `./scripts/venvinstall.sh` in the `/opt/pajbot` directory

**Comment by jkalter24** [comment]
> 

I ran it again

**Comment by RAnders00** [comment]
Try these commands in this order:

```
sudo systemctl restart pajbot@thecyberzone
sudo systemctl restart pajbot-web@thecyberzone
```

if that doesn‘t get things running, i‘d be interested in the `journalctl` logs of `pajbot@thecyberzone` as well as `pajbot-web@thecyberzone`.

**Comment by jkalter24** [comment]
> 

for the pajbot@thecyberzone https://gist.github.com/jkalter24/c19c9182aad7d67e3940d803e210b2a2
for pajbot-web@thecyberzone https://gist.github.com/jkalter24/42c3c80a24e261839f6c3817f73f5d7c

**Comment by jkalter24** [comment]
> Try these commands in this order:
> 
> ```
> sudo systemctl restart pajbot@thecyberzone
> sudo systemctl restart pajbot-web@thecyberzone
> ```
> 
> if that doesn‘t get things running, i‘d be interested in the `journalctl` logs of `pajbot@thecyberzone` as well as `pajbot-web@thecyberzone`.

for the pajbot@thecyberzone https://gist.github.com/jkalter24/c19c9182aad7d67e3940d803e210b2a2
for pajbot-web@thecyberzone https://gist.github.com/jkalter24/42c3c80a24e261839f6c3817f73f5d7c

**Comment by RAnders00** [comment]
From the logs you posted, it looks like you missed this step: https://github.com/pajbot/pajbot/tree/master/install-docs

and no, I don‘t think you need a full reinstall. Try doing that linked step/command above, then restart both in that order again and if things don‘t work i‘d be interested in the log outputs again.

**Comment by jkalter24** [comment]
> From the logs you posted, it looks like you missed this step: https://github.com/pajbot/pajbot/tree/stable/install-docs#create-a-database-schema
> 
> and no, I don‘t think you need a full reinstall. Try doing that linked step/command above, then restart both in that order again and if things don‘t work i‘d be interested in the log outputs again.

ERROR:  schema "pajbot1_thecyberzone" already exists

**Comment by jkalter24** [comment]
> ```
> sudo systemctl restart pajbot-web@thecyberzone
> ```

https://gist.github.com/jkalter24/be5947c0d2ab8de45e309c961a9cf745

**Comment by jkalter24** [comment]
> From the logs you posted, it looks like you missed this step: https://github.com/pajbot/pajbot/tree/stable/install-docs#create-a-database-schema
> 
> and no, I don‘t think you need a full reinstall. Try doing that linked step/command above, then restart both in that order again and if things don‘t work i‘d be interested in the log outputs again.

https://gist.github.com/jkalter24/be5947c0d2ab8de45e309c961a9cf745 the log the for the pajbot@thecyberzone
https://gist.github.com/jkalter24/1bbfc27ce4a321c777b0f10ecafe7297 pajbot-web@thecyberzone

**Comment by jkalter24** [comment]
> What does it say under `db =` in your `configs/thecyberzone.ini`?
![image](https://user-images.githubusercontent.com/70232140/179296348-0b27362a-2c41-4e2a-a2f5-3b401b1f0aa8.png)

it was still set to streamer_name and I just changed it Still wont start 
pajbot@thecyberzone is  https://gist.github.com/jkalter24/bc193a920f492fd3b27c7c95e858b89a
and pajbot-web@thecyberzone is https://gist.github.com/jkalter24/68222bcdba81e7fe7c146de68314b885

**Comment by jkalter24** [comment]
> What does it say under `db =` in your `configs/thecyberzone.ini`?

When running the ngix check command https://gist.github.com/jkalter24/5827d00174e3e8cc9a5d482e6c5785f8
when running the log for pajbot@thecyberzone I get this https://gist.github.com/jkalter24/9ce45e5fa6087a9d107ac4b08514011e

**Comment by RAnders00** [comment]
Do you perchance have more than one file in `/etc/nginx/sites-enabled`?

**Comment by jkalter24** [comment]
> Do you perchance have more than one file in `/etc/nginx/sites-enabled`?
> 
> (If not - I couldn‘t see anything wrong with the nginx file you posted above)

It appears there are 3 there. oops how should I proceed 
![image](https://user-images.githubusercontent.com/70232140/179375747-f91acfaa-33d3-4415-b351-2b17af0a2493.png)

**Comment by RAnders00** [comment]
Depends on which domain you want the bot website to run on - `bot.thecyberzone.online` or `thecyberzone.online`? Delete the one that you don't want. If you want one of them to redirect to the other, I can help you set that up later.

Afterwards, `sudo nginx -t` should say the config is okay, hopefully - you should then restart nginx (`sudo systemctl restart nginx`) and I'm hoping your website will work then. You can then do the authorization step from the instructions and then your bot should come online in chat as well.

**Comment by jkalter24** [comment]
> Still no luck. The domain is not working. I get this error for pajbot@thecyberzone https://gist.github.com/jkalter24/b05093e89caadef2004443cc24b8edeb

**Comment by RAnders00** [comment]
Yes, that error is normal and will keep appearing until you get the website running and authorize the bot. I was hopeful the website would start since the pajbot-web logs showed no error.

And now, do you want the bot to run on `bot.thecyberzone.online` or `thecyberzone.online`. If it‘s the former, you‘re missing a DNS CNAME entry for that. If it‘s the latter, we have some kind of misconfiguration making it so i get infinite redirects when i visit that site. Let me know if you need help with any of these things.

**Comment by jkalter24** [comment]
> Yes, that error is normal and will keep appearing until you get the website running and authorize the bot. I was hopeful the website would start since the pajbot-web logs showed no error.
> 
> And now, do you want the bot to run on `bot.thecyberzone.online` or `thecyberzone.online`. If it‘s the former, you‘re missing a DNS CNAME entry for that. If it‘s the latter, we have some kind of misconfiguration making it so i get infinite redirects when i visit that site. Let me know if you need help with any of these things.

I want it to be bot.thecyberzone.online I want to use the main domain to redirect to my twitch or my website

**Comment by RAnders00** [comment]
Yes, in that case, would you mind going to CloudFlare and taking a screenshot of your DNS entries and posting that here? You can just paste images into the text box or use the image upload button above the textbox.

**Comment by jkalter24** [comment]
> Yes, in that case, would you mind going to CloudFlare and taking a screenshot of your DNS entries and posting that here? You can just paste images into the text box or use the image upload button above the textbox.

![image](https://user-images.githubusercontent.com/70232140/179677126-689f0852-5dea-442b-96a5-4a951d52d202.png)

**Comment by RAnders00** [comment]
Add a CNAME for `bot` that points to `thecyberzone.online`.

**Comment by jkalter24** [comment]
> Add a CNAME for `bot` that points to `thecyberzone.online`, similar to how there‘s one for `www` already

![image](https://user-images.githubusercontent.com/70232140/179785486-0d6a926c-5544-46da-931d-58a706f96688.png)

**Comment by RAnders00** [comment]
What's the output of `sudo systemctl status nginx`? Is `sudo nginx -t` okay now?

**Comment by jkalter24** [comment]
sudo systemctl status nginx output ![image](https://user-images.githubusercontent.com/70232140/180266418-47eb02f0-f7a6-4e3a-9f16-59bfb0bceac9.png)

and yes nginx -t shows up that its ok

**Comment by jkalter24** [comment]
![image](https://user-images.githubusercontent.com/70232140/180270055-d47e79d5-4581-4705-b49b-bf2790de64d2.png)
![image](https://user-images.githubusercontent.com/70232140/180270092-a2616a7a-5515-4ea3-abf9-47ccd4492828.png)
![image](https://user-images.githubusercontent.com/70232140/180270149-f70d647e-87d4-4ded-8de2-8ba09ed079d9.png)
Do I need to point my ip to anything or portfoward? or did I mess something up in a config

**Comment by RAnders00** [comment]
Can you go ahead and temporarily disable the orange cloud (proxying) in the DNS section of CloudFlare for all the three entries that have it? I'm trying to figure out why your server is responding with a 404 Not Found even though from the things you've shown me I'd expect the pajbot website to show up.

**Comment by RAnders00** [comment]
From what I can tell you've got port 443 blocked in a firewall or, if you're using your home internet, it's not port-forwarded. The server is responding on port 80 but on port 443 the connection is refused.

**Comment by jkalter24** [comment]
> From what I can tell you've got port 443 blocked in a firewall or, if you're using your home internet, it's not port-forwarded. The server is responding on port 80 but on port 443 the connection is refused.

I just port fowarded 443

**Comment by RAnders00** [comment]
I'm not able to access the website via `https://bot.thecyberzone.online`, with the same error as before (connection refused).  However since you seem to be able to access it yourself you should now be able to perform the authorization step (visit https://bot.thecyberzone.online/bot_login)

**Comment by jkalter24** [comment]
> I'm not able to access the website via `https://bot.thecyberzone.online`, with the same error as before (connection refused). However since you seem to be able to access it yourself you should now be able to perform the authorization step (visit https://bot.thecyberzone.online/bot_login) - see also https://github.com/pajbot/pajbot/tree/master/install-docs#authenticate-the-bot

Done. Should I try doing this again? https://github.com/pajbot/pajbot/blob/master/install-docs/certbot-with-cloudflare/README.md

**Comment by RAnders00** [comment]
Some thing you can do to double-check your setup is correct:

* Visit https://ipinfo.io/ - is the IP address shown there identical to the one you set in CloudFlare?
* Is the port forward in your router pointing to the correct local IP adress (i.e. you should have a TCP port forward for port 80 and 443 pointing to the same local IP that you're entering into your browser to access the website).

**Comment by RAnders00** [comment]
Yes, you'll have to change that A record then. I'm hopeful that this was the problem and your website will be reachable afterwards.

**Comment by jkalter24** [comment]
> Yes, you'll have to change that A record then. I'm hopeful that this was the problem and your website will be reachable afterwards.

Changed the record no luck.

**Comment by RAnders00** [comment]
Pajbot used to have a song request system, but we removed it because better alternatives exist (e.g. streamelements songrequest, https://www.queup.net/ , streamlabs probably has an equivalent as well, etc.), and because nobody wanted to invest the work to keep it updated and make it good.

Since your website appears to be working now, you can try re-enabling the orange cloud/CloudFlare proxying in the CloudFlare DNS settings page.

It sounds like you also managed to get the bot working in chat then? Does it respond to commands? In that case I‘d like to close this issue.
