### ISSUE TITLE
Admin pages leads to a 404

### ISSUE THREAD

**Issue by ALazyMeme** [pajbot/pajbot#2049]
![image](https://user-images.githubusercontent.com/12804673/181861711-eee0c753-f5df-4844-962c-8ecd057fa772.png)

**Comment by pajlada** [comment]
Gonna need some more info on that, works for me
![image](https://user-images.githubusercontent.com/962989/181905130-989fc56b-37f8-434c-8bca-4687a28af5a4.png)

**Comment by ALazyMeme** [comment]
> Gonna need some more info on that

Upon closer inspection, it seems that ALL of my admin pages are not working. All with 404 errors in edge:

![image](https://user-images.githubusercontent.com/12804673/181909098-a60c481d-0c6a-4750-a7e8-93b40c2d82d4.png)
