### ISSUE TITLE
Migrate IRC-based commands to helix

### ISSUE THREAD

**Issue by ALazyMeme** [pajbot/pajbot#2117]
Refer: https://discuss.dev.twitch.tv/t/deprecation-of-chat-commands-through-irc

IRC commands are being deprecated in favour of the helix endpoints, meaning we need to move over to said endpoints prior to February 2023.

Migration guide: https://dev.twitch.tv/docs/irc/chat-commands#migration-guide

My idea is to:

- Check if the bot token contains the relevant scope to perform the requested action
- If not, fallback to the irc command
- Send deprecation message
- Once the IRC commands are turned off, we will be forced to fallback to nothing for the users who have not re-authed their bot
- Remove the IRC command-based code after they are turned off

Happy to hear other ideas, but I don't think we should enforce a breaking change straight away if we have roughly 5 months until the commands are removed.

**Comment by RAnders00** [comment]
I think the commands we use are:
* `/vips`
* `/mods`
* `/timeout`, `/ban`, `/unban`/`/untimeout`
* `/delete`
* `/announce`
* `/whisper`
* `/subscribers` and `/subscribersoff` (paid submode module)

Am I missing any?

**Comment by ALazyMeme** [comment]
Looks like we also use emoteonly, uniquechat, slow and followersonly in the default chat states module.

**Comment by ALazyMeme** [comment]
A few more to mention. Not sure if `/vips` and `/mods` will be deprecated, since they've all been added to helix:

VIPs: https://dev.twitch.tv/docs/api/reference#get-vips
Mods: https://dev.twitch.tv/docs/api/reference#get-moderators

**Comment by ALazyMeme** [comment]
In the migration of the untimeout function, as twitch does not supply a way to untimeout a user anymore, can we utilize the function of `timeout_end`? Since it is `None` for a normal user AND a banned user; can we just `return` if `None`?

**Comment by ALazyMeme** [comment]
I can't help but think I should split this down into an issue for each command
