### ISSUE TITLE
Lastseen command crashing bot

### ISSUE THREAD

**Issue by Mr-Cheeezz** [pajbot/pajbot#2195]
when  i use the !lastseen command it crashes the bot

**Comment by pajlada** [comment]
can you post a stacktrace or logs from the bot?

**Comment by Mr-Cheeezz** [comment]
where do i find them?

**Comment by pajlada** [comment]
Depends on how you're running the bot, if you're running it as a systemd unit you can find it with journalctl (e.g. `journalctl --user -fu pajbot@'*'` or `sudo journalctl -fu pajbot@'*'`

**Comment by Mr-Cheeezz** [comment]
pajlada my server ran into a issue where i need to reinstall everything, so how wound i reinstall pajbot with keeping all my data?

**Comment by pajlada** [comment]
You would need to backup your pajbot config file, your PostgreSQL database, and you'd probably want the Redis database too.
Once on your new server, upload your pajbot config file, then upload & restore your PostgreSQL & Redis databases

**Comment by Mr-Cheeezz** [comment]
how would i do that

**Comment by pajlada** [comment]
Best way would be to google that, it's not pajbot-specific instructions and depends a lot on your server and how you're running pajbot.

**Comment by Mr-Cheeezz** [comment]
Also very sorry about well side tracking this issue but do you know any server companies that provide Debian 9 mine is contabo it only provides debain 10 and 11

**Comment by pajlada** [comment]
No clue, sorry

**Comment by RAnders00** [comment]
The fact that the install instructions mention Debian 9 is not intended and it‘s merely outdated. Following the steps on Debian 11 was the correct thing to do. I‘ll create a separate issue about it so we can fix it.

**Comment by RAnders00** [comment]
About your actual issue though:

On the **old** install, stop the bot (`sudo systemctl stop pajbot@streamer_name`) and then take a database backup with `sudo -u pajbot pg_dump pajbot > dump.sql`

Then, download `/opt/pajbot/configs/streamer_name.ini` and this `dump.sql` you just created from the server.

Install your new system as you see fit, but when installing pajbot, you deviate a bit from the instructions:
![739BEA58-D8BC-4C12-BBC7-5A73CAA9D485](https://user-images.githubusercontent.com/1629196/198133963-98b67d0a-92f0-45e2-9bed-857111166359.jpeg)
Follow the first part as is written in the instructions. When you get to the single-bot setup though, you‘ll want to put the `/opt/pajbot/configs/streamer_name.ini` file in the same place on the new server, and then you‘ll want to restore the database backup with `sudo -u pajbot psql -d pajbot -f dump.sql`. You can then proceed with „Set up the website with nginx“ and then you should be able to start the bot again. **make sure you don‘t do the steps marked in red.**

**Comment by Mr-Cheeezz** [comment]
thanks

**Comment by RAnders00** [comment]
If you end up having issues with the `!lastseen` command crashing your bot, feel free to post another comment here.
