### ISSUE TITLE
cant access /streamer_login and /bot_login get 404 error

### ISSUE THREAD

**Issue by Mr-Cheeezz** [pajbot/pajbot#2211]
when i try to login as bot i get a error 
![image](https://user-images.githubusercontent.com/68625998/199358869-7bd7248b-5a6a-43a1-9fe7-83fbaeea857e.png)
same as streamer_login
![image](https://user-images.githubusercontent.com/68625998/199358922-3311d92f-c5cf-4a90-abbf-f638491d1870.png)

**Comment by ALazyMeme** [comment]
Good Day

Please provide a stacktrace or logs from the bot in order to further assist.

**Comment by Mr-Cheeezz** [comment]
Now I am getting a 502 bad gateway error

**Comment by RAnders00** [comment]
We can‘t help you like this. You‘ll have to do the things we ask you for. We need some more information about what‘s going on, so we need you check the bot‘s logs (`journalctl -eu pajbot@streamer_name`)

**Comment by Mr-Cheeezz** [comment]
pajbot:
`Nov 02 12:58:00 vmi1065408 pajbot@mr_cheeezz[1234]:   File "/opt/pajbot/pajbot/apiwrappers/twitch/helix.py", line 210, in <lambda>
Nov 02 12:58:00 vmi1065408 pajbot@mr_cheeezz[1234]:     fetch_fn=lambda: self._fetch_user_data_by_id(user_id),
Nov 02 12:58:00 vmi1065408 pajbot@mr_cheeezz[1234]:   File "/opt/pajbot/pajbot/apiwrappers/twitch/helix.py", line 185, in _fetch_user_data_by_id
Nov 02 12:58:00 vmi1065408 pajbot@mr_cheeezz[1234]:     response = self.get("/users", {"id": user_id})
Nov 02 12:58:00 vmi1065408 pajbot@mr_cheeezz[1234]:   File "/opt/pajbot/pajbot/apiwrappers/twitch/base.py", line 71, in get
Nov 02 12:58:00 vmi1065408 pajbot@mr_cheeezz[1234]:     return self.request("GET", endpoint, params, headers, authorization).json()
Nov 02 12:58:00 vmi1065408 pajbot@mr_cheeezz[1234]:   File "/opt/pajbot/pajbot/apiwrappers/twitch/helix.py", line 145, in request
Nov 02 12:58:00 vmi1065408 pajbot@mr_cheeezz[1234]:     raise e
Nov 02 12:58:00 vmi1065408 pajbot@mr_cheeezz[1234]:   File "/opt/pajbot/pajbot/apiwrappers/twitch/helix.py", line 136, in request
Nov 02 12:58:00 vmi1065408 pajbot@mr_cheeezz[1234]:     return super().request(method, endpoint, params, headers, authorization, json)
Nov 02 12:58:00 vmi1065408 pajbot@mr_cheeezz[1234]:   File "/opt/pajbot/pajbot/apiwrappers/twitch/base.py", line 35, in request
Nov 02 12:58:00 vmi1065408 pajbot@mr_cheeezz[1234]:     "Authorization": f"{self.authorization_header_prefix} {authorization.token.access_token}",
Nov 02 12:58:00 vmi1065408 pajbot@mr_cheeezz[1234]:   File "/opt/pajbot/pajbot/apiwrappers/authentication/token_manager.py", line 79, in token
Nov 02 12:58:00 vmi1065408 pajbot@mr_cheeezz[1234]:     self.initialize()
Nov 02 12:58:00 vmi1065408 pajbot@mr_cheeezz[1234]:   File "/opt/pajbot/pajbot/apiwrappers/authentication/token_manager.py", line 65, in initialize
Nov 02 12:58:00 vmi1065408 pajbot@mr_cheeezz[1234]:     self._token = self.fetch_new()
Nov 02 12:58:00 vmi1065408 pajbot@mr_cheeezz[1234]:   File "/opt/pajbot/pajbot/apiwrappers/authentication/token_manager.py", line 97, in fetch_new
Nov 02 12:58:00 vmi1065408 pajbot@mr_cheeezz[1234]:     return self.api.get_app_access_token(self.scope)
Nov 02 12:58:00 vmi1065408 pajbot@mr_cheeezz[1234]:   File "/opt/pajbot/pajbot/apiwrappers/twitch/id.py", line 11, in get_app_access_token
Nov 02 12:58:00 vmi1065408 pajbot@mr_cheeezz[1234]:     response = self.post(
Nov 02 12:58:00 vmi1065408 pajbot@mr_cheeezz[1234]:   File "/opt/pajbot/pajbot/apiwrappers/base.py", line 116, in post
Nov 02 12:58:00 vmi1065408 pajbot@mr_cheeezz[1234]:     return self.request("POST", endpoint, params, headers, json, **request_options).json()
Nov 02 12:58:00 vmi1065408 pajbot@mr_cheeezz[1234]:   File "/opt/pajbot/pajbot/apiwrappers/base.py", line 97, in request
Nov 02 12:58:00 vmi1065408 pajbot@mr_cheeezz[1234]:     response.raise_for_status()
Nov 02 12:58:00 vmi1065408 pajbot@mr_cheeezz[1234]:   File "/opt/pajbot/venv/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_f>
Nov 02 12:58:00 vmi1065408 pajbot@mr_cheeezz[1234]:     raise HTTPError(http_error_msg, response=self)
Nov 02 12:58:00 vmi1065408 pajbot@mr_cheeezz[1234]: requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://id.twitch.tv/oaut>
Nov 02 12:58:00 vmi1065408 systemd[1]: pajbot@mr_cheeezz.service: Main process exited, code=exited, status=1/FAILURE
Nov 02 12:58:00 vmi1065408 systemd[1]: pajbot@mr_cheeezz.service: Failed with result 'exit-code'.
Nov 02 12:58:00 vmi1065408 systemd[1]: pajbot@mr_cheeezz.service: Consumed 1.794s CPU time.`

pajbot-web:
`Nov 02 12:59:33 vmi1065408 systemd[1]: pajbot-web@mr_cheeezz.service: Scheduled restart job, restart counter is at 82.
Nov 02 12:59:33 vmi1065408 systemd[1]: Stopped pajbot-web for mr_cheeezz.
Nov 02 12:59:33 vmi1065408 systemd[1]: pajbot-web@mr_cheeezz.service: Consumed 2.034s CPU time.
Nov 02 12:59:33 vmi1065408 systemd[1]: Started pajbot-web for mr_cheeezz.
Nov 02 12:59:33 vmi1065408 pajbot-web@mr_cheeezz[1316]: [uWSGI] getting INI configuration from uwsgi_shared.ini
Nov 02 12:59:33 vmi1065408 pajbot-web@mr_cheeezz[1316]: *** Starting uWSGI 2.0.20 (64bit) on [Wed Nov  2 12:59:33 2022] ***
Nov 02 12:59:33 vmi1065408 pajbot-web@mr_cheeezz[1316]: compiled with version: 10.2.1 20210110 on 02 November 2022 01:44:40
Nov 02 12:59:33 vmi1065408 pajbot-web@mr_cheeezz[1316]: os: Linux-5.10.0-19-cloud-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21)
Nov 02 12:59:33 vmi1065408 pajbot-web@mr_cheeezz[1316]: nodename: vmi1065408
Nov 02 12:59:33 vmi1065408 pajbot-web@mr_cheeezz[1316]: machine: x86_64
Nov 02 12:59:33 vmi1065408 pajbot-web@mr_cheeezz[1316]: clock source: unix
Nov 02 12:59:33 vmi1065408 pajbot-web@mr_cheeezz[1316]: detected number of CPU cores: 8
Nov 02 12:59:33 vmi1065408 pajbot-web@mr_cheeezz[1316]: current working directory: /opt/pajbot
Nov 02 12:59:33 vmi1065408 pajbot-web@mr_cheeezz[1316]: detected binary path: /opt/pajbot/venv/bin/uwsgi
Nov 02 12:59:33 vmi1065408 pajbot-web@mr_cheeezz[1316]: !!! no internal routing support, rebuild with pcre support !!!
Nov 02 12:59:33 vmi1065408 pajbot-web@mr_cheeezz[1316]: your processes number limit is 120319
Nov 02 12:59:33 vmi1065408 pajbot-web@mr_cheeezz[1316]: your memory page size is 4096 bytes
Nov 02 12:59:33 vmi1065408 pajbot-web@mr_cheeezz[1316]: detected max file descriptor number: 1024
Nov 02 12:59:33 vmi1065408 pajbot-web@mr_cheeezz[1316]: lock engine: pthread robust mutexes
Nov 02 12:59:33 vmi1065408 pajbot-web@mr_cheeezz[1316]: thunder lock: disabled (you can enable it with --thunder-lock)
Nov 02 12:59:33 vmi1065408 pajbot-web@mr_cheeezz[1316]: uwsgi socket 0 bound to UNIX address /var/run/pajbot/mr_cheeezz/web.sock fd 3
Nov 02 12:59:33 vmi1065408 pajbot-web@mr_cheeezz[1316]: Python version: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110]
Nov 02 12:59:33 vmi1065408 pajbot-web@mr_cheeezz[1316]: PEP 405 virtualenv detected: venv
Nov 02 12:59:33 vmi1065408 pajbot-web@mr_cheeezz[1316]: Set PythonHome to venv
Nov 02 12:59:33 vmi1065408 pajbot-web@mr_cheeezz[1316]: Python main interpreter initialized at 0x561c9ad3f190
Nov 02 12:59:33 vmi1065408 pajbot-web@mr_cheeezz[1316]: python threads support enabled
Nov 02 12:59:34 vmi1065408 pajbot-web@mr_cheeezz[1316]: your server socket listen backlog is limited to 100 connections
Nov 02 12:59:34 vmi1065408 pajbot-web@mr_cheeezz[1316]: your mercy for graceful operations on workers is 60 seconds
Nov 02 12:59:34 vmi1065408 pajbot-web@mr_cheeezz[1316]: mapped 145840 bytes (142 KB) for 1 cores
Nov 02 12:59:34 vmi1065408 pajbot-web@mr_cheeezz[1316]: *** Operational MODE: single process ***`

**Comment by RAnders00** [comment]
The problem is that your client_id, client_secret and redirect_uri are somehow incorrect. Make sure all three match up what‘s being shown in the Twitch Dev console.

**Comment by Mr-Cheeezz** [comment]
That fixed the issue, thanks.
