### ISSUE TITLE
move the point-system to a module

### ISSUE THREAD

**Issue by pajlada** [pajbot/pajbot#224]
The module listens to the on_chatters_update event and just gives points to the users FeelsGoodMan
could this work?
maybe
idk
let's try

This would let us have a setting to how many points a user should get for spending 5 minutes in the stream, both as a pleb and as a sub.
And perhaps a name for the point thing, such as calling points "nanopoints" instead of "points".
That alias could be fetched with some dank variable like $(phrase:points) or w/e

**Comment by RAnders00** [comment]
Due to pajbot [being moved into maintenance mode](https://github.com/pajbot/pajbot/blob/master/README.md) I'm closing this request for a major internal overhaul of pajbot.
