### ISSUE TITLE
Another way of acquiring tokens:

### ISSUE THREAD

**Issue by pajlada** [pajbot/pajbot#226]
Get 1 token for watching the stream for 1 hour. how? idk.

This would require us to change the way tokens "expire".
Just make a cap on 10 tokens or something.

**Comment by farbrormelker97** [comment]
sounds fair but there will be alot of sounds then so maybe make it 2 hours or more so it doesnt have to be too often.

**Comment by RAnders00** [comment]
Due to pajbot [being moved into maintenance mode](https://github.com/pajbot/pajbot/blob/master/README.md) I'm closing this feature request.
