### ISSUE TITLE
Include links to the tweets themselves while posting "New cool tweet"s in chat

### ISSUE THREAD

**Issue by zneix** [pajbot/pajbot#2295]
Basically, appending a link to the tweet itself (in the format like `https://twitter.com/i/status/{tweet_id}`) to the messages like the one shown below:
![zneixbot showing pajlada's 'going live' tweet](https://cdn.zneix.eu/csXmKRI.png)
Of course, this could be behind a tickbox on the website under tweet module configuration on the website, could be enabled by default - even thought that'd change the current behaviour I think it would be a nice little Qol.

**Comment by ALazyMeme** [comment]
Do you still want this with the recent planned updates to the twitter api?

**Comment by pajlada** [comment]
Going to close this since Twitter sucks. If their API rules change I'm happy to re-open this and look into it again
