### ISSUE TITLE
Introduce a way to have a link to the last account's tweet available through chat commands

### ISSUE THREAD

**Issue by zneix** [pajbot/pajbot#2296]
I thought of two solutions for this:

1. Introduce a new variable, e.g. `$(lastweet_link:<account>)` which would hold the value `https://twitter.com/i/status/{tweet_id}` or an empty string. This would allow for more flexible/customizable `!whereissomeone`-style commands.
2. Just straight-up append the link in aforementioned format to the value of `$(lasttweet:<account>)` variable. This might be good enough and easier however it might make it rather impossible to have commands that wouldn't post a link, like it is done right now, example:
![pajbot showing pajlada's last tweet](https://cdn.zneix.eu/2BUlkP6.png)

**Comment by pajlada** [comment]
Going to close this since Twitter sucks. If their API rules change I'm happy to re-open this and look into it again
