### ISSUE TITLE
error when updating bot

### ISSUE THREAD

**Issue by mr-cheeezz** [pajbot/pajbot#2415]
error: 
```
mr_cheeezz@vmi1065408:/opt/pajbot$ sudo -H -u pajbot ./scripts/venvinstall.sh
Creating python venv with pyenv
./scripts/venvinstall.sh: 18: pyenv: not found
```

**Comment by Felanbird** [comment]
https://github.com/pajbot/pajbot/blob/master/README.md#python-versioning

**Comment by pajlada** [comment]
#2418 will additionally add some documentation to the install docs.

If you have Python 3.9 or higher, you can just use the SKIP_PYENV=1 environment variable to keep using your system Python.

If your Python is 3.8 or lower, you must follow the install docs to install pyenv on your system.

**Comment by mr-cheeezz** [comment]
thanks
