### ISSUE TITLE
[API] Add API endpoints for leader-boards.

### ISSUE THREAD

**Issue by rigor789** [pajbot/pajbot#250]
Hey, so I was thinking we could have a couple API endpoints for getting stats from the bot.

Pretty much an endpoint for every aspect from https://github.com/pajlada/pajbot/blob/master/pajbot/web/routes/base/stats.py

Route ideas: 

`/top/duel/winners?limit=5` - for `top_5_winners`
`/top/duel/points?limit=5&scope=won` - for `top_5_points_won`
`/top/duel/points?limit=5&scope=lost` - for `top_5_points_lost`
`/top/duel/loosers?limit=5' -`top_5_losers`

etc.

Other possibilities: 
- Drop the scope selectors, and use `order=ASC` / `order=DESC`

**Comment by RAnders00** [comment]
Due to pajbot [being moved into maintenance mode](https://github.com/pajbot/pajbot/blob/master/README.md) I'm closing this feature request.
