### ISSUE TITLE
Follow age/since stopped working after the Twitch follows API changes

### ISSUE THREAD

**Issue by TopFuel** [pajbot/pajbot#2550]
[Twitch removed the Get Users Follows API](https://discuss.dev.twitch.tv/t/legacy-follows-api-and-eventsub-shutdown-timeline-updated/46769) and replaced it with [Get Channel Followers](https://dev.twitch.tv/docs/api/reference/#get-channel-followers) and [Followed Channels](https://dev.twitch.tv/docs/api/reference/#get-followed-channels), that change broke !followage and !followsince.

Get Channel Followers needs the **moderator:read:followers** scope to check if a user follows a channel otherwise it will only return the channel total followers count.

Fortunately channel moderators also have access to the **moderator:read:followers** scope:
> The ID in the broadcaster_id query parameter must match the user ID in the access token or **the user ID in the access token must be a moderator for the specified broadcaster**.

So !followage and !followsince should work with just the bot login from a user that is a channel moderator otherwise it will need to use the streamer login.
But as far as I can see, it will not be possible to check if a user follows some other channel with **!followage [user] [channel]** anymore.

**Comment by pajlada** [comment]
Fixed in #2553
