### ISSUE TITLE
Inidicator for when !#playsound is used

### ISSUE THREAD

**Issue by pajlada** [pajbot/pajbot#259]
Small speaker icon somewhere?
idk

**Comment by gempir** [comment]
`<i class="volume up icon"></i> `

could be an option for the icon from semantic ui http://semantic-ui.com/elements/icon.html#/icons

**Comment by T-Brawl** [comment]
One month later but instead of small speaker icon, maybe an differents emotes (like gachiHop for gachi sounds or KKaper for "Damn son")

**Comment by Nacht123** [comment]
Or just **nothing**, if people don't get that there is a sound playing,
they will **ask what** this **icon** is next and why it **shows up randomly**.

And more stuff on the overlay is maybe at some point to much.

**Comment by gempir** [comment]
That wouldn't solve the problem of new people not knowing where that sound comes from because emotes pop-up all the time.  

Also finding an emote for every sound is annoying

**Comment by Nacht123** [comment]
maybe an **easy way** is,
just let the **bot say** it in chat but with a X sec **delay**.

**Comment by RAnders00** [comment]
Due to pajbot [being moved into maintenance mode](https://github.com/pajbot/pajbot/blob/master/README.md) I'm closing this feature request.
