### ISSUE TITLE
Chat funded raffles?

### ISSUE THREAD

**Issue by dextermb** [pajbot/pajbot#269]
I would like to see chat have the ability to start funding for a raffle and then after _x_ amount of seconds start the raffle
### start funding

```
!fund -s
```
### fund _x_ amount

```
!fund 2000
```
# Bot responses
### start of funding

```
00a5 has started a public raffle, type !fund [amount] to add to the prize pool
```
### every 10 seconds confirmed prize pool

```
Public raffle prize pool: 2000, type !fund [amount] to add to the prize pool
```
### end of funding period, start of raffle

```
Public raffle has started. Type !join to have a chance at winning some of the prize pool
```

:tophat: :briefcase:

**Comment by dextermb** [comment]
@pajlada has this been added or is it worth closing now?

**Comment by RAnders00** [comment]
Due to pajbot [being moved into maintenance mode](https://github.com/pajbot/pajbot/blob/master/README.md) I'm closing this feature request.
