### ISSUE TITLE
Enter pleblist host without streamtip login

### ISSUE THREAD

**Issue by Mstiekema** [pajbot/pajbot#288]
Logging into streamtip / twitchalerts to play chat songrequests doesn't really make sense so maybe there should be an option that you can go straight to the hosting mode for chat requests.

Example
![Example](https://cloud.githubusercontent.com/assets/16525696/14612069/a7860d74-0595-11e6-88fa-04bc70d07948.png)

**Comment by dextermb** [comment]
Good idea!

:tophat: :briefcase:

**Comment by alazymeme** [comment]
@pajlada This can probably be closed since I've removed the login

**Comment by pajlada** [comment]
Not in the pleblist business anymore, at least not here. so closing this off. Thanks!
