### ISSUE TITLE
Issue with aliases

### ISSUE THREAD

**Issue by pajlada** [pajbot/pajbot#289]
Aliases are somehow corrupted when you do the following things:
1. Create command with alias **a**
2. Add alias **b** to command **a**
3. Remove alias **a**

**Comment by RAnders00** [comment]
I cannot reproduce this anymore:

```
23:06 randers: !add command atest1 atest1
23:06 randers: !atest1
23:06 BotFactory: atest1
23:06 randers: !add alias atest1 atest2
23:06 randers: !atest2
23:06 BotFactory: atest1
23:06 randers: !remove alias atest1
23:06 randers: !atest2
23:06 BotFactory: atest1 
```

Also the row in the database is updated correctly.
