### ISSUE TITLE
Donation Lottery system and custom Trivia api/system [feature requests (TODO)]

### ISSUE THREAD

**Issue by pajlada** [pajbot/pajbot#298]
app that checks twitchalerts donations and keeps track of a donation lottery system

Every $150, one donator is chosen by random
instead of "one chosen by random", just randomly sort the list so #1 is #1 prio. if that person doesn't respond, you can talk to #2 etc.

Trivia system with custom questions

**Comment by alazymeme** [comment]
Still looking to integrate this?
