### ISSUE TITLE
No timeout on HSbet

### ISSUE THREAD

**Issue by YourImag1nat1on** [pajbot/pajbot#299]
Sometimes a hsbet will begin at the end of the stream and will keep your points in the bet until Nani or forsen play the next day, I think there should be like a 2 hour timeout on hsbet where if there is no outcome it returns the points

**Comment by Nacht123** [comment]
You can always ask a mod to **reset** the bets with `!hsbet close`
And don't bet before a game starts, just **wait until** the streamer is **ingame**.

**Comment by RAnders00** [comment]
Given that nobody has found this to be an annoyance for over 4 years I'll close this, especially with pajbot being moved into maintenance mode.
