### ISSUE TITLE
!awardpoints command

### ISSUE THREAD

**Issue by YourImag1nat1on** [pajbot/pajbot#300]
I think it would be good to have a command that just gives points intead of edit points,
Also have it so you could use !awardpoints \* 1000 to give everyone in chat 1k for example

**Comment by Nacht123** [comment]
If there would be a command like this, if must have a **bigger** **user** and **global cd** to not fuck up the server.

**Comment by DatGuy1** [comment]
https://pastebin.com/w9shvstj is a working example

**Comment by alazymeme** [comment]
I believe this is fixed by the !editpoints command. But there's still no solution to give points to everyone :/

**Comment by alazymeme** [comment]
> https://pastebin.com/w9shvstj is a working example

@DatGuy1 Is this still working code? Could it potentially be merged?

**Comment by DatGuy1** [comment]
Yes, should be. Updated version here https://pastebin.com/uta6TwD6

**Comment by TroyDota** [comment]
Wait, this does like giga updates.

**Comment by TroyDota** [comment]
https://pastebin.com/200t495f here is a better version.

**Comment by RAnders00** [comment]
Due to pajbot [being moved into maintenance mode](https://github.com/pajbot/pajbot/blob/master/README.md) I'm closing this feature request.
