### ISSUE TITLE
2 new betting systems

### ISSUE THREAD

**Issue by YourImag1nat1on** [pajbot/pajbot#302]
Make a duel system on forsen.tv like csgowild do how you have games open and then you coin flip but don't take a percentage

Make a pot system like all csgo betting sites where you enter a pot and your chances increase the more you bet

**Comment by gempir** [comment]
There is already a point lottery similar to what you want. 

You should explain the first idea a bit more, because it sounds like a normal duel.

**Comment by YourImag1nat1on** [comment]
It would be like csgowild.com where you open room and people can join

Basically a duel on forsen.tv

**Comment by gempir** [comment]
I don't want to visit csgowild.com to understand what you want. Explain more.

The bot already does duels and points lottery what do you want to add

**Comment by YourImag1nat1on** [comment]
Okay i go to forsen.tv, link my twitch, then i create a game, select how much i want to bet or i join a game that has already been made, once both parties join the game there is a coin flip and whoever it lands on they win the pot

The lottery would be the same idea but more people and you can bet however much you want and whoever bets more has higher chance to win

Hope that makes sense, it would basically make it cleaner and not just betting in chat

**Comment by gempir** [comment]
so a duel and a pointlottery ? This functionality literally alread exists just with some small differences. 

I don't see the point of this in the bot.

**Comment by YourImag1nat1on** [comment]
I know it already exists but i think it should have a front end on forsen.tv because no one is spending there points and are just hoarding them

**Comment by gempir** [comment]
So you want a whole graphical interface for gambling? 

I think that's out of the scope of the bot IMO. It would cost a lot of time and effort to make.

**Comment by YourImag1nat1on** [comment]
This isn't exclusively about the bot but i was talking to paj and he asked for suggestions on how people should spend points and put them back into the "system"

**Comment by cinemassacres** [comment]
should close as twitch as implemented a version of that
