### ISSUE TITLE
Scrolling bug in commands list

### ISSUE THREAD

**Issue by pajlada** [pajbot/pajbot#304]
How to reproduce: ![xD](http://i.imgur.com/k4yw0xK.gif)

**Comment by KostasPelelis** [comment]
To make this bug more annoying, I tested in on mobile(the css is a clown fiesta) but the sticky div has the expected behavior

**Comment by alazymeme** [comment]
The imgur is no longer available, are you able to reproduce and reupload to nuuls? Tks
