### ISSUE TITLE
Pleblist enhancements (search, records, etc)

### ISSUE THREAD

**Issue by Hidduh** [pajbot/pajbot#321]
It would be nice to enhance the Pleblist by adding certain features to it, such as:

- Being able to search for certain videos (maybe within a specific timespan?)
- Being able to request video status (as in times played, first time played)

I occassionally go back to the Pleblist overview to watch specific parts in VOD's where videos were played, this would make that a lot easier for those doing the same. Just an idea, though.

**Comment by alazymeme** [comment]
This can probably be closed @pajlada
