### ISSUE TITLE
!$unbanme whisper is not ignored if user is permabanned

### ISSUE THREAD

**Issue by friendlyanon** [pajbot/pajbot#324]
Example:
 * Permabanned via bot
 * Send `!$unbanme` to the bot
 * Bot claims that you are unbanned and deducts the points. This is where it should instead notify the user that they are permabanned via the bot and not deduce points.

Nest time you type something in chat and you are perma'd again.

**Comment by RAnders00** [comment]
https://github.com/pajbot/pajbot/blob/master/pajbot/bot.py#L740 This has been resolved since your issue was created. (No commands will be executed for banned sources)
