### ISSUE TITLE
Autobanned for 5 mins after @ a questionable username

### ISSUE THREAD

**Issue by Eric264** [pajbot/pajbot#334]
I responded to a message @Nigerian__Warlord posted and got auto timeout. I assume this is because of some kind of racism filter? Nothing in my message was of questionable content so I assume the username triggered it. Might want to update the auto-timeout to ignore strings with @ in them so people don't get banned for typing usernames.

**Comment by pajlada** [comment]
then someone could just type `@n-word` and not get timed out
