### ISSUE TITLE
Debug why playsounds sometimes break

### ISSUE THREAD

**Issue by RAnders00** [pajbot/pajbot#399]
Symptom is that editing/adding/removing works, web interface works, module is enabled, WebSocket also works (e.g. showemote still goes through), but it's not possible to make the bot publish a playsound payload either through the "Play on stream" test button OR the !#playsound command

The play on stream endpoint also does not return any error.

Also issue is not alleviated by disabling/enabling the module.

**Comment by alazymeme** [comment]
@RAnders00 Did f174983 end up fixing this issue?

**Comment by RAnders00** [comment]
Not sure, but there have been no reports of that error since, so I think this can be closed.
