### ISSUE TITLE
Debug why "Spelling it" regex behaves differently on snusbot

### ISSUE THREAD

**Issue by RAnders00** [pajbot/pajbot#406]
This is the relevant banphrase:

https://gist.github.com/RAnders00/bcb88598bdd7d2d2b797c5f4d1821e3f

Works as expected on pajbot but times out `N OMEGALUL <chatterino char>` on snusbot.

Possible factors I can think of are python version between the servers or possibly hardcoded behaviour along the lines of `if bot.streamer == "forsen"`

**Comment by RAnders00** [comment]
Confirmed to behave correctly on botnextdoor

```
14:52 pajbot: 1.35 DEV (pajlada-remove-relaybroker, a48751bc, commit 1932), 1 day and 18 hours 
14:52 Snusbot: 1.35 DEV (master, a6f01944, commit 1981), 1 day and 18 hours 
14:52 botnextdoor: 1.35 DEV (master, a6f01944, commit 1981), 1 day and 18 hours 
```

**Comment by pajlada** [comment]
Issue was the "Remove accents" option being enabled in one bot, but not the other.
In the debugging process we found that running strip after the "Remove accents" function was run made the regex simpler anyway
