### ISSUE TITLE
Auto fetch/refresh subscriber badge for web UI

### ISSUE THREAD

**Issue by RAnders00** [pajbot/pajbot#417]
in the same move, maybe do the fetch for streamer avatar in the same way

**Comment by RAnders00** [comment]
I would like to do this after the api wrappers refactor (would be a matter of adding a twitch badges api wrapper and adding a helper like download_logo in the web interface)

**Comment by alazymeme** [comment]
Wasn't this fixed by the subscriber badge option in the config file?

**Comment by RAnders00** [comment]
you are right, this is fixed.
