### ISSUE TITLE
$(epm) should be 0 for known emotes never seen during this runtime

### ISSUE THREAD

**Issue by RAnders00** [pajbot/pajbot#423]
```
pajbot: pajbot 1.35 running!
user: !add command kpm $(epm:KKona)
user: !kpm
---> pajbot should say "0" but doesn't.
user: KKona
user: !kpm
pajbot: 1
```

**Comment by pajlada** [comment]
If the emote exists, but has not been typed this session yet, then returning 0 makes sense. :+1: 
What about if the emote just doesn't exist at all, then we keep the current behaviour right?

**Comment by RAnders00** [comment]
I was thinking so, yes. Consult the emote managers whether emote exists.
