### ISSUE TITLE
Banphrase option for emote matching

### ISSUE THREAD

**Issue by RAnders00** [pajbot/pajbot#424]
Up for discussion:

  - "Must match an emote", e.g. "Kapp" would not match "Kappa"
  - "Must match at start of any emote", e.g. "Kapp" would match "Kapp" and "Kappa"

I'd think just one of them, anything else is confusing. The second behaviour can easily be emulated using regex.

Just wanted to write this down here as an enhancement proposal, so it's not forgotten. Does not have any priority in my opinion.

**Comment by alazymeme** [comment]
I'm not sure if I quite understand this, considering it can be done simply with:
`\bKapp\b` - could you explain further?

**Comment by RAnders00** [comment]
@alazymeme it's meant for sub emotes, e.g. if I created a banphrase for `forsenE` only forsen subs typing forsenE would get timed out with this option enabled

**Comment by alazymeme** [comment]
Sounds interesting; sounds a little difficult 🤔

**Comment by RAnders00** [comment]
Due to pajbot [being moved into maintenance mode](https://github.com/pajbot/pajbot/blob/master/README.md) I'm closing this feature request.
