### ISSUE TITLE
Banphrase subsections sorted by name

### ISSUE THREAD

**Issue by Felanbird** [pajbot/pajbot#456]
Idea for the banphrase page in the admin panel to be sorted by subsections based on banphrase name. 

To deal with the fact that when there's a lot of banphrases the page takes a while to load, if all the banphrases were in their own sections, it would allow for the page to load a lot quicker, and finding a banphrase you actually wanted would be easier with subsections. 

Paint idea included, sections clickable and load only banphrases with corresponding name
![pajbot_idea](https://user-images.githubusercontent.com/41973452/63231469-14623800-c1ea-11e9-942c-6535d3c75e01.png)

I am aware tho that this would still generate a very large section (No Name banphrase) but it would be extremely useful for well maintained banphrases :)

**Comment by alazymeme** [comment]
This could probably be sorted similar to the modules page

**Comment by RAnders00** [comment]
Due to pajbot [being moved into maintenance mode](https://github.com/pajbot/pajbot/blob/master/README.md) I'm closing this feature request.
