### ISSUE TITLE
Add a commercial module

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#457]
Fairly simple, add the ability to bind /commercial to a command.

**Comment by alazymeme** [comment]
For this, adding a module that allows for automatic ad playing or something would be cool

**Comment by alazymeme** [comment]
Would also like to see the addition of being able to use this within a timer

**Comment by RAnders00** [comment]
Due to pajbot [being moved into maintenance mode](https://github.com/pajbot/pajbot/blob/master/README.md) I'm closing this feature request. You are of course free to add this feature via PR yourself.

**Comment by alazymeme** [comment]
> Due to pajbot [being moved into maintenance mode](https://github.com/pajbot/pajbot/blob/master/README.md) I'm closing this feature request. You are of course free to add this feature via PR yourself.

I'm already somewhat working on this, can you reopen and assign me
