### ISSUE TITLE
"largest timeout wins" module

### ISSUE THREAD

**Issue by RAnders00** [pajbot/pajbot#473]
- listen to CLEARCHAT
- algorithm that detects overridden (shorter) timeouts
- schedule the final timeout in a few seconds to undo the override

**Comment by pajlada** [comment]
"beta" version in pajbot2 https://github.com/pajbot/pajbot2/commit/2349c26f2b0a8f69c4b1432427ffe32bdbd3b8b4

**Comment by RAnders00** [comment]
good enough for me
