### ISSUE TITLE
Add 'submysterygift' and 'giftpaidupgrade' to subalert

### ISSUE THREAD

**Issue by DatGuy1** [pajbot/pajbot#487]

**Comment by pajlada** [comment]
Example "giftpaidupgrade" message: `@badge-info=subscriber/5;badges=vip/1,subscriber/3,premium/1;color=#DF3600;display-name=KaimTime;emotes=;flags=;id=8167e72c-564e-4552-bfda-f126716d252e;login=kaimtime;mod=0;msg-id=giftpaidupgrade;msg-param-sender-login=okayitskazzie;msg-param-sender-name=okayitsKAZZIE;room-id=11148817;subscriber=1;system-msg=KaimTime\sis\scontinuing\sthe\sGift\sSub\sthey\sgot\sfrom\sokayitsKAZZIE!;tmi-sent-ts=1572644380737;user-id=38413299;user-type= :tmi.twitch.tv USERNOTICE #pajlada`
Example `submysterygift` message: `@badge-info=subscriber/2;badges=subscriber/0,sub-gift-leader/2;color=#6C0EC6;display-name=jhmanar;emotes=;flags=;id=41de1c9e-336d-4d4a-8c2c-5af530c51780;login=jhmanar;mod=0;msg-id=submysterygift;msg-param-mass-gift-count=5;msg-param-origin-id=1a\s27\sb1\s27\s10\s96\s3d\sc9\se0\sa3\s3c\s78\s7f\s3b\sa3\sbc\sae\s1e\sba\sd0;msg-param-sender-count=10;msg-param-sub-plan=1000;room-id=70136772;subscriber=1;system-msg=jhmanar\sis\sgifting\s5\sTier\s1\sSubs\sto\sAtotheG_'s\scommunity!\sThey've\sgifted\sa\stotal\sof\s10\sin\sthe\schannel!;tmi-sent-ts=1572785895619;user-id=221478578;user-type= :tmi.twitch.tv USERNOTICE #pajlada

**Comment by pajlada** [comment]
@DatGuy1 How do you want the two events handled? Just silently ignored?
The `submysterygift` message will be followed by multiple giftsub messages which we handle
I can't think of a good way to handle `giftpaidupgrade` message, since it's not really an action but rather just a commitment

**Comment by DatGuy1** [comment]
@pajlada I'm not sure to be honest, I think giftpaidupgrade can be ignored. In my instance I made submysterygift thank the gifter in chat and a joke like "tag them for a free sub." Maybe if grant_points_on_sub is enabled then it could give them bonus points to encourage it.

**Comment by RAnders00** [comment]
Due to pajbot [being moved into maintenance mode](https://github.com/pajbot/pajbot/blob/master/README.md) I'm closing this feature request.
