### ISSUE TITLE
Make level needed to view/set specific module properties configurable

### ISSUE THREAD

**Issue by DatGuy1** [pajbot/pajbot#492]

**Comment by RAnders00** [comment]
First we need to solve https://github.com/pajbot/pajbot/issues/108

**Comment by alazymeme** [comment]
@DatGuy1 What specific modules were you looking at? Since the initial issue that needed to be solved has been solved.

**Comment by DatGuy1** [comment]
For example, moderation modules such as ASCII protection should probably require level 1000 while other more fun modules such as raffles and roulettes shouldn't

**Comment by alazymeme** [comment]
As per this comment: https://github.com/pajbot/pajbot/pull/892#issuecomment-633221708
This won't be implemented despite my efforts.

**Comment by RAnders00** [comment]
Due to pajbot [being moved into maintenance mode](https://github.com/pajbot/pajbot/blob/master/README.md) I'm closing this feature request.
