### ISSUE TITLE
Move all web requests to a separate ActionQueue

### ISSUE THREAD

**Issue by pajlada** [pajbot/pajbot#51]
From today's clown fiesta we can see that this is required in case the twitch API is down.
Consider adding backup IPs for the ConnectionManager, in case the request fails.

**Comment by pajlada** [comment]
There should be a class different ActionQueue class, which can start one thread for each "type" of event that's created.

**Comment by RAnders00** [comment]
We now use a thread pool, since https://github.com/pajbot/pajbot/commit/94de6f2918f48094c8c079a776c0e914c3dd8499
