### ISSUE TITLE
Messages in controlling channel should not be processed by moderation modules

### ISSUE THREAD

**Issue by ALazyMeme** [pajbot/pajbot#543]
I have the message length module on for pajbot (RoboWeest) and found that when running a command on streamelements in the controlling channel that is too long, streamelements will still get timed out despite the violation not happening in the bot's connected channel perse: https://i.nuuls.com/UPvED.gif

**Comment by alazymeme** [comment]
![image](https://user-images.githubusercontent.com/12804673/71433514-66ccdb80-272b-11ea-8e5a-fd1bd18f1d06.png)

**Comment by RAnders00** [comment]
Honestly this is such a low priority issue that it's not worth investing work into this, especially given that pajbot has been moved into maintenance mode. I'll close the issue for now. If somebody wants, they can of course send a PR to implement this regardless.
