### ISSUE TITLE
Offline/Online only banphrases

### ISSUE THREAD

**Issue by RAnders00** [pajbot/pajbot#546]
I think this should be straight-forward enough

**Comment by alazymeme** [comment]
Can we expand this to all moderation modules?

**Comment by RAnders00** [comment]
@alazymeme please create a separate issue since that would be quite "separate" in the current state of the bot's code

**Comment by RAnders00** [comment]
Due to pajbot [being moved into maintenance mode](https://github.com/pajbot/pajbot/blob/master/README.md) I'm closing this feature request.
