### ISSUE TITLE
Check Usernames for Banphrases

### ISSUE THREAD

**Issue by Felanbird** [pajbot/pajbot#562]
Adding the option to check usernames for banphrases, toggle-able option as preexisting banphrases could cause issues.

Fixes the issue that naughty names have to be manually banned but people who @ the name are timed out no problem 🏎 

streamelements example included 
![image](https://user-images.githubusercontent.com/41973452/66787296-1fb3a600-eeb1-11e9-8bd5-a0d2d424a393.png)

**Comment by alazymeme** [comment]
Would this ignore the colon? What if users use /me? Will it count as a single message?

**Comment by Felanbird** [comment]
> Would this ignore the colon? What if users use /me? Will it count as a single message?

This request is specific to the message sender username only, but usernames still exist as usernames even when the message is /me.

![image](https://user-images.githubusercontent.com/41973452/67538348-e3e8bf80-f6ac-11e9-8e00-5b6eaa3299ef.png)
![image](https://user-images.githubusercontent.com/41973452/67538440-0e3a7d00-f6ad-11e9-9b01-15de4ed64a63.png)
![image](https://user-images.githubusercontent.com/41973452/67538395-eea35480-f6ac-11e9-85ab-6094ebcf5c52.png)
![image](https://user-images.githubusercontent.com/41973452/67538414-fbc04380-f6ac-11e9-8c31-98b26275a6ab.png)

**Comment by alazymeme** [comment]
I've started running into issues recently with a certain user(s) in a certain channel. Would be very useful, could also take out some hardcoded shit:

https://github.com/pajbot/pajbot/blob/master/pajbot/bot.py#L774-L777
https://github.com/pajbot/pajbot/blob/master/pajbot/bot.py#L794-L801

**Comment by RAnders00** [comment]
Due to pajbot [being moved into maintenance mode](https://github.com/pajbot/pajbot/blob/master/README.md) I'm closing this feature request.
