### ISSUE TITLE
Add a bypass level for the link filter

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#563]
Most other modules have a bypass filter, would be cool to see one for links too.

Edited: removed useless shit

**Comment by RAnders00** [comment]
So you want to be able to set them all at once?

**Comment by alazymeme** [comment]
@RAnders00 No, set them on a per module basis

**Comment by RAnders00** [comment]
From what I see these modules already have a configurable bypass level:

- ascii
- maximum message length
- case checker
- paid timeout
- repetetive spam
- mass ping protection

and these modules are lacking them:

- banphrase
- link checker

Do i understand that correctly?

**Comment by alazymeme** [comment]
Yeah looks like it. I personally won't use the banphrase level bypass (I don't think anyone should), but if it's easy enough to integrate, then feel free to
