### ISSUE TITLE
Add a keyword module (possibly) integrated with commands

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#564]
If this is integrated with commands (like se), then we can use $(command:num_uses) for keywords BroBalt

**Comment by RAnders00** [comment]
I do believe @DatGuy1 did something similar in his bot, we can investiage if it's possible in a reasonable way without having to refactor the commands model

**Comment by alazymeme** [comment]
If we aren't integrating with commands, it'd be nice if there were a new variable with it "keyword:num_uses". This should be able to be called from a command (like !count test - test has been used X times) or from within the response of the keyword.

**Comment by RAnders00** [comment]
I assume you want to emulate the way nightbot does emote/keyword counters?

**Comment by alazymeme** [comment]
More towards the streamlabs/streamelements integration. Mostly because nightbot only allows keywords at the start of the line.
Phantombots keyword module might be a good reference, it's pretty good

**Comment by RAnders00** [comment]
Due to pajbot [being moved into maintenance mode](https://github.com/pajbot/pajbot/blob/master/README.md) I'm closing this feature request.
