### ISSUE TITLE
cool down for show emote/ modules auto activate and deactivate if stream is on or offline

### ISSUE THREAD

**Issue by Parrallax** [pajbot/pajbot#566]
please do thanks

**Comment by RAnders00** [comment]
So you want to automatically disable showemote and playsound when the stream ends, and enable them on stream start?

**Comment by Felanbird** [comment]
> So you want to automatically disable showemote and playsound when the stream ends, and enable them on stream start?

Even if that isn't the original request that could be extremely useful to have, the only issue is sometimes pajbot lags behind on "recognizing" the stream is offline but I think that is generated from pajbot having a window in which you can restart your stream and keep total uptime.

**Comment by RAnders00** [comment]
The time-to-offline is intentional to compensate for how the Twitch API caches stream status (we wait for quite a long time for things to stabilize). It's also useful for what @Felanbird said - a stream is not broken if there is only a short downtime.

**Comment by RAnders00** [comment]
@Parrallax Can you clarify again what feature you want to be added here? It's still unclear to me, and I'd like to help 😸

**Comment by Parrallax** [comment]
Forget the cool down for show emote, just being able to set modules to enable when the stream is offline and disable while the stream is online. Maybe also the ability to add alias to commands. Ex: !soundon to replace !module enable sound

**Comment by RAnders00** [comment]
Please continue discussion in #595, to avoid duplication
