### ISSUE TITLE
More Stats on the Userpage.

### ISSUE THREAD

**Issue by Parrallax** [pajbot/pajbot#569]
Past Time Outs.
Number of Times timed out
number of bans
recent links posted
account age
These are just thing i feel would be helpful. 
Maybe the ability to reset some data as well. Like resetting the number of times timed out

**Comment by RAnders00** [comment]
Just a few questions to clarify-

- Account age as in "first time seen by this pajbot" or "date account was created with Twitch"?
- Do you want to count timeouts and bans not from "paid timeout" and "paid ban" too?

**Comment by Parrallax** [comment]
No just normal vans and timeouts. Account date created with twitch

**Comment by RAnders00** [comment]
created separate issues
