### ISSUE TITLE
Rotate messages based on single timer

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#570]
Would like to see a timer system more like fossabot. Potentially a "global" option that disables individual timer timing and uses a global option instead (with a chat line integration).

**Comment by pajlada** [comment]
Please describe what this would look like compared to our current timer system

**Comment by alazymeme** [comment]
Main timer page when global timers are not enabled:
![image](https://user-images.githubusercontent.com/12804673/67188296-5e0c1080-f42f-11e9-94cd-7a7d9068f9a8.png)

Global timer options:
![image](https://user-images.githubusercontent.com/12804673/67188330-6f551d00-f42f-11e9-8f06-19c5b2f55cdb.png)

Main timer page when global timers are enabled (note the removal of the interval columns):
![image](https://user-images.githubusercontent.com/12804673/67190213-e50eb800-f432-11e9-9a88-edfee9b6ca15.png)

**Comment by RAnders00** [comment]
So this is like a single timer, except the messages are rotated, and not always the same.

**Comment by alazymeme** [comment]
Yes, it rotates through each timer on a single timing system

**Comment by RAnders00** [comment]
Due to pajbot [being moved into maintenance mode](https://github.com/pajbot/pajbot/blob/master/README.md) I'm closing this feature request.
