### ISSUE TITLE
Add the ability to auto disable/enable modules when live/offline

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#595]
Adding the ability to disable certain modules when one goes live and re-enable them when offline - but also the other way around. This can be applicable for most modules:

- Ascii protection; possibility of it being off when offline, but on when online
- Bingo games
- Duel
- 8-ball
etc, etc you get the point

**Comment by pajlada** [comment]
related to #566

**Comment by RAnders00** [comment]
Due to pajbot [being moved into maintenance mode](https://github.com/pajbot/pajbot/blob/master/README.md) I'm closing this feature request.
