### ISSUE TITLE
Add command to give every user points

### ISSUE THREAD

**Issue by RAnders00** [pajbot/pajbot#638]
Original request form https://github.com/Parrallax (#622)

> Perhaps the ability to add points to all users at once.

**Comment by alazymeme** [comment]
Does this include the ability to add points to individual users?

**Comment by RAnders00** [comment]
> Does this include the ability to add points to individual users?

You can already do that with !editpoints and !setpoints

**Comment by DatGuy1** [comment]
I have an existing implementation at https://github.com/admiralbullbot/bullbot/blob/master/pajbot/modules/viewerpoints.py

**Comment by RAnders00** [comment]
Due to pajbot [being moved into maintenance mode](https://github.com/pajbot/pajbot/blob/master/README.md) I'm closing this feature request.
