### ISSUE TITLE
Whisper user if they are ignored and trying to run a command

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#647]
If a user is ignored, they should be whispered (to notify them that they're ignored) when they try and use commands (with a cd of course)

**Comment by RAnders00** [comment]
We should discuss this first. I think we shouldn't do this, but I'm happy to discuss the pros/cons.

**Comment by alazymeme** [comment]
The idea is that they're notified that the command is not working due to them being ignored. Otherwise they wouldn't know they were ignored I guess? That's also the idea of the whisper cooldown.
