### ISSUE TITLE
Add existing chat badge options from ffz

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#650]

**Comment by RAnders00** [comment]
You mean we should display the ffz donator badge on the website next to the sub badge?

**Comment by RAnders00** [comment]
Or perhaps this? 
![image](https://user-images.githubusercontent.com/1629196/68164084-40c16100-ff5c-11e9-8759-2be776cd7d64.png)

**Comment by alazymeme** [comment]
@RAnders00 Second one, the ffz donator badge might be a nice edition also.

**Comment by alazymeme** [comment]
I'm an idiot, put this on the wrong github page FailFish
