### ISSUE TITLE
Dubtrack rooms don't work with spaces KKona

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#656]
Possible fix would be replacing spaces with `-` in the api url forsenKKona

**Comment by RAnders00** [comment]
Do you have an example room to test this

**Comment by alazymeme** [comment]
@RAnders00 https://www.dubtrack.fm/join/feelsdankman-clap

**Comment by RAnders00** [comment]
You‘re supposed to enter `feelsdankman-clap` in that case, did you do that?

**Comment by alazymeme** [comment]
No, and I wasn't aware of any instructions or anything that told me so. I entered as per the room name. I switched to that and it works now.

**Comment by RAnders00** [comment]
Ok, we can be more explicit about what to enter. I don't think dubtrack has an API endpoint that allows us to look up rooms by their display name.
