### ISSUE TITLE
Use parse_points_amount more frequently when applicable

### ISSUE THREAD

**Issue by DatGuy1** [pajbot/pajbot#658]
For example: Raffle, hsbet, pointlottery, edit/setpoints, etc.

**Comment by RAnders00** [comment]
I think for raffle and edit/setpoints, we need to develop an alternate version of points parser that doesn't allow allin phrases (what would !raffle all do?!)

**Comment by RAnders00** [comment]
Due to pajbot [being moved into maintenance mode](https://github.com/pajbot/pajbot/blob/master/README.md) I'm closing this feature request.
