### ISSUE TITLE
Version showing incorrectly on the dashboard

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#668]
I am using stable for both weest and another streamer, yet it is still showing `DEV`: https://i.nuuls.com/1Yv19.png

**Comment by RAnders00** [comment]
This is because you enabled dev = 1 in the config, which is not what the bot ships with if you do a fresh install

**Comment by alazymeme** [comment]
@RAnders00 Nope, dev is not enabled in the config. One of them I've never toggled the option and the other I have, but isn't currently on. Pls reopen the issue

**Comment by pajlada** [comment]
@alazymeme 

Works for me as expected on latest stable (v1.39).
I tried:

- `dev = 1` - version showed, as expected
- `dev = 0` - version didn't show, as expected
- no dev entry at all - version didn't show, as expected

Update to the latest stable and this is no longer an issue.

**Comment by RAnders00** [comment]
Yes, sorry, I should have been more explicit this was recently fixed. The fix is in release v1.39. Sorry @alazymeme for the confusion
