### ISSUE TITLE
Ability to add alias to sound names

### ISSUE THREAD

**Issue by Parrallax** [pajbot/pajbot#676]
For example we have a playsound named pepelaugh, but we would also like it to be activated if you type ohnonono. As a temporary work around we have multiple uploads of the same audio with different names but this would make things cleaner and alot easier

**Comment by RAnders00** [comment]
Due to pajbot [being moved into maintenance mode](https://github.com/pajbot/pajbot/blob/master/README.md) I'm closing this feature request.
