### ISSUE TITLE
Create $(tb:bot_domain) variable

### ISSUE THREAD

**Issue by Felanbird** [pajbot/pajbot#688]
I think this would be extremely useful as it would allow for virtually every single command that directs to the webui to be:
```
https://$(tb:broadcaster).$(tb:bot_domain)/*
```

**Comment by pajlada** [comment]
bot_domain should return the entire domain value as specified in the `[web]` section in the config file, so for pajbot it would be `paj.pajlada.se`, for snusbot it would be `forsen.tv`, for nymn it would be `nymn.pajbot.com`. so the commands would look like this: `https://$(tb:bot_domain)/...`

**Comment by alazymeme** [comment]
https://github.com/pajbot/pajbot/pull/693

**Comment by RAnders00** [comment]
Closed via #639
