### ISSUE TITLE
Add the ability to change your prefix

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#697]
a `prefix = !` option in the config file would be the easiest way to this

**Comment by alazymeme** [comment]
Am working on it: https://github.com/pajbot/pajbot/pull/705
@RAnders00 you mentioned the wrong issue 🤦‍♂️

**Comment by RAnders00** [comment]
I didn't link the wrong issue

![image](https://user-images.githubusercontent.com/1629196/70230229-314e5700-1758-11ea-9c9f-9ab263706323.png)

**Comment by alazymeme** [comment]
pajaShh
