### ISSUE TITLE
Alerts module

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#700]
Merge sub alerts and add more options to a broader alerts module

- [x] Raid alerts
- [x] New chatter alerts
- [x] Live alerts
- [ ] Streamlabs donation alerts
- [ ] Streamelements donation alerts
- [ ] Host alerts
- [ ] Bit cheering alerts
- [ ] Follow alerts
- [ ] Channel points alert

**Comment by RAnders00** [comment]
Due to pajbot [being moved into maintenance mode](https://github.com/pajbot/pajbot/blob/master/README.md) I'm closing this feature request. However you are of course free to submit pull requests to add these alert modules in the future.
