### ISSUE TITLE
The overlay

### ISSUE THREAD

**Issue by TroyDota** [pajbot/pajbot#703]
How to i add the overlay to obs so that i can see the emotes and hear the playsounds. Ive been looking for a while and i see that the clr socket has something to do with it but i have no idea how to add that into obs. Any help?

**Comment by pajlada** [comment]
https://your.domain.com/clr/overlay/12345 - replace your.domain.com with whatever domain you use to access the website. for me it's https://paj.pajlada.se/clr/overlay/12345

**Comment by TroyDota** [comment]
Hi, thanks for the fast reply, how do i find the <widget_id>? is it always 12345? Because when i do that i receive 404 not found. 
http://twitchbot.zapto.org/clr/overlay/12345 
its a temp domain

**Comment by alazymeme** [comment]
Looks like you haven't setup http redirect. Your CLR overlay can be found here: https://twitchbot.zapto.org/clr/overlay/12345

You can also follow this guide to setup the redirection: https://github.com/pajbot/pajbot/blob/master/install-docs/full-nginx-setup/README.md

**Comment by TroyDota** [comment]
Thanks it works now :)
