### ISSUE TITLE
Twitch Verification on bots

### ISSUE THREAD

**Issue by TroyDota** [pajbot/pajbot#707]
is there a guide on how to get the bot verified so it bypasses chat limits?

**Comment by alazymeme** [comment]
You can apply for bot verification here: https://dev.twitch.tv/limit-increase/

**Comment by TroyDota** [comment]
Thanks is there any advice on how to make a successful application?

**Comment by alazymeme** [comment]
This should be of assistance: https://gist.github.com/pajlada/be605ffaf9174b6463141bc5115c1228

**Comment by TroyDota** [comment]
Thanks super help :)

**Comment by TroyDota** [comment]
Do you know how long bot verification takes?

**Comment by TroyDota** [comment]
Do you know how long bot verification takes?

**Comment by RAnders00** [comment]
Takes a few days, up to a week roughly. If you come to twitch.tv/pajlada, and type `-botinfo the_bot_username` and a bot will tell you the verification status of your bot, in case you are interested

**Comment by TroyDota** [comment]
What are the chances of the bot being rejected? I followed the guide you linked perfectly.

**Comment by RAnders00** [comment]
Twitch will send you an email if they reject you, giving you the reason why. If you haven't gotten that email yet, they would still be working on it.

**Comment by TroyDota** [comment]
So i applied almost a week ago and still haven't received a response, is this normal?

**Comment by alazymeme** [comment]
I've put in a ticket to twitch about a year ago. Yet to receive a response. Be patient, they don't guarantee a time period iirc

**Comment by TroyDota** [comment]
Holy shit that's bad. Hopefully they can verify within the next week.

**Comment by pajlada** [comment]
> I've put in a ticket to twitch about a year ago. Yet to receive a response. Be patient, they don't guarantee a time period iirc

You should just apply again

**Comment by TroyDota** [comment]
It took a week.
