### ISSUE TITLE
Compensate points on bits or donations

### ISSUE THREAD

**Issue by TroyDota** [pajbot/pajbot#711]
Hi is there a way to give points to users who donate or cheer? Donations might be tricky as they are a third party(and idk forsenCD) thing but bits?

**Comment by alazymeme** [comment]
No, but this probably falls under my issue: https://github.com/pajbot/pajbot/issues/700

**Comment by TroyDota** [comment]
i mean there must be a way, streamelements does it?

**Comment by alazymeme** [comment]
No; pajbot does not yet recognize donations or cheers.

**Comment by TroyDota** [comment]
i did it.
