### ISSUE TITLE
I have edited the way clr works by dividing it into /overlay/<id>

### ISSUE THREAD

**Issue by TroyDota** [pajbot/pajbot#714]
I have created a version of the clr and websocket manager where you can send specific data to specific overlays. Is this something that is wanted i can make a pull for it.

**Comment by alazymeme** [comment]
Are you asking a question, or telling me something?

**Comment by TroyDota** [comment]
Asking if I should make a pull for this

**Comment by RAnders00** [comment]
Yes! We‘re always open to pull requests.

**Comment by TroyDota** [comment]
I will make the pull
