### ISSUE TITLE
Can you add aliases to commands that are from modules. 

### ISSUE THREAD

**Issue by TroyDota** [pajbot/pajbot#718]
Such as !songrequest -> !sr
when i type "!add alias !songrequest !sr"
the bot returns "That command cannot have aliases added to. "

**Comment by alazymeme** [comment]
No, currently the aliases are hardcoded. Also the pleblist module doesn't work.

**Comment by TroyDota** [comment]
I repaired it partially but how do u add alias on commands in the code?

**Comment by RAnders00** [comment]
In a module you can do for example:

```
def load_commands(self):
    self.commands["songrequest"] = ...
```

and then:

```
    self.commands["sr"] = self.commands["songrequest"]
```

The command will work under that alias, but it will not show up twice in the commands list on the website. There it will be shown by the name you give in the `Command( ... )` constructor.

**Comment by TroyDota** [comment]
Thanks :)
