### ISSUE TITLE
Improve the link filter regex

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#722]
Known incorrect timeouts:
- 1.40, etc
- *.mp4, etc

pajlada suggested finding a link module (similar to what was done with chatterino): https://github.com/Chatterino/chatterino2/commit/e12f76387a28b2d01ae5109ecd9e7b8413719f9a

**Comment by RAnders00** [comment]
yeah it's a really poor regex it considers the weirdest things to be links

**Comment by alazymeme** [comment]
I feel like this should have the bug feature on it, there's some shit it really shouldn't be timing out:
![image](https://user-images.githubusercontent.com/12804673/104836132-69cad900-58f7-11eb-8711-63002ca83168.png)
