### ISSUE TITLE
Implement level automation

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#723]
Possibly an option to automate levels.
If user is a `insert dropdown here - Moderator, VIP, Editor`, then give them level `input box`
Then also add an ignore list of a list of users to ignore

Something like that, I'm sure someone is more creative than me

**Comment by RAnders00** [comment]
Due to pajbot [being moved into maintenance mode](https://github.com/pajbot/pajbot/blob/master/README.md) I'm closing this feature request.
