### ISSUE TITLE
@value Generates a Twitter link on command page(s)

### ISSUE THREAD

**Issue by Felanbird** [pajbot/pajbot#725]
![image](https://user-images.githubusercontent.com/41973452/71048072-0676e200-210c-11ea-8147-b279b8740410.png)

![image](https://user-images.githubusercontent.com/41973452/71048204-869d4780-210c-11ea-8c7f-1fe8ebb5775a.png)

I'm unsure if this is intended but it seems unnecessary because @value does nothing in twitch chat so most twitter commands would have the direct twitter link anyway. 🍆

**Comment by alazymeme** [comment]
Are you sure this isn't an extension you have installed? I don't have the same issue:
![image](https://user-images.githubusercontent.com/12804673/71457099-21baaf00-27e8-11ea-85b4-6c32418f1dd6.png)

**Comment by Felanbird** [comment]
![image](https://user-images.githubusercontent.com/41973452/71481351-8b789000-27cb-11ea-89ac-030069cdfd68.png)

I don't think I have any extensions that run in incognito 🤔

**Comment by RAnders00** [comment]
I can replicate this. The link appears on the detail page (https://nymn.pajbot.com/commands/991-yonn2) but not on the commands page https://nymn.pajbot.com/commands if you select it from the list.

**Comment by alazymeme** [comment]
Ok can confirm this shows up for me: https://i.nuuls.com/eySeP.png
Seems really inconsistent, wasn't showing up for me the other day...

**Comment by Felanbird** [comment]
👍 confirmed fixed
