### ISSUE TITLE
Using the new channel point system to run commands using pajbot

### ISSUE THREAD

**Issue by Parrallax** [pajbot/pajbot#726]
I know for a fact this is widely needed and would probably increase the amount of people who use pajbot. I know streamers like Mizkif who use channel points to let people mute each other, and people like M0xyy who want to do that but are to lazy. I feel this is going to become a massively requested feature. Only a true 5 head will be able to harness its full power.

**Comment by alazymeme** [comment]
Like this? Am a little confused on what you're after...
![image](https://user-images.githubusercontent.com/12804673/71084363-cb92ae00-21e0-11ea-8754-e4a54fb083d0.png)

**Comment by RAnders00** [comment]
Reference msg when redeeming a custom reward with message "penis":

`@rm-received-ts=1576675463642;historical=1;badge-info=subscriber/10;badges=broadcaster/1,subscriber/0;color=#19E6E6;custom-reward-id=f70049dd-b608-4884-b3de-81383aabcf7b;display-name=randers;emotes=;flags=0-4:S.6;id=5c893576-635b-4f27-9965-ae3c1a799e21;mod=0;room-id=40286300;subscriber=1;tmi-sent-ts=1576675463512;turbo=0;user-id=40286300;user-type= :randers!randers@randers.tmi.twitch.tv PRIVMSG #randers :penis`

**Comment by TroyDota** [comment]
Pubsub has an event for this.

**Comment by RAnders00** [comment]
Due to pajbot [being moved into maintenance mode](https://github.com/pajbot/pajbot/blob/master/README.md) I'm closing this feature request.
