### ISSUE TITLE
Re-usage of capturing groups unsupported (regex)

### ISSUE THREAD

**Issue by Felanbird** [pajbot/pajbot#728]
https://regex101.com/r/tExtVb/1

![image](https://user-images.githubusercontent.com/41973452/71160646-f814ed00-2215-11ea-9985-9c6e46b7dd21.png)

**Comment by RAnders00** [comment]
If you switch to Python on regex101 you'll see why it does not compile with the standard python regex engine

**Comment by Felanbird** [comment]
You are indeed correct Randers 

![image](https://user-images.githubusercontent.com/41973452/71164956-f64f2780-221d-11ea-9401-f44354f67e9b.png)

Now to figure out if this can accept any of the characters in this set, but that is not a pajbot issue 😃
