### ISSUE TITLE
502 bad gateway error 

### ISSUE THREAD

**Issue by FedericoBuono** [pajbot/pajbot#731]
After all the steps of the install guide I go to the website to login but i get bad gateway error, how do I fix it? thanks

**Comment by RAnders00** [comment]
Check what the issue is using `journalctl -eu pajbot-web@streamer_name`. If you can, please check the log output for any errors or if you can't find anything post the latest logs for us to take a look.

**Comment by FedericoBuono** [comment]
I get
"Failed to determine user credentials: No such process
Failed at step USER spawning /opt/pajbot/venv/bin/uwsgi: No such process"; 
I didn't create the user pajbot because it didn't let me do administrator things like copying folder in root with the pajbot user, maybe is that the cause? I need to start over or else? Thank you for the help btw.

**Comment by FedericoBuono** [comment]
Ok now I fixed the error but the website always has 502 error and I get this,
[2019-12-23 16:16:59,008] [DEBUG  ] Cache Miss: api:twitch:helix:user:by-id:xxxxxxx
Dec 23 16:16:59 uwsgi[687]: [2019-12-23 16:16:59,012] [DEBUG  ] Successfully loaded OAuth token from storage
Dec 23 16:16:59 uwsgi[687]: [2019-12-23 16:16:59,419] [WARNING] Unable to download subscriber badge: Channel(xxxxxx) does not have any subscriber badges
Dec 23 16:17:00 uwsgi[687]: [2019-12-23 16:17:00,166] [ERROR  ] add_handler No handler for on_message found.
Dec 23 16:17:00  uwsgi[687]: [2019-12-23 16:17:00,290] [ERROR  ] add_handler No handler for on_pubmsg found.
Dec 23 16:17:00  uwsgi[687]: [2019-12-23 16:17:00,332] [ERROR  ] add_handler No handler for on_message found.
Dec 23 16:17:00  uwsgi[687]: [2019-12-23 16:17:00,332] [ERROR  ] add_handler No handler for on_commit found.
Dec 23 16:17:00 uwsgi[687]: [2019-12-23 16:17:00,390] [ERROR  ] add_handler No handler for on_usernotice found.
Dec 23 16:17:00  uwsgi[687]: WSGI app 0 (mountpoint='') ready in 12 seconds on interpreter 0x55be2e33b870 pid: 687 (default app)
Dec 23 16:17:00  uwsgi[687]: *** uWSGI is running in multiple interpreter mode ***
Dec 23 16:17:00  uwsgi[687]: spawned uWSGI master process (pid: 687)
Dec 23 16:17:00  uwsgi[687]: spawned uWSGI worker 1 (pid: 888, cores: 1)

**Comment by RAnders00** [comment]
The errors you posted are all not fatal to the operation, they are all just warnings. Are you still getting error 502 when accessing the website?

**Comment by FedericoBuono** [comment]
yes, I also checked on dns checker if my domain and server resolve and they do. Btw I'm not using a .com domain but a .ga domain that I got on freenom maybe that is the issue or some parameters in the nginx config but I checked the syntax with sudo nginx -t and it doesn't show any errors. If I typed something wrong in the config.ini file it should appear some kind of error right?

**Comment by RAnders00** [comment]
You can also check `/var/log/nginx/error.log` for any errors nginx had when trying to connect to the upstream application server. Feel free to post log snippets if you can't immediately figure out what's going on.

**Comment by FedericoBuono** [comment]
Ok I was able to fix it thanks to your tip to check nginx log ( it sad couldn't find the websocket because I changed, in the nginx .conf file, streamer_name with my name) and now the website works but I don't see the bot in my twitch chat, I restarted the bot and also the server but I don't see in the users list of my twitch chat.

**Comment by RAnders00** [comment]
The log output of the bot process can help in that case: `sudo journalctl -eu pajbot@streamer_name`

**Comment by FedericoBuono** [comment]
I get this
 [2019-12-23 20:09:08,188] [DEBUG  ] Successfully loaded OAuth token from storage
Dec 23 20:09:08  python3[1056]: [2019-12-23 20:09:08,450] [INFO   ] Successfully updated 5 chatters
Dec 23 20:09:08  python3[1056]: [2019-12-23 20:09:08,451] [DEBUG  ] ChattersRefreshModule::_update_chatters function took 998.497 ms
Dec 23 20:11:23  python3[1056]: [2019-12-23 20:11:23,741] [DEBUG  ] UserRanksRefreshManager::_refresh function took 31.207 ms
Dec 23 20:16:51  python3[1056]: [2019-12-23 20:16:51,766] [DEBUG  ] UserRanksRefreshManager::_refresh function took 24.015 ms
Dec 23 20:19:07  python3[1056]: [2019-12-23 20:19:07,469] [WARNING] Cannot fetch subscribers because no streamer token is present. Have the streamer log in with the /streamer_login web route to enable subscriber fetch.
Dec 23 20:19:07  python3[1056]: [2019-12-23 20:19:07,470] [DEBUG  ] SubscriberFetchModule::_update_subscribers function took 1.756 ms
Dec 23 20:19:07  python3[1056]: [2019-12-23 20:19:07,611] [ERROR  ] Logging an uncaught exception (main thread)
Dec 23 20:19:07  python3[1056]: Traceback (most recent call last):
Dec 23 20:19:07  python3[1056]:   File "/opt/pajbot/pajbot/eventloop.py", line 19, in run
Dec 23 20:19:07  python3[1056]:     command.target()
Dec 23 20:19:07  python3[1056]:   File "/opt/pajbot/pajbot/bot.py", line 524, in <lambda>
Dec 23 20:19:07  python3[1056]:     self.reactor.scheduler.execute_after(delay, lambda: function(*args, **kwargs))
Dec 23 20:19:07  python3[1056]:   File "/opt/pajbot/pajbot/modules/moderators_refresh.py", line 37, in _update_moderators
Dec 23 20:19:07  python3[1056]:     self.bot.privmsg("/mods")
Dec 23 20:19:07  python3[1056]:   File "/opt/pajbot/pajbot/bot.py", line 485, in privmsg
Dec 23 20:19:07  python3[1056]:     return self.irc.privmsg(message, channel, increase_message=increase_message)
Dec 23 20:19:07  python3[1056]:   File "/opt/pajbot/pajbot/managers/irc.py", line 44, in privmsg
Dec 23 20:19:07  python3[1056]:     self.connection_manager.privmsg(channel, message, increase_message=increase_message)
Dec 23 20:19:07  python3[1056]:   File "/opt/pajbot/pajbot/managers/connection.py", line 125, in privmsg
Dec 23 20:19:07  python3[1056]:     conn.privmsg(channel, message)
Dec 23 20:19:07  python3[1056]:   File "/opt/pajbot/venv/lib/python3.7/site-packages/irc/client.py", line 560, in privmsg
Dec 23 20:19:07  python3[1056]:     self.send_items('PRIVMSG', target, ':' + text)
Dec 23 20:19:07  python3[1056]:   File "/opt/pajbot/venv/lib/python3.7/site-packages/irc/client.py", line 591, in send_items
Dec 23 20:19:07  python3[1056]:     self.send_raw(' '.join(filter(None, items)))
Dec 23 20:19:07  python3[1056]:   File "/opt/pajbot/pajbot/managers/connection.py", line 40, in send_raw
Dec 23 20:19:07  python3[1056]:     raise ServerNotConnectedError("Not connected.")
Dec 23 20:19:07  python3[1056]: irc.client.ServerNotConnectedError: Not connected.
Dec 23 20:19:08  python3[1056]: [2019-12-23 20:19:08,348] [INFO   ] Successfully updated 5 chatters
Dec 23 20:19:08  python3[1056]: [2019-12-23 20:19:08,349] [DEBUG  ] ChattersRefreshModule::_update_chatters function took 896.430 ms

I don't understand why says server not connected, maybe I need to change in the streamer_name.ini the name of the websocket to streamer_name?

**Comment by RAnders00** [comment]
The "not connected" error is an error about the bot not  being connected to IRC. If you try restarting it `sudo systemctl restart pajbot@streamer_name` and checking for any errors during startup of the bot?

**Comment by FedericoBuono** [comment]
I get this 
Stopped pajbot for streamer_name.
Dec 23 20:30:13 systemd[1]: Started pajbot for streamer_name.
Dec 23 20:30:16 python3[2823]: [2019-12-23 20:30:16,792] [DEBUG  ] Loaded config
Dec 23 20:30:16 python3[2823]: [2019-12-23 20:30:16,794] [DEBUG  ] Cache Miss: api:twitch:helix:user:by-login:streambot
Dec 23 20:30:16 python3[2823]: [2019-12-23 20:30:16,797] [DEBUG  ] Successfully loaded OAuth token from storage
Dec 23 20:30:17 python3[2823]: [2019-12-23 20:30:17,097] [INFO   ] PostgreSQL Server notice: NOTICE:  relation "schema_version" already exists, skipping
Dec 23 20:30:17 python3[2823]: [2019-12-23 20:30:17,098] [DEBUG  ] migrate db: current revision ID is 11
Dec 23 20:30:17 python3[2823]: [2019-12-23 20:30:17,098] [DEBUG  ] migrate db: 0 revisions to run
Dec 23 20:30:17 python3[2823]: [2019-12-23 20:30:17,109] [DEBUG  ] migrate redis: current revision ID is 1
Dec 23 20:30:17 python3[2823]: [2019-12-23 20:30:17,110] [DEBUG  ] migrate redis: 0 revisions to run
Dec 23 20:30:17 python3[2823]: [2019-12-23 20:30:17,670] [INFO   ] Loaded 0 timers (0 online/0 offline)
Dec 23 20:30:17 python3[2823]: [2019-12-23 20:30:17,687] [DEBUG  ] Cache Miss: api:bttv:global-emotes
Dec 23 20:30:17 python3[2823]: [2019-12-23 20:30:17,703] [DEBUG  ] Cache Miss: api:ffz:global-emotes
Dec 23 20:30:17 python3[2823]: [2019-12-23 20:30:17,713] [DEBUG  ] Cache Miss: api:twitch:kraken:v5:global-emotes
Dec 23 20:30:18 python3[2823]: [2019-12-23 20:30:18,262] [DEBUG  ] Cache Miss: api:twitch:legacy:channel-emotes:streamname
Dec 23 20:30:18 python3[2823]: [2019-12-23 20:30:18,514] [ERROR  ] Logging an uncaught exception (ActionQueue)
Dec 23 20:30:18 python3[2823]: Traceback (most recent call last):
Dec 23 20:30:18 python3[2823]:   File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
Dec 23 20:30:18 python3[2823]:     result = self.fn(*self.args, **self.kwargs)
Dec 23 20:30:18 python3[2823]:   File "/opt/pajbot/pajbot/managers/emote.py", line 66, in load_all
Dec 23 20:30:18 python3[2823]:     self.load_channel_emotes()
Dec 23 20:30:18 python3[2823]:   File "/opt/pajbot/pajbot/managers/emote.py", line 99, in load_channel_emotes
Dec 23 20:30:18 python3[2823]:     streamer
Dec 23 20:30:18 python3[2823]:   File "/opt/pajbot/pajbot/apiwrappers/twitch/legacy.py", line 67, in get_channel_emotes
Dec 23 20:30:18 python3[2823]:     force_fetch=force_fetch,
Dec 23 20:30:18 python3[2823]:   File "/opt/pajbot/pajbot/apiwrappers/response_cache.py", line 98, in cache_fetch_fn
Dec 23 20:30:18 python3[2823]:     fetch_result = fetch_fn()
Dec 23 20:30:18 python3[2823]:   File "/opt/pajbot/pajbot/apiwrappers/twitch/legacy.py", line 64, in <lambda>
Dec 23 20:30:18 python3[2823]:     fetch_fn=lambda: self.fetch_channel_emotes(channel_name),
Dec 23 20:30:18 python3[2823]:   File "/opt/pajbot/pajbot/apiwrappers/twitch/legacy.py", line 59, in fetch_channel_emotes
Dec 23 20:30:18 python3[2823]:     raise e
Dec 23 20:30:18 python3[2823]:   File "/opt/pajbot/pajbot/apiwrappers/twitch/legacy.py", line 30, in fetch_channel_emotes
Dec 23 20:30:18 python3[2823]:     resp = self.get(["channels", channel_name, "product"])
Dec 23 20:30:18 python3[2823]:   File "/opt/pajbot/pajbot/apiwrappers/twitch/base.py", line 64, in get
Dec 23 20:30:18 python3[2823]:     return self.request("GET", endpoint, params, headers, authorization).json()
Dec 23 20:30:18 python3[2823]:   File "/opt/pajbot/pajbot/apiwrappers/twitch/base.py", line 61, in request
Dec 23 20:30:18 python3[2823]:     raise e
Dec 23 20:30:18 python3[2823]:   File "/opt/pajbot/pajbot/apiwrappers/twitch/base.py", line 46, in request
Dec 23 20:30:18 python3[2823]:     return super().request(method, endpoint, params, headers, json)
Dec 23 20:30:18 python3[2823]:   File "/opt/pajbot/pajbot/apiwrappers/base.py", line 81, in request
Dec 23 20:30:18 python3[2823]:     response.raise_for_status()
Dec 23 20:30:18 python3[2823]:   File "/opt/pajbot/venv/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
Dec 23 20:30:18 python3[2823]:     raise HTTPError(http_error_msg, response=self)
Dec 23 20:30:18  python3[2823]: requests.exceptions.HTTPError: 410 Client Error: Gone for url: https://api.twitch.tv/api/channels/streamname/product
Dec 23 20:30:19  python3[2823]: [2019-12-23 20:30:19,169] [ERROR  ] babyrage
Dec 23 20:30:19  python3[2823]: Traceback (most recent call last):
Dec 23 20:30:19  python3[2823]:   File "/opt/pajbot/pajbot/managers/connection.py", line 82, in start
Dec 23 20:30:19 python3[2823]:     self.make_new_connection()
Dec 23 20:30:19  python3[2823]:   File "/opt/pajbot/pajbot/managers/connection.py", line 107, in make_new_connection
Dec 23 20:30:19  python3[2823]:     ip, port, self.bot.nickname, self.bot.password, self.bot.nickname, connect_factory=ssl_factory
Dec 23 20:30:19  python3[2823]:   File "/opt/pajbot/pajbot/bot.py", line 274, in password
Dec 23 20:30:19  python3[2823]:     return f"oauth:{self.bot_token_manager.token.access_token}"
Dec 23 20:30:19 python3[2823]:   File "/opt/pajbot/pajbot/apiwrappers/authentication/token_manager.py", line 75, in token
Dec 23 20:30:19  python3[2823]:     self.initialize()
Dec 23 20:30:19 python3[2823]:   File "/opt/pajbot/pajbot/apiwrappers/authentication/token_manager.py", line 67, in initialize
Dec 23 20:30:19  python3[2823]:     self._token = self.fetch_new()
Dec 23 20:30:19  python3[2823]:   File "/opt/pajbot/pajbot/apiwrappers/authentication/token_manager.py", line 106, in fetch_new
Dec 23 20:30:19  python3[2823]:     raise NoTokenError(f"No authentication token found for user {self.username} ({self.user_id}) in redis")
Dec 23 20:30:19  python3[2823]: pajbot.apiwrappers.authentication.token_manager.NoTokenError: No authentication token found for user streamname (64139307) in redis

**Comment by RAnders00** [comment]
Yes, this means you still need to complete this part from the guide: https://github.com/pajbot/pajbot/tree/master/install-docs#authenticate-the-bot

**Comment by FedericoBuono** [comment]
I get the same error, I also checked on Twitch connections and the bot appears there, maybe I need to change the twitch secret, also when I go to the login page it makes me authorize the login every time I access it. It should automatically login or it is normal that asks the authorization every time I go to the bot_login page?

**Comment by RAnders00** [comment]
Just some things to check because I can't immediately pin down the issue from the logs:

- Make sure nickname, streamer, etc. are lowercase in your `streamer_name.ini` config file
- You need to log in with the bot account you configured in the config (`nickname`) obviously.

Remember to restart `pajbot-web` if you end up making any changes to your config.

**Comment by RAnders00** [comment]
You can also check the logs of `pajbot-web`, if the login with the bot account succeeded you should see `Successfully updated bot token in redis` in the output.

**Comment by FedericoBuono** [comment]
I fixed it basically I forgot that i had to do a separate account for the bot and when I changed everything it appeared on the chat, thank you so much without your help I could not made it happy holidays :D
