### ISSUE TITLE
Move all secrets to the web ui - only accessible by certain users

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#732]

**Comment by pajlada** [comment]
I would rather have the riot api key (and other "secrets") using some sort of secret setting, only viewable and settable by certain users.
Dependant on #492

**Comment by alazymeme** [comment]
As in an option on the website? I feel like this wouldn't be a good idea. What if someone accidentally shows them on stream when configuring their bot?

**Comment by pajlada** [comment]
That's the idea of the new setting options, one of the settings would be a text field that emulates a password field.

**Comment by alazymeme** [comment]
Found the relevant line from the twitter html file: `{%- if not session.user.level or session.user.level >= 1000 %}`

**Comment by RAnders00** [comment]
Due to pajbot [being moved into maintenance mode](https://github.com/pajbot/pajbot/blob/master/README.md) I'm closing this feature request.
