### ISSUE TITLE
"emote timeout" whitelist

### ISSUE THREAD

**Issue by Felanbird** [pajbot/pajbot#734]
![image](https://user-images.githubusercontent.com/41973452/71417133-bcbd5880-2631-11ea-93d1-d038b1249340.png)

whitelist options for the "emote timeout" module 🥒

**Comment by RAnders00** [comment]
Due to pajbot [being moved into maintenance mode](https://github.com/pajbot/pajbot/blob/master/README.md) I'm closing this feature request.
