### ISSUE TITLE
Catch duel module's RuntimeError

### ISSUE THREAD

**Issue by DatGuy1** [pajbot/pajbot#737]
I'm not sure if it's possible to be fixed, but at the very least it shouldn't throw an ugly error.

https://i.nuuls.com/T9XsD.png

**Comment by RAnders00** [comment]
the image link doesn't work anymore, unless you still have the original image I will have to close this

Please in the future remember to post stack traces as text or at the very least use GitHub's uploading image feature if you for some reason can't copy the text.
