### ISSUE TITLE
Add a --me variable for creating commands with a .me response

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#743]

**Comment by RAnders00** [comment]
Just type /me at the start of the command response, I think that's what the "Me" selector does on the website anyways

**Comment by alazymeme** [comment]
Yes, but it makes it look better on the commands page if you use the me response

**Comment by alazymeme** [comment]
Not sure what happened, but it appears the same on the commands page either way you do it. Can't remember where I saw this.
