### ISSUE TITLE
Using the --reply variable should set "Whisperable" to "Yes"

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#744]
![image](https://user-images.githubusercontent.com/12804673/72055450-93c9e280-3316-11ea-9939-9c5296d987fa.png)

![image](https://user-images.githubusercontent.com/12804673/72055465-9b898700-3316-11ea-9b12-574898a7d4bf.png)

**Comment by RAnders00** [comment]
In this case the whisper only works for you because you are a high user level on the bot and you are able to bypass the "Whisperable" property using your level. Other users will not be able to use this command via whispers

**Comment by alazymeme** [comment]
But is the reply command response not meant to reply to that method of communication?

**Comment by pajlada** [comment]
Reply is meant to reply to you in whatever way you triggered the command, yes.
However, reply does not necessarily mean that the command can be triggered by e.g. being whispered. Having these two options make it possible to only allow privileged users to run certain commands through whispers and get the response through whispers (e.g. the !logs command).

**Comment by alazymeme** [comment]
@pajlada So you require whisperable and reply to be set in order for the reply function to properly fulfill it's function?

**Comment by pajlada** [comment]
@alazymeme No, the function of the "reply" return type is still relevant for commands that can be invoked by moderators through whispers and have them reply in a whisper, even if normal users aren't allowed to whisper the command.
