### ISSUE TITLE
API for the bot stats

### ISSUE THREAD

**Issue by Burday** [pajbot/pajbot#755]
Hello Pageloader, I was wondering if you plan to make an API or just allow people to add ".json" to usernames on https://forsen.tv/user/<username> so we can easily get stats on things like messages sent and how many points we have.

**Comment by RAnders00** [comment]
There is already an API for this: `https://forsen.tv/api/v1/users/:login` and `https://forsen.tv/api/v1/users/by-id/:id` Where `:login` is a Twitch login name and `:id` is a Twitch user ID.

**Comment by Burday** [comment]
Oh, didn't know. Sorry. Thanks for the heads up
