### ISSUE TITLE
Add some default commands

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#757]
Would be nice to have some default commands

Eg
!game
!title

The idea is to add them to the basic commands module and make them toggleable

**Comment by TroyDota** [comment]
Like with nightbot? Perhaps have it when mods type `!game Dota 2` it changes the game, to Dota 2 and then also do `!game` which tells us what the game is.

**Comment by alazymeme** [comment]
@TroyDota No, that is already a default command. `!setgame` and `!settitle`. I'm talking default commands like `!points`, `!game`, `!title`, `!timeonline/offline` or `!watchtime`, `!commands`, `!ping`, etc

**Comment by alazymeme** [comment]
The commands in the guide are fine, will keep it to that
