### ISSUE TITLE
Fix urlfetch censoring on the website for nested substitution cases

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#763]
Make it so that http/https isn't required. Currently the urlfetch parameter isn't masked because it doesn't contain http/https: https://pajlada.pajbot.com/commands/1057-shuffle
![image](https://user-images.githubusercontent.com/12804673/72679810-8d015380-3afe-11ea-81d8-24590130103b.png)

**Comment by RAnders00** [comment]
The command actually contains `https://`:

`17:02 pajbot -> randers: id=1057, level=100, type=message, cost=0, cd_all=5, cd_user=15, mod_only=False, response=$(urlfetch https://shitty-customapis-si5z3vz69j2s.runkit.sh/random/shuffle?input=$(args:0|urlencode))`

The `$(args:0|urlencode)` does not match the urlfetch regex. I suspect it normally (in the bot) gets replaced before urlfetch matches are performed.

**Comment by RAnders00** [comment]
I think this is more of a feature request rather than a bug. For this reason due to pajbot [being moved into maintenance mode](https://github.com/pajbot/pajbot/blob/master/README.md) I'm closing this.

**Comment by alazymeme** [comment]
I disagree, this is a bug. It's an implemented feature that isn't working.

**Comment by RAnders00** [comment]
Unless you‘re already working on a fix because this is arguably not a major breakage in any way I didnt find it to be worth to keep the open bug lingering around. I‘ll assign you and reopen

**Comment by alazymeme** [comment]
This will be closed at some point anyway. Might as well close it now.
