### ISSUE TITLE
Pnsl module enhancements

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#772]
Few things:
- If `verified = 1` is not found in the config, the max chunks should be that of twitch's rate limits for a regular mod (100 I think?)
- If `verified = 1` is found in the config, then the max chunks should be that of twitch's rate limits for a verified bot (7500 I think?)

**Comment by pajlada** [comment]
There's currently no way to do that check programmatically, because setting parameters are initialized statically. I don't think it's worth to implement just for this check. Having the max chunk be that high won't make sense because pajbot is slow anyway

**Comment by alazymeme** [comment]
@pajlada I usually set my max chunks to 7000 - can we at least raise the limit to 7500?
