### ISSUE TITLE
Setting the max message length to 0 should disable is

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#774]
Eg if I want to set the offline max message length to 0, it should disable it on pajbot and would therefore rely on the limits of twitch irc

**Comment by RAnders00** [comment]
Just set it to 500 to effectively disable it

**Comment by alazymeme** [comment]
What makes even less sense is why it has the option to set it to 1000...

**Comment by pajlada** [comment]
As RAnders00 said, just set it to an unreachable number and it'll effectively be disabled.


> 
> 
> What makes even less sense is why it has the option to set it to 1000...

There was a point where either the message limit was 1000, or I was under the belief that it was 1000. That's why the limit is like that.
