### ISSUE TITLE
Update the web interface

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#788]
The version of semantic ui currently being run is very old. Would be cool if either:

1. It was updated
Or
2. It was completely redone

Of course the former would be easier, but it depends how the contributor wishes to do it.

**Comment by pajlada** [comment]
no, not going to happen. maybe at some point we start making more APIs for all functionality and add stuff to the pajbot2 dashboard or something, but I don't want to rewrite 50% of the code base
