### ISSUE TITLE
Modules are not sorted correctly by default

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#793]
![image](https://user-images.githubusercontent.com/12804673/75101344-f3f6b880-5626-11ea-901b-19e9e9fe50bc.png)

**Comment by alazymeme** [comment]
![image](https://user-images.githubusercontent.com/12804673/75101352-1688d180-5627-11ea-94e1-a0c8a503d67d.png)

**Comment by pajlada** [comment]
The "Module" header is marked as sorted, while this list is in fact not sorted at all.
Options:

- make sure the "Module" header doesn't indicate that it's sorted in the beginning
- Properly sort by module on load
