### ISSUE TITLE
Utilize Verified Bot status for "stats" page (line farming)

### ISSUE THREAD

**Issue by Felanbird** [pajbot/pajbot#798]
Would fix #797 and set a fair precedent for any other bots possibly clogging up stats.

**Comment by RAnders00** [comment]
are you suggesting we fetch verified bot status of every single user

**Comment by alazymeme** [comment]
Yes I think this is a good idea. Maybe store the bot status on the profile page or something.

**Comment by RAnders00** [comment]
Fetching the bot status is an API call with the Twitch API that we would have to do for each user separately, which is extremely costly.

**Comment by Felanbird** [comment]
Secondary idea's for @RAnders00 's argument

> Small subset of users, Fossabot, Streamelements, Nightbot, Moobot, etc.

> Query only the top 10 chatters for verified bot status, 

(if you have more than 10 verified bots clogging your stats, you are sadly out of luck for a fix 😢)

**Comment by pajlada** [comment]
I'm fine with the "Poll top 10 users for their verified bot status every now and then" solution to this problem

**Comment by RAnders00** [comment]
Better algorithm would be to fetch verified bot status beginning from the top until there are no verified bots in the top 5 left.

**Comment by RAnders00** [comment]
Also fetching bot verification status is on a undocumented endpoint of the v5 API so not exactly ideal but it can be done

**Comment by alazymeme** [comment]
Since this is not necessarily an issue only to do with line farming, could we branch this out as a global feature? Points, etc

**Comment by RAnders00** [comment]
Due to pajbot [being moved into maintenance mode](https://github.com/pajbot/pajbot/blob/master/README.md) I'm closing this feature request.
