### ISSUE TITLE
Global Playsound cooldown not working

### ISSUE THREAD

**Issue by gempir** [pajbot/pajbot#802]
In Nymns chat we have global cooldown configured to 90s

![image](https://user-images.githubusercontent.com/9765622/75631995-08731c00-5bf8-11ea-8df3-dbe11dfcd8ed.png)

But playsounds are playable much more often somehow.

**Comment by RAnders00** [comment]
There's some serious multi threading noobery revolving the playsounds module, so I wouldn't be surprised.

**Comment by RAnders00** [comment]
See also https://github.com/pajbot/pajbot/issues/399, could be related

**Comment by RAnders00** [comment]
@gempir are you sure it's not some moderator using the admin panel and "test sound on stream"? That button has no cooldown.

**Comment by gempir** [comment]
@RAnders00 Could be. I don't know

**Comment by RAnders00** [comment]
feel free to open this again if it ever happens again
