### ISSUE TITLE
Changing reply type of a command doesn't work

### ISSUE THREAD

**Issue by gempir** [pajbot/pajbot#803]
When trying to change the Reply Type of a command via the web interface it will not apply the changes. 

Example. Change command reply-type from Say to Reply. Test it in chat (won't work)

After a restart of the bot the reply type resests itself again in the web interface. (Tested once, maybe test that again)

**Comment by gempir** [comment]
nevermind

**Comment by alazymeme** [comment]
Good one
![image](https://user-images.githubusercontent.com/12804673/75636547-4fe6c000-5c6b-11ea-8dee-b5c4bbffd011.png)
