### ISSUE TITLE
Add an emotestreak_string variable to sub alerts

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#806]
Adding a variable that allows an emote name to be input. That many emotes are spammed as per either:

- how many months in a row
or
- how many months total

Of course this would be limited to a certain amount of emotes. Perhaps give an option as to how many max emotes the streamer wants to use

**Comment by RAnders00** [comment]
Due to pajbot [being moved into maintenance mode](https://github.com/pajbot/pajbot/blob/master/README.md) I'm closing this feature request.
