### ISSUE TITLE
Use channel points for playsounds, showemote, paid timeouts

### ISSUE THREAD

**Issue by Parrallax** [pajbot/pajbot#807]
Ides for what channel points could be used for.
Playsounds (redeem and type the sound name, eliminates the need for typing the command)
ShowEmote (Same as above)
Paid and Unpaid timeouts

**Comment by RAnders00** [comment]
Due to pajbot [being moved into maintenance mode](https://github.com/pajbot/pajbot/blob/master/README.md) I'm closing this feature request.
