### ISSUE TITLE
Bugged subemotes api?

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#809]
It's been around 24 hours since weest changed some of his subemotes. I've reloaded subemotes a few times, but it just doesn't seem to be working. As seen in the below screenshot, the "missing emotes" are ones that weest doesn't have anymore:

![image](https://user-images.githubusercontent.com/12804673/76692773-b07fef00-66a6-11ea-858c-1e38bf93ef51.png)

**Comment by RAnders00** [comment]
Then it's an issue with twitchemotes.com, which we rely on: https://twitchemotes.com/channels/130924701

As you can see on their website, they are just out of date, and the website still shows the same state of data your bot has. (e.g. it still has weestCLOWN, etc.)

**Comment by alazymeme** [comment]
@RAnders00 Is there a way to force refresh the emotes?

**Comment by alazymeme** [comment]
Looks like they might be having issues. Their API is meant to refresh every 30min:
```API data is currently updated every 30 minutes (the same as the main site) so polling any more often will not be beneficial. Browser applications or extensions should not send requests to the API directly. You must cache on a your own backend server and then distribute to clients.```

**Comment by alazymeme** [comment]
Closed because its a twitchemotes api issue KKaper
