### ISSUE TITLE
Incorrect error message for blocked titles

### ISSUE THREAD

**Issue by ALazyMeme** [pajbot/pajbot#815]
The term "cunt" seems to be blocked by twitch's moderation policy. As a result you can't change the title to that. The bot appears to spit an incorrect error as a result:
![image](https://user-images.githubusercontent.com/12804673/77632998-85e14080-6f9a-11ea-8b97-40705a7daed4.png)

**Comment by RAnders00** [comment]
Relevant code section:
https://github.com/pajbot/pajbot/blob/05d30923f7cb5dc45076fb02c266f62f0bc21a52/pajbot/modules/basic/stream_update.py#L63-L65

**Comment by alazymeme** [comment]
supinic helped me figure out that 403 error code is actually used for if the user doesn't have channel editor AND if it doesn't pass the moderation filter. The message field might have to be parsed in order to fix this.

**Comment by alazymeme** [comment]
supinic helped me figure out that 403 error code is actually used for if the user doesn't have channel editor AND if it doesn't pass the moderation filter. The message field might have to be parsed in order to fix this.

**Comment by RAnders00** [comment]
Error on missing auth:

```json
{
  "error": "Forbidden",
  "status": 403,
  "message": "{\"status\":403,\"message\":\"Fail to auth.\",\"error\":\"Forbidden\",\"error_code\":\"error_auth_failure\"}"
}
```

Error with blocked term:

```json
{
  "error": "Forbidden",
  "status": 403,
  "message": "{\"status\":403,\"message\":\"Status contains banned words.\",\"error\":\"Forbidden\",\"error_code\":\"status_use_banned_words\"}"
}
```

**Comment by alazymeme** [comment]
This is still applicable with the new helix changes btw
