### ISSUE TITLE
bitemotes command

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#819]
Add bitemotes to the emotes module

**Comment by RAnders00** [comment]
I'm afraid there is no public API for this information, not from twitchemotes.com either, so this is blocked until a public API is released by twitch or some third party.

**Comment by alazymeme** [comment]
@Leppunen Didn't you figure out something today about this? fdm
Just can't remember what it was

**Comment by alazymeme** [comment]
@RAnders00 leppunen did a thing: https://api.ivr.fi/twitch/bitemotes/alazymeme
Something exists fdm

**Comment by RAnders00** [comment]
His API also queries GraphQL just for the reference

If @Leppunen wants to stabilize his API and promises not to change it then we can build against it.

**Comment by Leppunen** [comment]
I'm still working on the final output format of that endpoint. And since GraphQL is involved it can break or change at any time so i can't promise that it is completely stable all time.

**Comment by alazymeme** [comment]
Closing because this is not practical

**Comment by RAnders00** [comment]
Do you no longer want/need this?

**Comment by alazymeme** [comment]
> Do you no longer want/need this? I think this is doable.

Yes, but it's not practical. You'd have to spend a fuck load of money on bits on your bot account for this to work (unless twitch introduces a permanent sub thing for bots). I don't see many people using it tbh

**Comment by RAnders00** [comment]
True, fair point. I handn't considered that the bot would need to spend bits.
