### ISSUE TITLE
Founders timed out by bot link checker

### ISSUE THREAD

**Issue by Prozvonit** [pajbot/pajbot#820]
The link checker module is set to deny non-subs the ability to link. We ran into a problem when a founder couldn't link. Even though they were subbed, they got a timeout.
Current settings:
![image](https://user-images.githubusercontent.com/36782050/78451545-2f3bcc80-7654-11ea-80a7-db01a1751339.png)
![image](https://user-images.githubusercontent.com/36782050/78451595-6316f200-7654-11ea-97b8-e08b629ad65b.png)

**Comment by alazymeme** [comment]
Can confirm: https://i.nuuls.com/e6Uj7.png - gempir enabled link protection in pajlada's channel and the founder got timed out
