### ISSUE TITLE
Create a offlineonly/onlineonly command setting

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#822]
Variables that only allow commands to be used online/offline only accordingly.

**Comment by RAnders00** [comment]
This should really be a per-command setting. Introducing a variable for this is a hack.

**Comment by alazymeme** [comment]
Yes

**Comment by RAnders00** [comment]
Due to pajbot [being moved into maintenance mode](https://github.com/pajbot/pajbot/blob/master/README.md) I'm closing this feature request.
