### ISSUE TITLE
Include sub tier in user model

### ISSUE THREAD

**Issue by DatGuy1** [pajbot/pajbot#827]
Tier is fetched anyways at https://github.com/pajbot/pajbot/blob/master/pajbot/apiwrappers/twitch/helix.py#L149. I'd recommend using tuples for https://github.com/pajbot/pajbot/blob/master/pajbot/modules/subscriber_fetch.py#L42. Could do this myself but if anyone else wants to feel free

**Comment by RAnders00** [comment]
Due to pajbot [being moved into maintenance mode](https://github.com/pajbot/pajbot/blob/master/README.md) I'm closing this feature request.
