### ISSUE TITLE
Add an emote spam filter

### ISSUE THREAD

**Issue by Prozvonit** [pajbot/pajbot#834]
Timeout messages containing excessive amounts of emotes.
If max is set at 15 and the user sends 18 emotes in a message it times them out for a chosen amount of time. This would be able to check for both regular Twitch emotes and 3rd party emotes.

**Comment by alazymeme** [comment]
I'd like to say that this is the point of the max message filter module; but it really doesn't cut it. Since NaM is such a big emote and such a short length, I think an emote filter would be nice - it could probably be integrated with the existing emote timeout module.
