### ISSUE TITLE
Improvements to the CLR emotes on screen module

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#837]
Add a few more options to it:
- Ignore duplicates (only shows one of an emote if there are multiple in a message)
- Combo required - possibly all emotes past a 15x combo (15 individual lines) will display on screen in order to reduce spam

**Comment by TroyDota** [comment]
Ignore duplicates (only shows one of an emote if there are multiple in a message) does it show more than one if there are 2?

**Comment by alazymeme** [comment]
Yes
![image](https://user-images.githubusercontent.com/12804673/82540075-d7b8d800-9b91-11ea-90f0-80da528b71eb.png)

**Comment by RAnders00** [comment]
Due to pajbot [being moved into maintenance mode](https://github.com/pajbot/pajbot/blob/master/README.md) I'm closing this feature request.
