### ISSUE TITLE
IDs should be given in whispers when adding black/whitelisted links

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#850]
Just like banphrases, pajbot should tell you the id of the black/whitelisted link when adding it. Also, Instead of `Successfully added your links`, the response should be customized according to what you are adding. `Added your blacklisted link (ID:<id>)` or `Added your whitelisted link (ID:<id>)`
![image](https://user-images.githubusercontent.com/12804673/80863360-0e03e580-8cbf-11ea-8ade-31bb761dbd6f.png)

**Comment by RAnders00** [comment]
Due to pajbot [being moved into maintenance mode](https://github.com/pajbot/pajbot/blob/master/README.md) I'm closing this feature request.
