### ISSUE TITLE
Whitespace when no subscriber badges are enabled

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#854]
![image](https://user-images.githubusercontent.com/12804673/80913954-b7b0a880-8d8b-11ea-9706-637dcf1763e4.png)

**Comment by RAnders00** [comment]
isn't it kind of the bot installer's fault for not downloading a sub badge?

The whitespace won't appear on channels without subs because nobody will have the sub badge.

**Comment by alazymeme** [comment]
Yes, but if you have `subscriber_badge_version` set to `-1`, then the badge space shouldn't exist. Since this was a new bot installation, your theory would be correct, but once i set this to `-1`, the bot should no longer show these badges. No?

![image](https://user-images.githubusercontent.com/12804673/81467591-042d3580-921d-11ea-8f9e-ec1bda457060.png)

**Comment by RAnders00** [comment]
Setting that setting to -1 disables the **downloading** of the sub badge, in case you want to manage the image yourself. However it definitely should not disable sub badges on the website.

Is this really a useful setting though? Why would you want to disable sub badges?

**Comment by alazymeme** [comment]
Usually I'd disable it if I use pajbot for moderation only

**Comment by pajlada** [comment]
> Usually I'd disable it if I use pajbot for moderation only

why? just enable it. what's the concern with having it enabled?

**Comment by RAnders00** [comment]
We can talk about using the default twitch sub badge (the purple star) as a fallback

**Comment by alazymeme** [comment]
> 
> 
> > Usually I'd disable it if I use pajbot for moderation only
> 
> why? just enable it. what's the concern with having it enabled?

If this is the case, why do we allow users to turn it off using `-1`? Why not just force enable it?

**Comment by pajlada** [comment]
> Setting that setting to -1 disables the **downloading** of the sub badge, in case you want to manage the image yourself. However it definitely should not disable sub badges on the website.

@alazymeme :point_up:
