### ISSUE TITLE
Bot eval'ing from files sometimes doesn't work

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#855]
As per this picture, the bot has indicated that all the lines have been eval'ed: https://i.imgur.com/QmHxOxx.png

But as per the playsounds page, none of the playsounds have been imported:
![image](https://user-images.githubusercontent.com/12804673/80914642-2abc1e00-8d90-11ea-8129-9b066f1a52a0.png)

This only seems to work when it spam whispers you that the playsound has been imported. This specifically seems to be an issue if the playsounds module is disabled.

**Comment by RAnders00** [comment]
You need to enable the playsounds module to use `!add playsound`.

**Comment by RAnders00** [comment]
Also I realize this way of importing playsounds is far from optimal, but that should be handled in a different issue
