### ISSUE TITLE
Make a !suggest command

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#865]
I'm not sure if it's possible - but a `!suggest` command that would connect to the GitHub API and make a new issue. The issue would be made by a bot account, but would mention the twitch user in the description

**Comment by RAnders00** [comment]
I think this is a not a good feature, but I'll let @pajlada weigh in first.

**Comment by pajlada** [comment]
Not really an api I want to interact with from a Twitch bot, so the so the way its described in this issue is a no for me too.
