### ISSUE TITLE
TMI Limits

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#867]
Given the whisper limits given to new accounts, I think the whisper limit should be set to 0 for bots that don't use the `verified = 1` parameter. Then the bot won't attempt to whisper users when it can't (and get globally limited as a result)

**Comment by RAnders00** [comment]
can you post that comment again, but unter #691? I think it's sort of more relevant if all things closely related to the behaviour of `verified = 1/0` is kept in that issue.
