### ISSUE TITLE
maxmsglength whisper timeout reason doesn't work

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#873]
![image](https://user-images.githubusercontent.com/12804673/82117671-f21b3c00-97b4-11ea-9049-2574ed3f92d3.png)
![image](https://user-images.githubusercontent.com/12804673/82117672-f7788680-97b4-11ea-8317-dab333824a9b.png)

**Comment by RAnders00** [comment]
https://github.com/pajbot/pajbot/blob/bd4463ea22589784f0b5615fcb3760cbb2426c50/pajbot/modules/maxmsglength.py#L86-L87
