### ISSUE TITLE
Timeout for Channel points.

### ISSUE THREAD

**Issue by Parrallax** [pajbot/pajbot#880]
It would be cool if we could use channel points to time people out and untime people out. Integrating channel points to use all modules could be really cool and really helpful.

**Comment by JonasXc** [comment]
It would be great if you could implement something like that :D

**Comment by SlimTheGiraffe** [comment]
I think this would be a fantastic idea! Nice way to get people to spend those hard earned points and keep the stream as interactive as possible.

**Comment by TroyDota** [comment]
Requires 
- Pubsub implementation

**Comment by Parrallax** [comment]
what’s a pr? Can you give me more detail on how this works

**Comment by Parrallax** [comment]
@TroyDota

**Comment by Parrallax** [comment]
@TroyDota do you know how long this could take. Your saying, you already have a system worked out for this?

**Comment by TroyDota** [comment]
@Parrallax Well i made the pr for the streamer token, When that gets accepted then ill add a feature to complete this issue. I didnt make this feature specifically, but i made one for text to speech from channel points and its basically the same.

**Comment by Parrallax** [comment]
@TroyDota could you add me on discord. .hayden#0904

**Comment by RAnders00** [comment]
Due to pajbot [being moved into maintenance mode](https://github.com/pajbot/pajbot/blob/master/README.md) I'm closing this feature request.
