### ISSUE TITLE
Clear Chat function problems

### ISSUE THREAD

**Issue by TroyDota** [pajbot/pajbot#881]
- Throws an error when /clear command is called from chat
- Permaban doesnt do anything in the database.

**Comment by RAnders00** [comment]
On the second bullet point, see #882 and my review comment:

> The only data we store for each user is a timeout_end, as you can imagine, you can't fit permabans into that sort of model, which is why we just clear the timeout_end field on permaban.
> Reason is: There's just currently no use to knowing a user is banned (so why bother implementing it/storing it?). the only thing we use timeout_end for is the paid timeout module (so you can stack timeouts).
