### ISSUE TITLE
Individual toggles for !bttvemotes, !ffzemotes, !subemotes

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#883]
Some channels using pajbot may not be affiliate/partner. It would be nice to be able to individually toggle each of the emotes commands.

**Comment by RAnders00** [comment]
The subemotes command even has a special case for when no emotes are available. Is that not good enough for you?

**Comment by RAnders00** [comment]
https://github.com/pajbot/pajbot/blob/37da06f4f18237486513e86eb2efcb80d5755bf4/pajbot/modules/basic/emotes.py#L70
