### ISSUE TITLE
Add emoji detection to the Emote Limit module

### ISSUE THREAD

**Issue by Prozvonit** [pajbot/pajbot#885]
Add emoji detection to the Emote Limit module. Currently the module doesn't count emojis as emotes and it would be nice for it to detect those too.

**Comment by RAnders00** [comment]
sort of related: #489

**Comment by RAnders00** [comment]
Due to pajbot [being moved into maintenance mode](https://github.com/pajbot/pajbot/blob/master/README.md) I'm closing this feature request.
