### ISSUE TITLE
502 Bad Gateway Error

### ISSUE THREAD

**Issue by DGRuben** [pajbot/pajbot#889]
I've looked around and found issue #731 and had the exact same issue as me. When I check /var/log/nginx/error.log it says it cant find web.sock. It was the same problem for him, but I'm kinda noob at this and I have no clue how he fixed it.

**Comment by RAnders00** [comment]
Most likely the web process isn't running. You can check its status with `sudo systemctl status pajbot-web@streamer_name` and its log output with `sudo journalctl -eu pajbot-web@streamer_name`.

**Comment by DGRuben** [comment]
> Most likely the web process isn't running. You can check its status with `sudo systemctl status pajbot-web@streamer_name` and its log output with `sudo journalctl -eu pajbot-web@streamer_name`.

You were right, it was running but got some errors I managed to fix. But now I got a problem that my domain isn't working, I didnt get any errors with the SSL stuff

**Comment by DGRuben** [comment]
> > Most likely the web process isn't running. You can check its status with `sudo systemctl status pajbot-web@streamer_name` and its log output with `sudo journalctl -eu pajbot-web@streamer_name`.
> 
> You were right, it was running but got some errors I managed to fix. But now I got a problem that my domain isn't working, I didnt get any errors with the SSL stuff

Fixed that, now I'm running where my bot doesn't work in chat itself.

**Comment by DGRuben** [comment]
`May 22 01:36:47 server3 systemd[1]: Stopping pajbot for kardyg...
May 22 01:36:47 server3 pajbot@kardyg[52669]: [2020-05-22 01:36:47,102] [ERROR  ] Exception caught while trying to say quit phrase
May 22 01:36:47 server3 pajbot@kardyg[52669]: Traceback (most recent call last):
May 22 01:36:47 server3 pajbot@kardyg[52669]:   File "/opt/pajbot/pajbot/bot.py", line 841, in quit_bot
May 22 01:36:47 server3 pajbot@kardyg[52669]:     self.privmsg(p.format(**phrase_data))
May 22 01:36:47 server3 pajbot@kardyg[52669]:   File "/opt/pajbot/pajbot/bot.py", line 496, in privmsg
May 22 01:36:47 server3 pajbot@kardyg[52669]:     return self.irc.privmsg(message, channel, increase_message=increase_message)
May 22 01:36:47 server3 pajbot@kardyg[52669]:   File "/opt/pajbot/pajbot/managers/irc.py", line 44, in privmsg
May 22 01:36:47 server3 pajbot@kardyg[52669]:     self.connection_manager.privmsg(channel, message, increase_message=increase_message)
May 22 01:36:47 server3 pajbot@kardyg[52669]:   File "/opt/pajbot/pajbot/managers/connection.py", line 125, in privmsg
May 22 01:36:47 server3 pajbot@kardyg[52669]:     conn.privmsg(channel, message)
May 22 01:36:47 server3 pajbot@kardyg[52669]:   File "/opt/pajbot/venv/lib/python3.8/site-packages/irc/client.py", line 560, in privmsg
May 22 01:36:47 server3 pajbot@kardyg[52669]:     self.send_items('PRIVMSG', target, ':' + text)
May 22 01:36:47 server3 pajbot@kardyg[52669]:   File "/opt/pajbot/venv/lib/python3.8/site-packages/irc/client.py", line 591, in send_items
May 22 01:36:47 server3 pajbot@kardyg[52669]:     self.send_raw(' '.join(filter(None, items)))
May 22 01:36:47 server3 pajbot@kardyg[52669]:   File "/opt/pajbot/pajbot/managers/connection.py", line 40, in send_raw
May 22 01:36:47 server3 pajbot@kardyg[52669]:     raise ServerNotConnectedError("Not connected.")
May 22 01:36:47 server3 pajbot@kardyg[52669]: irc.client.ServerNotConnectedError: Not connected.
May 22 01:36:47 server3 pajbot@kardyg[52669]: Jobstore default:
May 22 01:36:47 server3 pajbot@kardyg[52669]:     UserRanksRefreshManager._refresh.<locals>.<lambda> (trigger: date[2020-05-22 01:40:12 UTC], next run at: 2020-05-22 01:40:12 UTC)
May 22 01:36:47 server3 pajbot@kardyg[52669]:     ChattersRefreshModule.enable.<locals>.<lambda> (trigger: interval[0:10:00], next run at: 2020-05-22 01:40:17 UTC)
May 22 01:36:47 server3 pajbot@kardyg[52669]:     ModeratorsRefreshModule.enable.<locals>.<lambda> (trigger: interval[0:10:00], next run at: 2020-05-22 01:40:17 UTC)
May 22 01:36:47 server3 pajbot@kardyg[52669]:     SubscriberFetchModule.enable.<locals>.<lambda> (trigger: interval[0:10:00], next run at: 2020-05-22 01:40:17 UTC)
May 22 01:36:47 server3 pajbot@kardyg[52669]:     EmoteManager.update_all_emotes (trigger: interval[1:00:00], next run at: 2020-05-22 02:00:17 UTC)
May 22 01:36:47 server3 systemd[1]: pajbot@kardyg.service: Succeeded.
May 22 01:36:47 server3 systemd[1]: Stopped pajbot for kardyg.
May 22 01:36:47 server3 systemd[1]: Started pajbot for kardyg.
May 22 01:36:47 server3 pajbot@kardyg[56149]: [2020-05-22 01:36:47,839] [DEBUG  ] Loaded config
May 22 01:36:47 server3 pajbot@kardyg[56149]: [2020-05-22 01:36:47,839] [DEBUG  ] Cache Miss: api:twitch:helix:user:by-login:botnextdoor
May 22 01:36:47 server3 pajbot@kardyg[56149]: [2020-05-22 01:36:47,840] [DEBUG  ] Successfully loaded OAuth token from storage
May 22 01:36:48 server3 pajbot@kardyg[56149]: [2020-05-22 01:36:48,129] [DEBUG  ] Cache Miss: api:twitch:helix:user:by-login:kardyg
May 22 01:36:48 server3 pajbot@kardyg[56149]: [2020-05-22 01:36:48,341] [INFO   ] PostgreSQL Server notice: NOTICE:  relation "schema_version" already exists, skipping
May 22 01:36:48 server3 pajbot@kardyg[56149]: [2020-05-22 01:36:48,342] [DEBUG  ] migrate db: current revision ID is 11
May 22 01:36:48 server3 pajbot@kardyg[56149]: [2020-05-22 01:36:48,342] [DEBUG  ] migrate db: 0 revisions to run
May 22 01:36:48 server3 pajbot@kardyg[56149]: [2020-05-22 01:36:48,343] [DEBUG  ] migrate redis: current revision ID is 2
May 22 01:36:48 server3 pajbot@kardyg[56149]: [2020-05-22 01:36:48,343] [DEBUG  ] migrate redis: 0 revisions to run
May 22 01:36:48 server3 pajbot@kardyg[56149]: [2020-05-22 01:36:48,408] [INFO   ] Loaded 0 timers (0 online/0 offline)
May 22 01:36:48 server3 pajbot@kardyg[56149]: [2020-05-22 01:36:48,608] [ERROR  ] babyrage
May 22 01:36:48 server3 pajbot@kardyg[56149]: Traceback (most recent call last):
May 22 01:36:48 server3 pajbot@kardyg[56149]:   File "/opt/pajbot/pajbot/managers/connection.py", line 82, in start
May 22 01:36:48 server3 pajbot@kardyg[56149]:     self.make_new_connection()
May 22 01:36:48 server3 pajbot@kardyg[56149]:   File "/opt/pajbot/pajbot/managers/connection.py", line 107, in make_new_connection
May 22 01:36:48 server3 pajbot@kardyg[56149]:     ip, port, self.bot.nickname, self.bot.password, self.bot.nickname, connect_factory=ssl_factory
May 22 01:36:48 server3 pajbot@kardyg[56149]:   File "/opt/pajbot/pajbot/bot.py", line 282, in password
May 22 01:36:48 server3 pajbot@kardyg[56149]:     return f"oauth:{self.bot_token_manager.token.access_token}"
May 22 01:36:48 server3 pajbot@kardyg[56149]:   File "/opt/pajbot/pajbot/apiwrappers/authentication/token_manager.py", line 75, in token
May 22 01:36:48 server3 pajbot@kardyg[56149]:     self.initialize()
May 22 01:36:48 server3 pajbot@kardyg[56149]:   File "/opt/pajbot/pajbot/apiwrappers/authentication/token_manager.py", line 67, in initialize
May 22 01:36:48 server3 pajbot@kardyg[56149]:     self._token = self.fetch_new()
May 22 01:36:48 server3 pajbot@kardyg[56149]:   File "/opt/pajbot/pajbot/apiwrappers/authentication/token_manager.py", line 106, in fetch_new
May 22 01:36:48 server3 pajbot@kardyg[56149]:     raise NoTokenError(f"No authentication token found for user {self.username} ({self.user_id}) in redis")
May 22 01:36:48 server3 pajbot@kardyg[56149]: pajbot.apiwrappers.authentication.token_manager.NoTokenError: No authentication token found for user botnextdoor (97661864) in redis`
heres my logs when i restart

**Comment by alazymeme** [comment]
Have you logged in with the bot? Your logs seem to indicate that your bot's name is `botnextdoor`, yet that is the bot used in nymn's channel? 🤔

**Comment by DGRuben** [comment]
> Have you logged in with the bot? Your logs seem to indicate that your bot's name in the config is `botnextdoor`, yet that is the bot used in nymn's channel? 🤔
> 
> Unless I'm missing something else

Ye I didn't know any other name, but I've already changed it.. Still getting the same error

**Comment by DGRuben** [comment]
When I use .com/bot_login and I login it redirects me to .com/login/None and I get a 404 Page not found. I don't know if that has to do with anything

**Comment by RAnders00** [comment]
Sorry, that's a bug that has been fixed and will be in the next release, but it doesn't prevent you from authorizing the bot.

@DGRuben You need to set the bot name to the name of the account you created with Twitch. If you made changes to the config you also need to restart the bot and web interface afterwards.

**Comment by DGRuben** [comment]
> Sorry, that's a bug that has been fixed and will be in the next release, but it doesn't prevent you from authorizing the bot.
> 
> @DGRuben You need to set the bot name to the name of the account you created with Twitch. If you made changes to the config you also need to restart the bot and web interface afterwards.

So I have to create a twitch account that has the exact same name as the bot has and create the bot on that specific twitch account?

**Comment by RAnders00** [comment]
That's how it works on Twitch, yes. You can create multiple accounts under the same e-mail on twitch, see here: https://help.twitch.tv/s/article/twitch-account-settings?language=en_US#securityandprivacy

Then you set the bot's nickname to the name you chose, you restart the bot, and then you do the bot_login process. All of this is documented in more detail in the install instructions as well. https://github.com/pajbot/pajbot/tree/master/install-docs#authenticate-the-bot

**Comment by DGRuben** [comment]
> That's how it works on Twitch, yes. You can create multiple accounts under the same e-mail on twitch, see here: https://help.twitch.tv/s/article/twitch-account-settings?language=en_US#securityandprivacy
> 
> Then you set the bot's nickname to the name you chose, you restart the bot, and then you do the bot_login process. All of this is documented in more detail in the install instructions as well. https://github.com/pajbot/pajbot/tree/master/install-docs#authenticate-the-bot

Oh okay, thats probably where it went wrong, will try this now

**Comment by DGRuben** [comment]
Yes! It's fully working now, thanks for the help!
