### ISSUE TITLE
Make commands for modules customizable

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#891]

**Comment by RAnders00** [comment]
Can you expand on this, what do you want to be added?

**Comment by alazymeme** [comment]
> Can you expand on this, what do you want to be added?

So adding the ability to change the default commands. Where `!roulette` would be for the roulette module, some people may want it as `!gamble` etc etc - basically the same thing as the settitle and setgame commands

**Comment by alazymeme** [comment]
Yeah this was fixed by one of my PRs, I'll just close it.
