### ISSUE TITLE
Language filter

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#893]
Make a language filter that will time out all other languages other than what is selected. I see plenty of people complaining about the fact that this is an option to select on the twitch dashboard, yet has no tools made by twitch in order to enforce it.

**Comment by RAnders00** [comment]
How would you envision this to work. Based on special characters (e.g. cyrillic) being used?

**Comment by alazymeme** [comment]
> How would you envision this to work? Based on special characters (e.g. cyrillic) being used?

Perhaps it would store x amount of messages and match similarity to others in chat:

![image](https://user-images.githubusercontent.com/12804673/83328998-338a0c00-a2ca-11ea-8829-c2a42e2061da.png)

**Comment by alazymeme** [comment]
> How would you envision this to work? Based on special characters (e.g. cyrillic) being used?

I'm not 100% sure, I'm hoping somebody has made a language library or something 🤔

**Comment by alazymeme** [comment]
@RAnders00 Would it be possible to use something like this? https://pypi.org/project/language-detector/

**Comment by RAnders00** [comment]
I looked at it, it seems ok to use, but you shouldn't expect perfect results. It's based on detecting characters most common to certain languages. If somebody talks in a different language without using accents etc. I don't think the library will have much luck detecting it.

https://github.com/DanielJDufour/language-detector/blob/master/language_detector/__init__.py

https://github.com/DanielJDufour/language-detector/blob/master/language_detector/prep/char_language.txt

**Comment by alazymeme** [comment]
Could this be something simple like "if the language of (message) does not equal what is selected, then time the user out"?

**Comment by RAnders00** [comment]
I'd say put a checkbox for every language the library can detect (wether to allow this language)

**Comment by RAnders00** [comment]
Due to pajbot [being moved into maintenance mode](https://github.com/pajbot/pajbot/blob/master/README.md) I'm closing this feature request.
