### ISSUE TITLE
One man spam filter

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#894]

**Comment by RAnders00** [comment]
Can you elaborate on how this is supposed to work?

**Comment by alazymeme** [comment]
> Can you elaborate on how this is supposed to work?

Perhaps it would store x amount of messages and match similarity to others in chat:

![image](https://user-images.githubusercontent.com/12804673/83328998-338a0c00-a2ca-11ea-8829-c2a42e2061da.png)

**Comment by alazymeme** [comment]
While this was a good idea (in my eyes at least), I don't think it's fitting for pajbot.
