### ISSUE TITLE
Add a random chatter/user/number variable

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#898]
Currently I make use of decapi's random user/number endpoint. But using multiple of the same urlfetch variables in the same response returns the same response. So ideally the variable would fetch different users per use.

**Comment by TroyDota** [comment]
Also, random numbers.

**Comment by RAnders00** [comment]
Due to pajbot [being moved into maintenance mode](https://github.com/pajbot/pajbot/blob/master/README.md) I'm closing this feature request.
