### ISSUE TITLE
twitter service not showing the full tweet

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#903]
Weird issue, I run the twitter service on my own bot; but tweet-provider on all my other bots. It seems that the twitter service does not print the full tweet as opposed to tweet-provider:

Tweet Provider:
![image](https://user-images.githubusercontent.com/12804673/83965748-5daa8200-a8f9-11ea-99d9-da58f2e1073e.png)

Regular twitter service:
![image](https://user-images.githubusercontent.com/12804673/83965752-6733ea00-a8f9-11ea-88f6-ead1b76f02e7.png)

**Comment by pajlada** [comment]
Not going to fiddle with non-tweet-provider streaming issues
