### ISSUE TITLE
Make so the !bttvemotes & !ffzemotes command give a link to BTTV/FFZ.

### ISSUE THREAD

**Issue by Fawcan** [pajbot/pajbot#910]
With all the new slots of BTTV emotes being added the current !bttvemotes command posts 4 different messages with emotes, it would be better and less spammy if it just sent a link to the BTTV website (like this one https://betterttv.com/users/559ad81fa287f9ec6c0a6ff3 )

**Comment by RAnders00** [comment]
Can't you do this by just disabling the !bttvemotes command (note that this was recently added, see [the changelog](https://github.com/pajbot/pajbot/blob/master/CHANGELOG.md)) - and then adding a custom command with just the link.
