### ISSUE TITLE
Add an alias option to call a command's response to timers

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#915]
Basically it would allow the editing of commands without having to adjust the timer.

**Comment by alazymeme** [comment]
Nightbot is a great example
![image](https://user-images.githubusercontent.com/12804673/84568297-c1cdba00-adc1-11ea-8549-f95bc609342f.png)

**Comment by RAnders00** [comment]
Due to pajbot [being moved into maintenance mode](https://github.com/pajbot/pajbot/blob/master/README.md) I'm closing this feature request.
