### ISSUE TITLE
pajbot does not recognize the bot as an editor

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#922]
![image](https://user-images.githubusercontent.com/12804673/85240889-31583f00-b47d-11ea-8192-7fc429b30645.png)
![image](https://user-images.githubusercontent.com/12804673/85240900-3b7a3d80-b47d-11ea-8477-c55a7050c400.png)

This was fixed by having weest login via the streamer_login page

**Comment by RAnders00** [comment]
Are you sure that the RoboWeest token has the requisite scope? Run `redis-cli --raw GET authentication:user-access-token:198445737 | jq .` and check that the `scope` contains `channel_editor`.

- If not, run through the `/bot_login` process again, then restart the bot
- If yes, this is a bug 👀

**Comment by alazymeme** [comment]
> Are you sure that the RoboWeest token has the requisite scope? Run `redis-cli --raw GET authentication:user-access-token:198445737 | jq .` and check that the `scope` contains `channel_editor`.
> 
> * If not, run through the `/bot_login` process again, then restart the bot
> * If yes, this is a bug 👀

I fixed it by re-authing the streamer_login page. But I might be able to reproduce this on another bot just by changing the client id and token.

**Comment by TroyDota** [comment]
This is a bug, https://github.com/pajbot/pajbot/blob/69679c78475662e2b7948fe63d529a755c47fc80/pajbot/modules/basic/stream_update.py#L61 this should still work.

**Comment by RAnders00** [comment]
@alazymeme can you please run the suggested redis command and report back, because it gives the necessary insight.

**Comment by TroyDota** [comment]
> re-authing the streamer_login

Didnt he overwrite the oauth?

**Comment by RAnders00** [comment]
If he did `streamer_login` then yes the streamer token would be overridden, but I was looking into the scope of the bot token, whether there was `channel_editor` in there.

**Comment by RAnders00** [comment]
So through Twitch chat I got confirmation by @alazymeme that the bot token does and did have `channel_editor` scope. I suspect since the token still appears to work fine that this might have been a temporary failure on Twitch's end.
