### ISSUE TITLE
no-referrer-when-downgrade when trying to visit the bot_login url while setting up the bot

### ISSUE THREAD

**Issue by PrestonRoberts** [pajbot/pajbot#928]
I followed the detailed installation docs and when i went to https://streamer_name.your-domain.com/bot_login where the streamer_name and domain name are my own the web page doesn't load but the error it gives me is "no-referrer-when-downgrade". The sudo nginx -t passes and status says everything is good. The error logs for nginx also don't say anything. I used a domain from google and used the cloudflare tutorial. Sorry if I am being dumb and I just missed something but how can I troubleshoot this/where should I be looking to fix this issue?

**Comment by PrestonRoberts** [comment]
After doing some research on other issues I was also able to find this error

pajbot-web@poberts[44413]: *** Operational MODE: single process ***
pajbot-web@poberts[44413]: Traceback (most recent call last):
pajbot-web@poberts[44413]:   File "./app.py", line 20, in <module>
pajbot-web@poberts[44413]:     pajbot.web.init(args)
pajbot-web@poberts[44413]:   File "./pajbot/web/__init__.py", line 75, in init
pajbot-web@poberts[44413]:     with open(args.config, "w") as configfile:
pajbot-web@poberts[44413]: PermissionError: [Errno 13] Permission denied: 'configs/poberts.ini'
pajbot-web@poberts[44413]: unable to load app 0 (mountpoint='') (callable not found or import error)
pajbot-web@poberts[44413]: *** no app loaded. GAME OVER ***
pajbot-web@poberts[44413]: VACUUM: unix socket /var/run/pajbot/poberts/web.sock removed.
pajbot-web@poberts.service: Main process exited, code=exited, status=22/n/a
pajbot-web@poberts.service: Failed with result 'exit-code'.

And also this 

● pajbot-web@poberts.service - pajbot-web for poberts
     Loaded: loaded (/etc/systemd/system/pajbot-web@.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Sat 2020-07-04 02:41:08 EDT; 472ms ago
    Process: 44674 ExecStart=/opt/pajbot/venv/bin/uwsgi --ini uwsgi_shared.ini --socket /var/run/pajbot/poberts/web.sock --pyargv --config configs/poberts.ini --virtualenv venv (code=exited, status=22)
   Main PID: 44674 (code=exited, status=22)

pajbot-web@poberts.service: Main process exited, code=exited, status=22/n/a
pajbot-web@poberts.service: Failed with result 'exit-code'.

**Comment by TroyDota** [comment]
The problem came when you `nano` edited a file without `sudo` to fix simply do
`sudo chron pajbot:pajbot /path/to/config`

**Comment by PrestonRoberts** [comment]
Ok that got me through that issue but the website is still not working. Now the error I got was this:

Jul 04 03:35:18 preston-VirtualBox pajbot-web@poberts[45095]: *** Operational MODE: single process ***
Jul 04 03:35:19 preston-VirtualBox pajbot-web@poberts[45095]: [2020-07-04 03:35:19,997] [ERROR  ] Error downloading the streamers profile picture
Jul 04 03:35:19 preston-VirtualBox pajbot-web@poberts[45095]: Traceback (most recent call last):
Jul 04 03:35:19 preston-VirtualBox pajbot-web@poberts[45095]:   File "./pajbot/web/__init__.py", line 85, in init
Jul 04 03:35:19 preston-VirtualBox pajbot-web@poberts[45095]:     download_logo(twitch_helix_api, streamer, streamer_user_id)
Jul 04 03:35:19 preston-VirtualBox pajbot-web@poberts[45095]:   File "./pajbot/web/utils.py", line 78, in download_logo
Jul 04 03:35:19 preston-VirtualBox pajbot-web@poberts[45095]:     with open(logo_raw_path, "wb") as logo_raw_file:
Jul 04 03:35:19 preston-VirtualBox pajbot-web@poberts[45095]: PermissionError: [Errno 13] Permission denied: 'static/images/logo_poberts.png'
Jul 04 03:35:20 preston-VirtualBox pajbot-web@poberts[45095]: [2020-07-04 03:35:20,077] [ERROR  ] Error downloading the streamers subscriber badge
Jul 04 03:35:20 preston-VirtualBox pajbot-web@poberts[45095]: Traceback (most recent call last):
Jul 04 03:35:20 preston-VirtualBox pajbot-web@poberts[45095]:   File "./pajbot/web/__init__.py", line 94, in init
Jul 04 03:35:20 preston-VirtualBox pajbot-web@poberts[45095]:     download_sub_badge(twitch_badges_api, streamer, streamer_user_id, subscriber_badge_version)
Jul 04 03:35:20 preston-VirtualBox pajbot-web@poberts[45095]:   File "./pajbot/web/utils.py", line 103, in download_sub_badge
Jul 04 03:35:20 preston-VirtualBox pajbot-web@poberts[45095]:     with open(subscriber_badge_path, "wb") as subscriber_badge_file:
Jul 04 03:35:20 preston-VirtualBox pajbot-web@poberts[45095]: PermissionError: [Errno 13] Permission denied: 'static/images/badge_sub_poberts.png'
Jul 04 03:35:20 preston-VirtualBox pajbot-web@poberts[45095]: [2020-07-04 03:35:20,119] [ERROR  ] add_handler No handler for on_message found.
Jul 04 03:35:20 preston-VirtualBox pajbot-web@poberts[45095]: [2020-07-04 03:35:20,128] [ERROR  ] add_handler No handler for on_pubmsg found.
Jul 04 03:35:20 preston-VirtualBox pajbot-web@poberts[45095]: [2020-07-04 03:35:20,131] [ERROR  ] add_handler No handler for on_message found.
Jul 04 03:35:20 preston-VirtualBox pajbot-web@poberts[45095]: [2020-07-04 03:35:20,131] [ERROR  ] add_handler No handler for on_commit found.
Jul 04 03:35:20 preston-VirtualBox pajbot-web@poberts[45095]: [2020-07-04 03:35:20,135] [ERROR  ] add_handler No handler for on_usernotice found.
Jul 04 03:35:20 preston-VirtualBox pajbot-web@poberts[45095]: WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x5596ba365f50 pid: 45095 (default app)
Jul 04 03:35:20 preston-VirtualBox pajbot-web@poberts[45095]: *** uWSGI is running in multiple interpreter mode ***
Jul 04 03:35:20 preston-VirtualBox pajbot-web@poberts[45095]: spawned uWSGI master process (pid: 45095)
Jul 04 03:35:20 preston-VirtualBox pajbot-web@poberts[45095]: spawned uWSGI worker 1 (pid: 45102, cores: 1)

I'm not sure if this is related but my bot has this error:

Jul 04 03:35:17 preston-VirtualBox pajbot@poberts[43424]: [2020-07-04 03:35:17,738] [ERROR  ] Exception caught while trying to say quit phrase
Jul 04 03:35:17 preston-VirtualBox pajbot@poberts[43424]: Traceback (most recent call last):
Jul 04 03:35:17 preston-VirtualBox pajbot@poberts[43424]:   File "/opt/pajbot/pajbot/bot.py", line 880, in quit_bot
Jul 04 03:35:17 preston-VirtualBox pajbot@poberts[43424]:     self.privmsg(p.format(**phrase_data))
Jul 04 03:35:17 preston-VirtualBox pajbot@poberts[43424]:   File "/opt/pajbot/pajbot/bot.py", line 501, in privmsg
Jul 04 03:35:17 preston-VirtualBox pajbot@poberts[43424]:     self.irc.privmsg(channel, message, is_whisper=False)
Jul 04 03:35:17 preston-VirtualBox pajbot@poberts[43424]:   File "/opt/pajbot/pajbot/managers/irc.py", line 105, in privmsg
Jul 04 03:35:17 preston-VirtualBox pajbot@poberts[43424]:     self.conn.privmsg(channel, message)
Jul 04 03:35:17 preston-VirtualBox pajbot@poberts[43424]:   File "/opt/pajbot/venv/lib/python3.8/site-packages/irc/client.py", line 560, in privmsg
Jul 04 03:35:17 preston-VirtualBox pajbot@poberts[43424]:     self.send_items('PRIVMSG', target, ':' + text)
Jul 04 03:35:17 preston-VirtualBox pajbot@poberts[43424]:   File "/opt/pajbot/venv/lib/python3.8/site-packages/irc/client.py", line 591, in send_items
Jul 04 03:35:17 preston-VirtualBox pajbot@poberts[43424]:     self.send_raw(' '.join(filter(None, items)))
Jul 04 03:35:17 preston-VirtualBox pajbot@poberts[43424]:   File "/opt/pajbot/pajbot/managers/irc.py", line 37, in send_raw
Jul 04 03:35:17 preston-VirtualBox pajbot@poberts[43424]:     raise ServerNotConnectedError("Not connected.")
Jul 04 03:35:17 preston-VirtualBox pajbot@poberts[43424]: irc.client.ServerNotConnectedError: Not connected.
Jul 04 03:35:17 preston-VirtualBox pajbot@poberts[43424]: Jobstore default:
Jul 04 03:35:17 preston-VirtualBox pajbot@poberts[43424]:     ChattersRefreshModule.enable.<locals>.<lambda> (trigger: interval[0:10:00], next run at: 2020-07-04 03:42:12 EDT)
Jul 04 03:35:17 preston-VirtualBox pajbot@poberts[43424]:     ModeratorsRefreshModule.enable.<locals>.<lambda> (trigger: interval[0:10:00], next run at: 2020-07-04 03:42:12 EDT)
Jul 04 03:35:17 preston-VirtualBox pajbot@poberts[43424]:     SubscriberFetchModule.enable.<locals>.<lambda> (trigger: interval[0:10:00], next run at: 2020-07-04 03:42:12 EDT)
Jul 04 03:35:17 preston-VirtualBox pajbot@poberts[43424]:     EmoteManager.update_all_emotes (trigger: interval[1:00:00], next run at: 2020-07-04 04:22:12 EDT)
Jul 04 03:35:17 preston-VirtualBox systemd[1]: Stopping pajbot for poberts...
Jul 04 03:35:17 preston-VirtualBox systemd[1]: pajbot@poberts.service: Succeeded.
Jul 04 03:35:17 preston-VirtualBox systemd[1]: Stopped pajbot for poberts.
Jul 04 03:35:18 preston-VirtualBox systemd[1]: Started pajbot for poberts.
Jul 04 03:35:18 preston-VirtualBox pajbot@poberts[45068]: [2020-07-04 03:35:18,498] [DEBUG  ] Loaded config
Jul 04 03:35:18 preston-VirtualBox pajbot@poberts[45068]: [2020-07-04 03:35:18,499] [DEBUG  ] Cache Miss: api:twitch:helix:user:by-login:pobertsbot
Jul 04 03:35:18 preston-VirtualBox pajbot@poberts[45068]: [2020-07-04 03:35:18,499] [DEBUG  ] Successfully loaded OAuth token from storage
Jul 04 03:35:18 preston-VirtualBox pajbot@poberts[45068]: [2020-07-04 03:35:18,685] [INFO   ] PostgreSQL Server notice: NOTICE:  relation "schema_version" already exists, skipping
Jul 04 03:35:18 preston-VirtualBox pajbot@poberts[45068]: [2020-07-04 03:35:18,685] [DEBUG  ] migrate db: current revision ID is 11
Jul 04 03:35:18 preston-VirtualBox pajbot@poberts[45068]: [2020-07-04 03:35:18,686] [DEBUG  ] migrate db: 0 revisions to run
Jul 04 03:35:18 preston-VirtualBox pajbot@poberts[45068]: [2020-07-04 03:35:18,687] [DEBUG  ] migrate redis: current revision ID is 2
Jul 04 03:35:18 preston-VirtualBox pajbot@poberts[45068]: [2020-07-04 03:35:18,687] [DEBUG  ] migrate redis: 0 revisions to run
Jul 04 03:35:18 preston-VirtualBox pajbot@poberts[45068]: [2020-07-04 03:35:18,741] [INFO   ] Loaded 0 timers (0 online/0 offline)
Jul 04 03:35:18 preston-VirtualBox pajbot@poberts[45068]: [2020-07-04 03:35:18,743] [DEBUG  ] Cache Miss: api:bttv:global-emotes
Jul 04 03:35:18 preston-VirtualBox pajbot@poberts[45068]: [2020-07-04 03:35:18,744] [DEBUG  ] Cache Miss: api:ffz:global-emotes
Jul 04 03:35:18 preston-VirtualBox pajbot@poberts[45068]: [2020-07-04 03:35:18,750] [DEBUG  ] Cache Miss: api:twitch:kraken:v5:global-emotes
Jul 04 03:35:19 preston-VirtualBox pajbot@poberts[45068]: [2020-07-04 03:35:19,061] [DEBUG  ] Cache Miss: api:ffz:channel-emotes:poberts
Jul 04 03:35:19 preston-VirtualBox pajbot@poberts[45068]: [2020-07-04 03:35:19,062] [DEBUG  ] Cache Miss: api:bttv:channel-emotes:129997462
Jul 04 03:35:19 preston-VirtualBox pajbot@poberts[45068]: [2020-07-04 03:35:19,063] [DEBUG  ] Cache Miss: api:twitch_emotes:channel-emotes:poberts
Jul 04 03:35:19 preston-VirtualBox pajbot@poberts[45068]: [2020-07-04 03:35:19,247] [ERROR  ] Failed to open connection, retrying in 2 seconds
Jul 04 03:35:19 preston-VirtualBox pajbot@poberts[45068]: Traceback (most recent call last):
Jul 04 03:35:19 preston-VirtualBox pajbot@poberts[45068]:   File "/opt/pajbot/pajbot/managers/irc.py", line 74, in start
Jul 04 03:35:19 preston-VirtualBox pajbot@poberts[45068]:     self._make_new_connection()
Jul 04 03:35:19 preston-VirtualBox pajbot@poberts[45068]:   File "/opt/pajbot/pajbot/managers/irc.py", line 87, in _make_new_connection
Jul 04 03:35:19 preston-VirtualBox pajbot@poberts[45068]:     self.bot.password,
Jul 04 03:35:19 preston-VirtualBox pajbot@poberts[45068]:   File "/opt/pajbot/pajbot/bot.py", line 290, in password
Jul 04 03:35:19 preston-VirtualBox pajbot@poberts[45068]:     return f"oauth:{self.bot_token_manager.token.access_token}"
Jul 04 03:35:19 preston-VirtualBox pajbot@poberts[45068]:   File "/opt/pajbot/pajbot/apiwrappers/authentication/token_manager.py", line 75, in token
Jul 04 03:35:19 preston-VirtualBox pajbot@poberts[45068]:     self.initialize()
Jul 04 03:35:19 preston-VirtualBox pajbot@poberts[45068]:   File "/opt/pajbot/pajbot/apiwrappers/authentication/token_manager.py", line 67, in initialize
Jul 04 03:35:19 preston-VirtualBox pajbot@poberts[45068]:     self._token = self.fetch_new()
Jul 04 03:35:19 preston-VirtualBox pajbot@poberts[45068]:   File "/opt/pajbot/pajbot/apiwrappers/authentication/token_manager.py", line 106, in fetch_new
Jul 04 03:35:19 preston-VirtualBox pajbot@poberts[45068]:     raise NoTokenError(f"No authentication token found for user {self.username} ({self.user_id}) in redis")
Jul 04 03:35:19 preston-VirtualBox pajbot@poberts[45068]: pajbot.apiwrappers.authentication.token_manager.NoTokenError: No authentication token found for user pobertsbot (467225791) in redis
Jul 04 03:35:23 preston-VirtualBox pajbot@poberts[45068]: [2020-07-04 03:35:23,257] [ERROR  ] Logging an uncaught exception (main thread)
Jul 04 03:35:23 preston-VirtualBox pajbot@poberts[45068]: Traceback (most recent call last):
Jul 04 03:35:23 preston-VirtualBox pajbot@poberts[45068]:   File "/opt/pajbot/pajbot/eventloop.py", line 19, in run
Jul 04 03:35:23 preston-VirtualBox pajbot@poberts[45068]:     command.target()
Jul 04 03:35:23 preston-VirtualBox pajbot@poberts[45068]:   File "/opt/pajbot/pajbot/bot.py", line 540, in <lambda>
Jul 04 03:35:23 preston-VirtualBox pajbot@poberts[45068]:     self.reactor.scheduler.execute_after(delay, lambda: function(*args, **kwargs))
Jul 04 03:35:23 preston-VirtualBox pajbot@poberts[45068]:   File "/opt/pajbot/pajbot/managers/irc.py", line 77, in <lambda>
Jul 04 03:35:23 preston-VirtualBox pajbot@poberts[45068]:     self.bot.execute_delayed(2, lambda: self.start())
Jul 04 03:35:23 preston-VirtualBox pajbot@poberts[45068]:   File "/opt/pajbot/venv/lib/python3.8/site-packages/ratelimiter.py", line 75, in wrapped
Jul 04 03:35:23 preston-VirtualBox pajbot@poberts[45068]:     return f(*args, **kwargs)
Jul 04 03:35:23 preston-VirtualBox pajbot@poberts[45068]:   File "/opt/pajbot/pajbot/managers/irc.py", line 71, in start
Jul 04 03:35:23 preston-VirtualBox pajbot@poberts[45068]:     raise AssertionError("start() should not be called while a connection is active")
Jul 04 03:35:23 preston-VirtualBox pajbot@poberts[45068]: AssertionError: start() should not be called while a connection is active

**Comment by TroyDota** [comment]
Ok, so `Jul 04 03:35:20 preston-VirtualBox pajbot-web@poberts[45095]: spawned uWSGI worker 1 (pid: 45102, cores: 1)` means its running, go to /bot_login and /streamer_login and then reboot both, you can do this with `sudo systemctl restart pajbot{,-web}@*`

**Comment by pajlada** [comment]
The issue in your webpage are still permissions-related, this time it's the file `static/images/badge_sub_poberts.png` that isn't writeable by your user. Verify the owner & permission of that file

For the bot error, what TroyDota posted should be enough. The bot is missing credentials to be able to join chat, and after you've authenticated with `bot_login` you have to restart the bot like TroyDota specified in his comment

**Comment by RAnders00** [comment]
I think you forgot some `sudo -u pajbot` prefixes when you were following the instructions. You can fix the permissions though by running `sudo chown -R pajbot:pajbot /opt/pajbot`, then give the services a restart.

**Comment by PrestonRoberts** [comment]
So I am not getting a permission denied issue anymore but the website is still not loading for me the nginx error log doesn't show anything but I get this from website logs

> Jul 04 13:09:35 preston-VirtualBox pajbot-web@poberts[78307]: *** Operational MODE: single process ***
> Jul 04 13:09:35 preston-VirtualBox pajbot-web@poberts[78307]: [2020-07-04 13:09:35,923] [DEBUG  ] Cache Miss: api:twitch:helix:user:by-id:129997462
> Jul 04 13:09:35 preston-VirtualBox pajbot-web@poberts[78307]: [2020-07-04 13:09:35,923] [DEBUG  ] Successfully loaded OAuth token from storage
> Jul 04 13:09:36 preston-VirtualBox pajbot-web@poberts[78307]: [2020-07-04 13:09:36,359] [ERROR  ] add_handler No handler for on_message found.
> Jul 04 13:09:36 preston-VirtualBox pajbot-web@poberts[78307]: [2020-07-04 13:09:36,368] [ERROR  ] add_handler No handler for on_pubmsg found.
> Jul 04 13:09:36 preston-VirtualBox pajbot-web@poberts[78307]: [2020-07-04 13:09:36,371] [ERROR  ] add_handler No handler for on_message found.
> Jul 04 13:09:36 preston-VirtualBox pajbot-web@poberts[78307]: [2020-07-04 13:09:36,371] [ERROR  ] add_handler No handler for on_commit found.
> Jul 04 13:09:36 preston-VirtualBox pajbot-web@poberts[78307]: [2020-07-04 13:09:36,375] [ERROR  ] add_handler No handler for on_usernotice found.
> Jul 04 13:09:36 preston-VirtualBox pajbot-web@poberts[78307]: WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x555a13362f50 pid: 78307 (default app)
> Jul 04 13:09:36 preston-VirtualBox pajbot-web@poberts[78307]: *** uWSGI is running in multiple interpreter mode ***
> Jul 04 13:09:36 preston-VirtualBox pajbot-web@poberts[78307]: spawned uWSGI master process (pid: 78307)
> Jul 04 13:09:36 preston-VirtualBox pajbot-web@poberts[78307]: spawned uWSGI worker 1 (pid: 78318, cores: 1)

and also this.

> Jul 04 13:09:35 preston-VirtualBox pajbot-web@poberts[78307]: [2020-07-04 13:09:35,923] [DEBUG  ] Successfully loaded OAuth token from storage
> Jul 04 13:09:36 preston-VirtualBox pajbot-web@poberts[78307]: [2020-07-04 13:09:36,359] [ERROR  ] add_handler No handler for on_message found.
> Jul 04 13:09:36 preston-VirtualBox pajbot-web@poberts[78307]: [2020-07-04 13:09:36,368] [ERROR  ] add_handler No handler for on_pubmsg found.
> Jul 04 13:09:36 preston-VirtualBox pajbot-web@poberts[78307]: [2020-07-04 13:09:36,371] [ERROR  ] add_handler No handler for on_message found.
> Jul 04 13:09:36 preston-VirtualBox pajbot-web@poberts[78307]: [2020-07-04 13:09:36,371] [ERROR  ] add_handler No handler for on_commit found.
> Jul 04 13:09:36 preston-VirtualBox pajbot-web@poberts[78307]: [2020-07-04 13:09:36,375] [ERROR  ] add_handler No handler for on_usernotice found.
> Jul 04 13:09:36 preston-VirtualBox pajbot-web@poberts[78307]: WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x555a13362f50 pid: 78307 (default app)
> Jul 04 13:09:36 preston-VirtualBox pajbot-web@poberts[78307]: *** uWSGI is running in multiple interpreter mode ***
> Jul 04 13:09:36 preston-VirtualBox pajbot-web@poberts[78307]: spawned uWSGI master process (pid: 78307)
> Jul 04 13:09:36 preston-VirtualBox pajbot-web@poberts[78307]: spawned uWSGI worker 1 (pid: 78318, cores: 1)

I still can't access any part of my website.

**Comment by PrestonRoberts** [comment]
I made a change and I don't get the cache miss anymore, but the website still doesn't work

Jul 04 15:30:02 preston-VirtualBox pajbot-web@poberts[80230]: *** Operational MODE: single process ***
Jul 04 15:30:03 preston-VirtualBox pajbot-web@poberts[80230]: [2020-07-04 15:30:03,914] [ERROR  ] add_handler No handler for on_message found.
Jul 04 15:30:03 preston-VirtualBox pajbot-web@poberts[80230]: [2020-07-04 15:30:03,921] [ERROR  ] add_handler No handler for on_pubmsg found.
Jul 04 15:30:03 preston-VirtualBox pajbot-web@poberts[80230]: [2020-07-04 15:30:03,924] [ERROR  ] add_handler No handler for on_message found.
Jul 04 15:30:03 preston-VirtualBox pajbot-web@poberts[80230]: [2020-07-04 15:30:03,924] [ERROR  ] add_handler No handler for on_commit found.
Jul 04 15:30:03 preston-VirtualBox pajbot-web@poberts[80230]: [2020-07-04 15:30:03,928] [ERROR  ] add_handler No handler for on_usernotice found.
Jul 04 15:30:03 preston-VirtualBox pajbot-web@poberts[80230]: WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x562ec361df50 pid: 80230 (default app)
Jul 04 15:30:03 preston-VirtualBox pajbot-web@poberts[80230]: *** uWSGI is running in multiple interpreter mode ***
Jul 04 15:30:03 preston-VirtualBox pajbot-web@poberts[80230]: spawned uWSGI master process (pid: 80230)
Jul 04 15:30:03 preston-VirtualBox pajbot-web@poberts[80230]: spawned uWSGI worker 1 (pid: 80234, cores: 1)

**Comment by RAnders00** [comment]
The website logs you posted don't indicate any fault.

Note the "cache miss" in the logs is not any error, it's just information on what API calls the website makes.

What exactly do you see in your browser when you visit your website? Show us a screenshot or something.

**Comment by PrestonRoberts** [comment]
Firefox tab on my linux is stuck on loading, here is my chrome. 
I got the domain poberts.com from google domains, and I'm using cloud flare. 
![Screen Shot 2020-07-05 at 9 54 52 AM](https://user-images.githubusercontent.com/40707604/86534383-1686c100-bea6-11ea-9f78-a14e9f3b8cd1.png)
![Screen Shot 2020-07-05 at 9 56 16 AM](https://user-images.githubusercontent.com/40707604/86534389-1edefc00-bea6-11ea-8b9d-f75b9150b590.png)

**Comment by RAnders00** [comment]
The issue you have is not really with pajbot. Your domain is not set up right - you seem to be missing the required DNS entries for `poberts.poberts.com`.

**Comment by PrestonRoberts** [comment]
Thank you guys so much, I solved it by adding a new entry to /etc/hosts for my domain.
