### ISSUE TITLE
Weird ascii timeout bug

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#935]
Debug why this doesn't get timed out:
![image](https://user-images.githubusercontent.com/12804673/87295318-5a359680-c548-11ea-8ee6-78acd09e8b2c.png)

Yet this does:
![image](https://user-images.githubusercontent.com/12804673/87295350-63266800-c548-11ea-9148-09a75bb0fd6a.png)

**Comment by pajlada** [comment]
The way the ASCII module works is it only times out a message if the ratio of ascii/non-ascii characters is too high. The first message has a bunch of normal text which probably pushes the ratio down into the non-timeout area

**Comment by RAnders00** [comment]
![image](https://user-images.githubusercontent.com/1629196/87870729-165cea00-c9ab-11ea-9a9b-91de4b310496.png)
You can configure these limits. This is what it's currently set to in pajlada's chat.
