### ISSUE TITLE
Emojis break $(if) variable parsing

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#936]
![image](https://user-images.githubusercontent.com/12804673/87768681-de955b80-c85f-11ea-982f-56a8e12a9c7d.png)

**Comment by RAnders00** [comment]
Honestly I consider this to be quite low priority. Unless you want to submit a PR fixing this I'll close it. (I belive you have to edit some kind of regex in the ActionParser class, in case you want to give it a try yourself)
