### ISSUE TITLE
Add support for nested $(if) variables

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#937]
![image](https://user-images.githubusercontent.com/12804673/87769738-62037c80-c861-11ea-98c7-027c08a9aaaa.png)

**Comment by alazymeme** [comment]
This seems to occur for urlfetch as well:
![image](https://user-images.githubusercontent.com/12804673/87849459-313c4980-c92c-11ea-96e8-7a96674407aa.png)

**Comment by RAnders00** [comment]
Due to pajbot [being moved into maintenance mode](https://github.com/pajbot/pajbot/blob/master/README.md) I'm closing this feature request.
