### ISSUE TITLE
Rank under Messages sent on my User profile not updating (for months)

### ISSUE THREAD

**Issue by Aubycek** [pajbot/pajbot#971]
If you go to my user profile here: https://xqc.pajbot.com/user/aubycek , you can see that I am Rank 473 under Messages sent. "Messages sent" alone works perfectly, but my Rank has been stuck on this particular number (473) for several months now (6+months). Don't know about other people, but I'm pretty sure it's broken at least for me.

**Comment by TroyDota** [comment]
Might be related to #970 or #966

**Comment by TroyDota** [comment]
Sounds interesting

**Comment by alazymeme** [comment]
![image](https://user-images.githubusercontent.com/12804673/89996695-760a9480-dcce-11ea-87ab-81dca83c6514.png)

Entirely intentional.
